config/system.action.user_add_role_action.site_admin.yml
config/system.action.user_remove_role_action.site_admin.yml
config/system.date.yml
config/user.role.site_admin.yml

**Post Deploy steps:**
```
lando drush cim -y
lando drush cr
```
**Testing instructions:**
- Create a new use with the role: Site Admin
- Log into the site with that user
- check to see that they have access to content, general site configuration, translation configuration, users/roles

VOTE-770 add site admin role

---

config/block_content.type.email_signup.yml
config/core.entity_form_display.block_content.email_signup.default.yml
config/core.entity_view_display.block_content.email_signup.default.yml
config/field.field.block_content.email_signup.field_email_field_label.yml
config/field.field.block_content.email_signup.field_heading.yml
config/field.field.block_content.email_signup.field_link.yml
config/field.field.block_content.email_signup.field_signup_button_label.yml
config/field.storage.block_content.field_email_field_label.yml
config/field.storage.block_content.field_link.yml
config/field.storage.block_content.field_signup_button_label.yml
config/language.content_settings.block_content.email_signup.yml

**Post Deploy steps**:
```
lando drush cim -y
lando drush cr
```
**Testing steps**
- Go to `/admin/structure/block/block-content/manage/email_signup/fields` and compare data model doc
- Go to `/block/add?destination=/admin/structure/block/block-content` and test creating a new instance of the block type
- Test translating the block type

VOTE-775 create Email signup block type

---

composer.json
composer.lock
config/admin_toolbar.settings.yml
config/admin_toolbar_search.settings.yml
config/admin_toolbar_tools.settings.yml
config/core.entity_form_display.block_content.accordion_group.default.yml
config/core.entity_form_display.block_content.basic.default.yml
config/core.entity_form_display.block_content.email_signup.default.yml
config/core.entity_form_display.block_content.government_banner.default.yml
config/core.entity_form_display.block_content.registration_form_selector.default.yml
config/core.entity_form_display.block_content.registration_tool.default.yml
config/core.entity_form_display.block_content.search.default.yml
config/core.entity_form_display.block_content.sitewide_alert.default.yml
config/core.entity_form_display.node.landing.default.yml
config/core.entity_form_display.node.page.default.yml
config/core.entity_form_display.node.state_territory.default.yml
config/core.entity_view_display.node.page.default.yml
config/core.extension.yml
config/field.field.block_content.accordion_group.field_accordions.yml
config/workflows.workflow.publishing_content.yml
patches/README.md
patches/double_field/2091587-text_long-60_2.patch

https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-798
1. Install/Enable Field groups modules, entity form module, publication date module, and admin toolbar module
2. Update form display settings and field order for each content type to organize and group the fields in a logical way
3. Same as above for block types

Vote-798/improve-editor-experience

---

config/core.entity_form_display.node.landing.default.yml
config/core.entity_form_display.node.page.default.yml
config/core.entity_form_display.node.state_territory.default.yml
config/core.extension.yml
config/pathauto.pattern.page.yml
config/pathauto.pattern.state_territory.yml
config/pathauto.pattern.state_territory_es.yml
config/pathauto.settings.yml
web/modules/custom/vote_utility/README.md
web/modules/custom/vote_utility/inc/token.inc
web/modules/custom/vote_utility/vote_utility.info.yml
web/modules/custom/vote_utility/vote_utility.module

...Update form display for language field
https://bixal-projects.atlassian.net/browse/VOTE-805
Update path alias settings and behavior to match documentation
1. run `lando drush cim -y`
1. Create a new Content: Basic Page, Landing Page and State/Territory Page
2. Create a new Media: Audio, Document, Remote Video and Image
3. Confirm that the path aliases for each page matches the patterns described in the data model documentation

VOTE-805 Add and enable custom token path

---

config/core.entity_form_display.node.landing.default.yml
config/field.field.node.landing.body.yml

[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-867)
Update landing page form display following guidance in the ticket.
1. run `lando drush cim`
1. Go to the new Landing page form
2. The Content field should be labeled "Page description"
3. It should also be ordered above the Page components field

VOTE-867 update landing page form display

---

composer.json
composer.lock
config/core.extension.yml
config/s3fs.settings.yml

Install S3fs module for static storage in cloud.gov
1. run `drush cim -y`

Install S3fs module

---

web/themes/custom/vote_gov/templates/bx/bx-media.html.twig
web/themes/custom/vote_gov/templates/bx/bx-tabs-item.html.twig
web/themes/custom/vote_gov/templates/bx/bx-tabs.html.twig
web/themes/custom/vote_gov/templates/bx/bx-title.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-accordion--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-accordion-item--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-card--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-card-item--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-collection--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-hero--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-media--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-process-list--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-process-list-item--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-site-alert--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-summary-box--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-tabs--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-tabs-item--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--bx-title--default.html.twig
web/themes/custom/vote_gov/templates/paragraph/paragraph--default.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-accordion-item.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-accordion.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-card-item.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-card.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-collection.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-hero.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-process-list-item.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-process-list.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-site-alert.html.twig
web/themes/custom/vote_gov/templates/uswds/usa-summary-box.html.twig

https://bixal-projects.atlassian.net/browse/VOTE-879
Updating paragraph component templates to extend abstract component templates
No deployment steps or testing is necessary, these templates are not currently in use.

VOTE-879 decouple component templates

---

config/core.date_format.long_date.yml
config/core.entity_form_display.node.state_territory.default.yml
config/core.entity_view_display.block_content.accordion_group.default.yml
config/core.entity_view_display.block_content.basic.default.yml
config/core.entity_view_display.block_content.registration_form_selector.default.yml
config/core.entity_view_display.block_content.registration_tool.default.yml
config/core.entity_view_display.node.landing.default.yml
config/core.entity_view_display.node.state_territory.default.yml
config/core.entity_view_display.node.state_territory.teaser.yml
config/field.field.node.state_territory.field_state_name.yml
config/field.storage.node.field_state_name.yml
web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig

Insert Jira ticket link
[Jira ticket](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-747)
Add the components to the main region of the page for landing page, basic pages, and state/territory pages.
1. Run lando retune on this branch
2. Create new content for a landing page or select the one already created. Check that all content expected between the header and footer is displayed correctly in the main section of the page.
3. Repeat steps for basic pages and State/territory page.

VOTE-747: Configure template layout/hierarchy

---

web/themes/custom/vote_gov/src/sass/_uswds-theme.scss

https://bixal-projects.atlassian.net/browse/VOTE-973
Reset uswds theme override settings to defaults.
1. `cd` into the theme directory and run `npm run build` and make sure there are no errors
No tests yet as we haven't merged in styling work

VOTE-973 reset uswds theme overrides

---

.circleci/config.yml

VOTE-874: CI/CD for php-lint, theme building, and deployments.

---

.circleci/config.yml
web/sites/default/settings.cloudgov.php

Tweaks to `phpcs` for Drupal standards & `settings.cloudgov.php` edits to pass lint test.

VOTE-874: PHPCS tweaks 

---

.circleci/config.yml

Alpine doesn't use Bash as a default shell, so I had to change the logic to run with /bin/sh.

[VOTE-874]: Fix commands to work in /bin/sh

---

.circleci/config.yml

sh wasn't liking the regex. Doing it "the long way".

[VOTE-874]: Change if statement

---

.circleci/config.yml

Had pushing commented out for testing. Fixed.

[VOTE-874]: Uncomment push

---

scripts/bootstrap.sh

[VOTE-874] Fix type in bootstrap

---

.circleci/config.yml
manifest.yml

[VOTE-1024](https://bixal-projects.atlassian.net/browse/VOTE-1024)
Merge test pipeline code into dev.

VOTE-1024: Create Test environment.

---

.circleci/config.yml
manifest.yml

Only move the `dist` folder during the node build to the deployment workspace.

VOTE-874: Initial Pipeline

---

web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/templates/block/block-content--government-banner.html.twig
web/themes/custom/vote_gov/templates/block/block-content--search.html.twig
web/themes/custom/vote_gov/templates/form/input--submit--search-block-submit.html.twig
web/themes/custom/vote_gov/templates/form/input--submit--search-form-page.html.twig
web/themes/custom/vote_gov/templates/misc/feed-icon.html.twig
web/themes/custom/vote_gov/templates/navigation/pager.html.twig
web/themes/custom/vote_gov/templates/node/node--uswds-collection.html.twig
web/themes/custom/vote_gov/templates/partial/footer-contact.html.twig

https://bixal-projects.atlassian.net/browse/VOTE-1039
Fix theme path in templates
1. Visit http://vote-gov.lndo.site/user and make sure that the images in the header and footer are not broken.

VOTE-1039 Fix theme path in templates

---

config/block.block.vote_gov_content.yml
config/block.block.vote_gov_page_title.yml
web/themes/custom/vote_gov/templates/layout/page.html.twig
web/themes/custom/vote_gov/templates/node/node--page--full.html.twig
web/themes/custom/vote_gov/vote_gov.info.yml

https://bixal-projects.atlassian.net/browse/VOTE-896
Configure default template

VOTE-896 config default page layout template

---

composer.json
composer.lock
config/core.entity_form_display.node.page.default.yml
config/core.entity_view_display.node.page.default.yml
config/core.entity_view_display.node.page.full.yml
config/core.entity_view_display.node.page.teaser.yml
config/core.extension.yml
config/editor.editor.simple_html.yml
config/field.field.node.page.body.yml
config/field.field.node.page.field_body.yml
config/field.field.node.state_territory.body.yml
config/field.storage.node.field_body.yml
config/filter.format.simple_html.yml
config/user.role.authenticated.yml

https://bixal-projects.atlassian.net/browse/VOTE-863
Data model revisions for Basic Page content type.
1. Go to `http://vote-gov.lndo.site/node/add/page` and see the new fields.

VOTE-863 Basic Page data model revisions

---

testing/cypress/e2e/tests/footer-id-function.cy.js
testing/cypress/e2e/tests/footer-menu-function.cy.js

https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-928&assignee=611272e0eb7aef00694b8a97
This Pr will add tests for the footer id part of the site... this will check the ability to add a link and that it is present and then check the access for each role as well.
1. pull done branch 
4. run `npm run cy:open`
5. select the `footer-id.cy.js` test and verify that test is working

Vote-928 Footer Id Function Test

---

composer.lock

[VOTE-1032](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1032&assignee=609161faf6c0960069bf61b3)
[VOTE-1030](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1030&assignee=609161faf6c0960069bf61b3)
Updates simple sitemap module and twig tweak module.

VOTE-1030: update twig tweak and simple sitemap

---

.circleci/config.yml
scripts/pipeline/build-theme.sh
scripts/pipeline/cloud-gov-login.sh
scripts/pipeline/cloud-gov-remote-cmd.sh
scripts/pipeline/composer-install.sh
scripts/pipeline/deb-basic-deps.sh
scripts/pipeline/deb-cf-install.sh
scripts/pipeline/deb-mysql-client-install.sh
scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh
scripts/pipeline/phpcs-install.sh

[VOTE-741](https://bixal-projects.atlassian.net/browse/VOTE-741)

VOTE-741: Setup Prod Env

---

web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/vote_gov/templates/partial/homepage-link.html.twig

[Insert Jira ticket link](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1069&assignee=609161faf6c0960069bf61b3)
This PR updates "Go Back" link to work with translations and adds the translation string for each langauge.
1. Pull branch
2. Import database
3. Run lando retune
1. Open English homepage
2. Check that "Go back" string is in the correct language
3. Open Spanish homepage
4. Check that "Go back" string is in the correct language

VOTE-1069: translate "go back" link

---

config/system.site.yml

https://bixal-projects.atlassian.net/browse/VOTE-1148
Set homepage and 404 page in settings
1. run `lando drush cim -y`
1. Go to http://vote-gov.lndo.site/ and make sure the homepage displays
2. Go to http://vote-gov.lndo.site/oops and make sure the 404 page displays

VOTE-1148 set homepage and 404 settings

---

.github/dependabot.yml

Initalize dependabot settings file for scans of dependencies

Initialize dependabot.yml

---

web/sites/default/settings.cloudgov.php

[VOTE-1078](https://bixal-projects.atlassian.net/browse/VOTE-1078)
Add apps.internal URL's to the trusted hosts variable.

[VOTE-1078] Add internal routes to trusted hosts.

---

testing/cypress.config.js
testing/cypress/e2e/tests/footer-menu-function.cy.js
testing/cypress/e2e/tests/site-wide-banner-access.cy.js
testing/cypress/support/commands.js

[Vote-943](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-943&assignee=611272e0eb7aef00694b8a97)
This Pr will add test coverage for the sitewide banner... this will check the access for each role and their ability to add the banner along with deleting it as well.
1. Pull down branch
2. start local
4. run `npm run cy:open`
5. run all tests in `backend` to create users 
6. select `sitewide-banner-access.cy.js` test and verify that the test is passing

Vote-943 -> site wide banner test

---

composer.json
composer.lock
config/autologout.role.content_editor.yml
config/autologout.role.content_manager.yml
config/autologout.role.site_admin.yml
config/autologout.settings.yml
config/core.extension.yml

[VOTE-1008](https://bixal-projects.atlassian.net/browse/VOTE-1008)
Enable and Configure Autologout module
1. Go to Autologout's config page and confirm 1800 seconds for autologout settings.

VOTE-1008: Enable and Configure Autologout

---

testing/cypress/e2e/externalLinks/english-external-links-validator.cy.js
testing/cypress/e2e/internalLinks/english-internal-links-validator.cy.js

[Vote-1043](https://bixal-projects.atlassian.net/browse/VOTE-1043)
This PR will update the link validator tests to check the now present links on the site. This will continue to be built our more as the migration continues 
1. Pull down the branch 
2. run `lando rebuild -y`
4. in the root run `lando cy:links` and `lando cy:proofer` and verify that both tests are passing

Vote-1043 -> Link Validator Test Update 

---

.lando.yml
testing/package-lock.json
testing/package.json

[Vote-1181](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1181&assignee=611272e0eb7aef00694b8a97)
This Pr will update Cypress-axe and Cypress Core... The dependabot flagged for 12.8.1 but 12.9.0 has been released and updated to that to be ahead of the next check. 
this will close out [Pr-105](https://github.com/usagov/vote-gov-drupal/pull/105) and [Pr-107](https://github.com/usagov/vote-gov-drupal/pull/107)
link to [Cypress Changelog](https://docs.cypress.io/guides/references/changelog)
1. Pull done branch 
2. `lando start`
3. `lando rebuild -y`
4. in the root run `lando cy:testSuite` this will run all tests and verify that tests are passing 
5. can also cd into `testing` …

Vote-1181 -> Dependabot updates 

---

web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-header.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-search.scss

https://bixal-projects.atlassian.net/browse/VOTE-1056
Override default sizing styles for the search text box
###Pre-deploy steps
1. You might have to recompile the styles
cd web/themes/custom/vote_gov
npm run build
1. Run lando retune
1. Verify the search text box sizing matches the original site
a. Desktop
b. Tablet
c. Mobile

VOTE-1056 Fix the responsive sizing of the search box

---

web/modules/custom/vote_utility/translations/nv.po

[VOTE-1175](https://bixal-projects.atlassian.net/browse/VOTE-1175)
Adds navajo translation for accessibility phrases

VOTE-1175: Accessibility phrases - Navajo

---

.circleci/config.yml

[Vote-1240](https://bixal-projects.atlassian.net/browse/VOTE-1240)
This Pr Will remove the backend script for Cyrpess that is no longer needed 

Vote-1240 -> remove back end script 

---

config/language.entity.ypk.yml

[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-1296)
Change Yup'ik language label to include dialect
1. Verify language name is updated on the language drop-down
2. You may need to switch the page to a few other languages and view the dropdown again

VOTE-1296 Add dialect to Yup'ik name label

---

docs/README.md

https://bixal-projects.atlassian.net/browse/VOTE-1018

VOTE-1018 update env names in docs

---

composer.json
composer.lock
config/core.extension.yml
config/google_tag.settings.yml
config/language.entity.ypk.yml
config/log_stdout.settings.yml
patches/log_stdout/3339853-3.patch
scripts/cronish.sh
web/themes/custom/vote_gov/templates/block/block--system-menu-block--footer.html.twig
web/themes/custom/vote_gov/vote_gov.libraries.yml

Adds --uri flag to cron script command to test sitemap defaults

VOTE-1205: investigate sitemap default behavior

---

testing/cypress/e2e/tests/homepage-accordion.cy.js

[Vote-926](https://bixal-projects.atlassian.net/browse/VOTE-9260
This Pr will add testing coverage for the homepage accordion component 
1. pull down the branch 
4. run `npm run cy:createUser`
5. run `npm run cy:open`
6. then run the `homepage-accordion.cy.js` test and verify that test is passing 
7. return to terminal and run `npm run cy:deleteUser`

Vote-926 -> Homepage Accordion Component 

---

testing/package-lock.json
testing/package.json

[Vote-1339](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1339&assignee=611272e0eb7aef00694b8a97)
This PR will close you the following dependabot PRs
https://github.com/usagov/vote-gov-drupal/pull/151
https://github.com/usagov/vote-gov-drupal/pull/152
4. run `npm install`
5. run `npm run cy:test` and `npm run cy:axe` and verify that tests are still passing

Vote-1339 -> dependabot updates 

---

composer.lock
web/sites/default/default.settings.php

Insert Jira ticket link
updating snyk finding 
1. check runs below and verify that tests are passing

update from snyk

---

testing/cypress/e2e/tests/upload-media.cy.js

[Vote-982](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-982&assignee=611272e0eb7aef00694b8a97)
This PR will add test coverage to check role access to uploading media as well as deleting 
2. start local
4. in terminal run `npm run cy:createUser`
5. then run `npm run cy:open`
6. select `upload-media.cy.js` verify that test is passing 
7. after test runs return back to terminal and run `npm run cy:delteUser`

Vote - 982 -> test media upload 

---

composer.json
composer.lock

https://bixal-projects.atlassian.net/browse/VOTE-1192
Patch publication_date module to fix deprecated function error
1. Visit http://vote-gov.lndo.site/node/add/page
2. Make sure there is no error displaying

VOTE-1192 Patch publication date module to fix deprecated function

---

docs/testing.md
testing/README.md
testing/docs/gettingStarted.md

[Vote-1338](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1338&assignee=611272e0eb7aef00694b8a97)
This PR will add testing documentation to the project 
1. Review files changed and ensure the information that is presented is relevant and current
2. click though links and ensure they are taking you to the correct place

added testing documentation to both the doc folder and testing folder

---

composer.json
composer.lock
config/core.extension.yml
config/new_relic_rpm.settings.yml

https://bixal-projects.atlassian.net/browse/VOTE-1055
Install and Enable New Relic RPM module
1. visit http://vote-gov.lndo.site/admin/config/development/new-relic
2. Confirm you now have a admin interface page for New Relic settings

VOTE-1055 install and enable New Relic RPM module

---

web/themes/custom/vote_gov/templates/field/field--node--field-body--page.html.twig
web/themes/custom/vote_gov/templates/node/node--page--full.html.twig

https://bixal-projects.atlassian.net/browse/VOTE-1140
Updated the field template for the basic page type so that the styling is consistent.
1. Compare the basic pages to ensure styling is consistent.
a. About Us
b. Slick sheet (promoting-access-to-voting)
c. 404 page

VOTE-1144 Apply usa prose class to basic page fields

---

testing/package-lock.json
testing/package.json

Insert Jira ticket link
This PR will update Cypess and the Reports from Depanabot.  This will close out https://github.com/usagov/vote-gov-drupal/pull/160 and https://github.com/usagov/vote-gov-drupal/pull/164
4. run `npm run testSuite` and verify that all tests pass and report is generated

Update Cypress from Dependabot

---

config/views.view.registration_tool_list.yml
web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/src/js/registration-tool.js
web/themes/custom/vote_gov/templates/paragraph/paragraph--registration-tool.html.twig
web/themes/custom/vote_gov/vote_gov.libraries.yml

[VOTE-1087](https://bixal-projects.atlassian.net/browse/VOTE-1087)
1. run lando retune
1. Use registration tool on the homepage to navigate to a state page

VOTE-1087: attach js to registration tool

---

testing/cypress/e2e/tests/user-content-access.cy.js
testing/cypress/support/commands.js
testing/cypress/support/e2e.js
testing/package-lock.json
testing/package.json

[vote-919](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-919&assignee=611272e0eb7aef00694b8a97)
[vote-918](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-918&assignee=611272e0eb7aef00694b8a97)
This PR will add test coverage for both Site admin and content Manager rolls access.  This will go through creating pages, checking if they can view drafts can move things out of draft etc. 
4. run `npm run cy:createUser`
5. run `npm run cy:open` and select the `user-content-access.cy.js` file and verify that test is passing 
6. once the test is complete be sure …

Testing Role Access to Content

---

scripts/cronish

[VOTE-1418](https://bixal-projects.atlassian.net/browse/VOTE-1418)
Update URI endpoint.

VOTE-1418: Update uri value in cron command

---

.circleci/config.yml

[VOTE-1438](https://bixal-projects.atlassian.net/browse/VOTE-1438)
Temporarily disabling Cypress while we work on CircleCI access through the WAF

Disable cypress from workflow on TEST

---

.circleci/config.yml

[Vote-1438](https://bixal-projects.atlassian.net/browse/VOTE-1438)
This Pr will remove Cypress test from the CircleCi workflow until the error can be addressed 
1. view file changes and verify that all cypress related steps are commented out

Vote-1438 Remove Cypress from CircleCi

---

composer.json
composer.lock
config/core.extension.yml
config/disable_language.settings.yml
config/language.entity.nv.yml

https://bixal-projects.atlassian.net/browse/VOTE-1176
Install and configure disable language module. Disable Navajo as a proof.
1. Log out and visit http://vote-gov.lndo.site/nv
2. Confirm that you are redirected to homepage in English

VOTE-1176 Disable Navajo translation

---

scripts/pipeline/cloud-gov-deploy.sh

[VOTE-1415](https://bixal-projects.atlassian.net/browse/VOTE-1514)
Fixes hardcoded `dev` to the branch variable.

VOTE-1514: Fix deploy script

---

web/themes/custom/vote_gov/src/sass/pages/homepage.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-accordion.scss

During visual regression testing we identified some dispcrepancies from Hugo to Drupal for the homepage. This PR resolves them.
1. cd `web/themes/custom/vote_gov`
2. run `npm run build`
1. visit https://vote-gov.lndo.site and compare against the live site https://vote.gov

BUG: Fix visual regression layout issue on homepage

---

web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig
web/themes/custom/vote_gov/templates/node/node.html.twig
web/themes/custom/vote_gov/templates/partial/homepage-link.html.twig

[Vote-1537](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1537&assignee=611272e0eb7aef00694b8a97)
This Pr will update the page templates in order to fix a bug with the go-back button location 
3. visit `http://vote-gov.lndo.site/register/ak` and `https://vote.gov/register/ak/` and verify that the location of the `go back` button are both in the same location 
> ** NOTE **
> please visit ticket for reference

updated templates to fix issue with go back button

---

scripts/build_static
scripts/pipeline/cloud-gov-deploy.sh

[VOTE-1560](https://bixal-projects.atlassian.net/browse/VOTE-1560)
Updating pipeline for new domain names, along with some other bug fixes.

Vote-1560: Update Tome URI to new domain names

---

testing/cypress/e2e/tests/user-content-access.cy.js

[Vote-926](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-916&assignee=611272e0eb7aef00694b8a97)
This Pr will add testing to check an anonymous users access to content moderation access 
1. Pull branch 
3. CD into `testing`
4. First run `npm run cy:createUser` 
5. Second run `npm run cy:open` and run the `user-content`access.cy.js` test and verify that all are passing 
6. after test running return back to your terminal in the `testing` folder and run `npm run cy:deleteUser`

Vote-916 -> anonymous user content access

---

web/themes/custom/vote_gov/gulpfile.js
web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-1178)
Replace uglify-es with superseder uglify-js
1. Inside theme directory run "npm run build"
2. Confirm no errors and dist directory builds as expected
3. Confirm site styling looks the same

VOTE-1178: replace uglify dependency

---

manifest.yml
scripts/bootstrap.sh
scripts/pipeline/cloud-gov-deploy.sh
scripts/post-deploy

[VOTE-1578](https://bixal-projects.atlassian.net/browse/VOTE-1578)
Ensures that post deploy is ran first, before the static site is generated.

VOTE-1578: Make sure static site is built after post deploy is ran

---

scripts/bootstrap.sh

[VOTE-966](https://bixal-projects.atlassian.net/browse/VOTE-966)

VOTE-966: write out certificate files.

---

testing/package-lock.json
testing/package.json

[Vote-1532](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1532&assignee=611272e0eb7aef00694b8a97)
This Pr will update cypress from dependabot updates 
Will close the follow PRs:
https://github.com/usagov/vote-gov-drupal/pull/226
https://github.com/usagov/vote-gov-drupal/pull/225
https://github.com/usagov/vote-gov-drupal/pull/206
https://github.com/usagov/vote-gov-drupal/pull/205
> **NOTE**
> There will be some fails that will happen. I have will be creating a ticket to check in to the issues further
1. Pull down the branch 
4. run `npm install`
5. run the following commands: `npm run cy:test`, `npm run cy:proofer`, `npm run cy:links`, …

Vote-1532 -> Cypress Dependabot updates

---

config/language.entity.ht.yml
config/language.negotiation.yml
config/language/ht/language.entity.ht.yml
config/language/ht/metatag.metatag_defaults.front.yml
config/language/ht/metatag.metatag_defaults.global.yml
config/language/ht/metatag.metatag_defaults.node__landing.yml
config/language/ht/metatag.metatag_defaults.node__state_territory.yml
web/modules/custom/vote_utility/translations/ht.po

[Insert Jira ticket link
](https://bixal-projects.atlassian.net/browse/VOTE-1488)
Migrate Haitian Creole (ht) language configuration and data
1. Confirm Haitian Creole shows up as a disabled language in the admin panel
2. Confirm metadata configuration is set
3. Confirm the language inherits the date format of English

VOTE-1488 Haitian Creole

---

testing/cypress/e2e/tests/state-pages.cy.js
web/themes/custom/vote_gov/templates/block/block-content--registration-form-selector--full.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--in-person.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig

[Vote-981](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?selectedIssue=VOTE-981&assignee=611272e0eb7aef00694b8a97)
This PR will add testing for state pages and verify that the state pages have the correct registration deadline 
2. Start local 
3. cd into `testing` folder 
4. run `npm run cy:open`
5. select the `state-pages.cy.js` test and verify that it is passing

Vote-981 -> Test for State Pages 

---

web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/templates/navigation/links--language-block.html.twig

[Vote-1539](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1539&assignee=611272e0eb7aef00694b8a97&assignee=61f17e9a138863006aad19c1)
This Pr will fix the Bug with the Navajo font turning `(`, `)` and `-` into characters 
1. Pull down Branch 
2. Start local 
3. visit the homepage
4. Check that every language in the language switcher has parenthesis around the language name and then click on `Navajo` and check that the parenthesis are now `<` and `>` also verify that the `-` between the Chinese names are removed as well on `Navajo`

Vote-1539 -> Navajo Parenthesis Bug

---

.circleci/config.yml
.gitignore
scripts/download_latest_backup.sh
scripts/pipeline/composer-install.sh
scripts/pipeline/deb-awscli.sh
scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh
scripts/pipeline/scheduled_backup.sh

[VOTE-1009](https://bixal-projects.atlassian.net/browse/VOTE-1009)
Script for hourly backups ups for:
- User uploads
- Drupal Database
- Terraform state files
Script for downloading the latest copy of the above backups.

VOTE-1009: backup and backup download scripts.

---

web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

[VOTE-1627](https://bixal-projects.atlassian.net/browse/VOTE-1627)
Update uswds version to 3.5.0 with no breaking changes
1. Check pages for visual regression issues

VOTE-1627: update USWDS to 3.5.0

---

testing/cypress/e2e/tests/basic-page.cy.js

[Vote-980](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-980&assignee=611272e0eb7aef00694b8a97)
This Pr will add test coverage for basic page on durpal site
4. run `npm run cy:createUser`
5. run `npm run cy:open`
6. select `basic-page.cy.js` and verify that test is passing 
7. return back to terminal and stop the cypress running with `control+c`
8. run `npm run cy:deleteUser`

Vote-980 -> test for basic page

---

web/themes/custom/vote_gov/img/ballot_box-blue.svg
web/themes/custom/vote_gov/templates/block/block-content--government-banner.html.twig

[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-1410)
1. Verify blue ballot box displays correctly inline
2. Verify the functionality of aria-labelledby

VOTE 1410 Change aria-label to aria-labelledby

---

docs/devops.md
scripts/entrypoint
scripts/start

[VOTE-1682](https://bixal-projects.atlassian.net/browse/VOTE-1682)
Fix for some entrypoint scripts.

VOTE-1682: General DevOps Documenation.

---

docs/README.md

[VOTE-1641](https://bixal-projects.atlassian.net/browse/VOTE-1641)
Add domains to the README docs.

VOTE-1641 Add domains to readme

---

testing/package-lock.json
testing/package.json

[Vote-15](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-15)
This pr will update cyrpess from dependabot PRS
Closes out: https://github.com/usagov/vote-gov-drupal/pull/257 and https://github.com/usagov/vote-gov-drupal/pull/257
1. pull done branch 
4. run `npm run cy:open` and check that cypress running is opening and tests are passing

Vote-15 -> Cypress dependabot updates 

---

manifest.yml
scripts/pipeline/exports.sh

[VOTE-1673](https://bixal-projects.atlassian.net/browse/VOTE-1673)
Add SSO certificates to environments.

VOTE-1673: SSO certificate exports.

---

docs/devops.md
web/modules/custom/vote_migrate/config/install/migrate_plus.migration.state_territory.yml
web/modules/custom/vote_migrate/config/install/migrate_plus.migration.state_territory_translations.yml
web/modules/custom/vote_migrate/config/install/migrate_plus.migration_group.nodes__state_territory.yml
web/modules/custom/vote_migrate/vote_migrate.install
web/modules/custom/vote_utility/translations/nv.po
web/themes/custom/vote_gov/templates/block/block-content--email-signup--full.html.twig
web/themes/custom/vote_gov/templates/block/block-content--registration-form-selector--full.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--in-person.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--not-needed.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig

https://cm-jira.usa.gov/browse/VOTE-14
These code changes represent the final work in Sprint 37

Sprint 37 release candidate to STAGE

---

.circleci/config.yml

Insert Jira ticket link
[Vote-1743](https://bixal-projects.atlassian.net/browse/VOTE-1743)
This PR will update to have the pipeline run just on the test branch
1. Verify that only test is listed under `branches: only` in .yml file

updated the pipeline config to just run on test

---

testing/package-lock.json
testing/package.json

[Vote-21](https://cm-jira.usa.gov/browse/VOTE-27)
This Pr will update cypress and cypress real events
closes out: https://github.com/usagov/vote-gov-drupal/pull/287 and https://github.com/usagov/vote-gov-drupal/pull/287
1. run `lando drush pm-uninstall usagov_login` to ensure that backend test will run
2. cd into `testing`
3. run `npm install`
4. run `npm run cy:fullTests` (this will fun both frontend and backend tests)
5. run `npm run cy:open` and check that runner is opening and you can run a few tests in the runner

Vote-21 -> Cypress dependabot updates 

---

scripts/pipeline/downsync-backup.sh

[VOTE-1759](https://bixal-projects.atlassian.net/browse/VOTE-1759)
Remove `drush cr` from downsync-backup script and replace it with ignoring database tables without meaningful data.
1. Allow downsync-backup pipeline to run
2. Test backup database dump created

VOTE-1759: Troubleshoot scheduled backup pipeline failures

---

web/themes/custom/vote_gov/templates/block/block--languageswitcher-2.html.twig
web/themes/custom/vote_gov/templates/block/block--languageswitcher.html.twig

[Insert Jira ticket link
](https://bixal-projects.atlassian.net/browse/VOTE-1412)
Change language switcher block markup to use divs so that the dropdown makes more sense for screen readers
1. Test language switcher to ensure functionality remains the same.

Bug/vote 1412/lang switcher jaws fix

---

.github/pull_request_template.md
config/block.block.loginalert.yml
config/language.entity.ar.yml
config/language.entity.ht.yml
config/language.entity.pt.yml
config/language.entity.ru.yml

Enhance the pull request template

Enable new languages and capture login block config

---

scripts/build_static

[VOTE-1575](https://bixal-projects.atlassian.net/browse/VOTE-1575)
Update the build_static script to export additional files and paths needed to produce the Simple Sitemap sitemap files/urls.
1. None
1. Await the build_static workflow to execute.
1. Once the build_static workflow has completed, visit /sitemap.xml to confirm that the sitemap renders and functions.

VOTE-1575 Update build_static script to support sitemap.xml

---

web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss
web/themes/custom/vote_gov/templates/navigation/links--language-block.html.twig

[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-194)
Update language switcher styling
1. Compare language switcher to [figma designs](https://www.figma.com/file/udbj72Ixi9akwke1nPI1jF/NVRF-Design?type=design&node-id=356-3082&mode=design&t=Y27jDYedBdjNF264-0) for accuracy on all screen sizes
note some changes that were made from the design:
- No "x" button in mobile menu, it closes with the "select language" button toggle or by clicking outside of it
- Did not implement "Select your language preference" because we don't have translations
- Did not implement custom scroll bar, on mobile scrolling still works and we've made the language list fixed so it can scroll without the whole page …

VOTE-194: language switcher style updates

---

.circleci/config.yml
.github/pull_request_template.md

[Vote-1243](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/266?modal=detail&selectedIssue=VOTE-1233&assignee=611272e0eb7aef00694b8a97)
This PR will update the config.yml file to help the cypress test run on the static build frontend 
N/A
N/A
1. review files and ensure that there are no issues with the modifications that were made

Vote-1243 -> update pipeline for cypress test

---

config/sync/metatag.metatag_defaults.global.yml

[Vote-1833](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1833&assignee=611272e0eb7aef00694b8a97)
This PR will update the config for the favicon to remove `[site:URL]` from the paths 
**Note**
> This Pr will take over for https://github.com/usagov/vote-gov-drupal/pull/323 and help keep git history clean and will now only have the correct file change that is needed 
3. run `lando retune` 
4. visit the following state pages and make sure there are no favicon errors in the console `Arkansas`, `American Somoa`, `Alaska`, `North Dakota`, and `Wyoming`

Vote-1833 -> Favicon path update

---

.circleci/config.yml
scripts/pipeline/exports.sh

VOTE-1756
Add pipeline variable and associated update to the `drush-cron-workflow` to have cron run with the environment's URI specified.
1. Allow the drush-cron-workflow scheduled job to run for this environment following the deploy
2. Look at the cf task number created in the pipeline for this drush-cron-workflow
3. cf tasks <application name> | grep <task id> and verify the command includes the correct URI for drush cron

VOTE-1756: Sitemap.xml generation in CMS doesn't recognize the site url

---

.circleci/config.yml
testing/package.json

[Vote-1879](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1879&assignee=611272e0eb7aef00694b8a97)
This PR will update the config.yml to update our deploy workflow.  We have removed the deploy-test and the deploy-prod and now have 2 workflows with deploy jobs.  
Testing will be php-lint and snyk on every branch and then cypress will be tested on `dev`, `test`, and `stage`.
Have also added new scripts for links and axe to run in the pipeline to add full test coverage on PRs and work pushed into branches
1. N/A
1. Need to set up rules for PRs to have specific tests pass before the merge can happen -> php-lint and snyk must pass on all branches, cypress can fail on `dev` and `test` but must pass for `stage`
1. Review file changes …

Vote-1879 -> Pipeline/Deploy Workflow updated

---

testing/cypress/e2e/backEndTests/footer-menu-editor.cy.js

[Vote-79](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-79&quickFilter=23166)
Update to cypress backend test for post-sprint run, there was something with a submit button that Cypress was not getting the full element, the `force: true` helps override the error and continue with the function. 
n/a
n/a
4. run `npm run cy:backEnd` and ensure tests are passing

updated test post sprint

---

.circleci/config.yml
testing/package-lock.json
testing/package.json

[Vote-226](https://cm-jira.usa.gov/browse/VOTE-226)
This Pr will update from dependabot updates and will close out https://github.com/usagov/vote-gov-drupal/pull/345, https://github.com/usagov/vote-gov-drupal/pull/324 and https://github.com/usagov/vote-gov-drupal/pull/326
n/a
n/a
4. run `npm install`
5. run `npm run cy:fullTests` and make sure cypress function tests are passing, also run `npm run cy:open` and make sure the runner is opening as expected as well

Vote-226 -> Dependabot Updates 

---

config/sync/language/fr/metatag.metatag_defaults.global.yml
web/modules/custom/vote_migrate/config/install/migrate_plus.migration.state_territory_translations.yml

[VOTE-73](https://cm-jira.usa.gov/browse/VOTE-73)
Update vote_migration module to include the content translation imports for French.
None
None
_(The following process can now be done from the admin migration page, /admin/structure/migrate/manage/nodes__state_territory/migrations)_
1. Enable the vote_migrate module via Drush `drush en vote_migrate`. 
3. Confirm the current migration status using `drush ms`. You should see that there are Unprocessed imports for state_territory_translations.
-- Confirm that there aren't any errors displayed in red if using the command line indicating 403 errors. This will confirm that the new install file works as expected.
5. Run the migration using `drush mim --group=nodes__state_territory`.
6. Run `drush ms` again to confirm that there aren't any more …

VOTE-73: Add French to migration script.

---

docs/backend.md

https://cm-jira.usa.gov/browse/VOTE-231
Add module documentation to backend documentation.

VOTE-231 Add Drupal module documentation to the codebase

---

config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.full.yml
config/sync/core.entity_view_display.node.state_territory.teaser.yml
config/sync/field.field.node.state_territory.field_address_location_inst.yml
config/sync/field.field.node.state_territory.field_identification_inst.yml
config/sync/field.field.node.state_territory.field_mailing_address_inst.yml
config/sync/field.field.node.state_territory.field_nvrf_last_updated_date.yml
config/sync/field.field.node.state_territory.field_online_voter_reg_desc.yml
config/sync/field.field.node.state_territory.field_personal_information_inst.yml
config/sync/field.field.node.state_territory.field_political_party_inst.yml
config/sync/field.field.node.state_territory.field_reg_eligibility_desc.yml
config/sync/field.storage.node.field_address_location_inst.yml
config/sync/field.storage.node.field_identification_inst.yml
config/sync/field.storage.node.field_mailing_address_inst.yml
config/sync/field.storage.node.field_nvrf_last_updated_date.yml
config/sync/field.storage.node.field_online_voter_reg_desc.yml
config/sync/field.storage.node.field_personal_information_inst.yml
config/sync/field.storage.node.field_political_party_inst.yml
config/sync/field.storage.node.field_reg_eligibility_desc.yml

[VOTE-84](https://cm-jira.usa.gov/browse/VOTE-84)
Add additional fields to State/Territory content type.
none
1. Run `lando drush cim` locally to import the content type changes.
1. Login as an admin.
2. Create or edit a State/Territory content item.
3. Confirm that the new fields are available per the requirements document:
https://docs.google.com/spreadsheets/d/1Z8j-a9KLrDlyG4kGqXmfwENlidtXTLYE/edit#gid=1000964088
4. Confirm that the fields which are marked as translatable are available when editing a translated content item.

VOTE-84: Add additional fields to state/territory content type.

---

.circleci/config.yml
testing/package.json

[Vote-238](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-238&quickFilter=23166)
This PR will set up both external and internal links on a schedule to run on stage on Monday and Thursday at 9am est.  also sets up that if the first test fails the second one will still run but the pipeline will fail no matter what if any fails 
n/a
n/a
1. Review file changes to ensure that jobs were added correctly and there are there is now a set run for link validation to run on a con (schedule)

Vote-238 -> Set up links validation on schedule 

---

web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-accordion.scss

https://cm-jira.usa.gov/browse/VOTE-235
This change resolves an issue with Vietnamese displaying inconsistent weights when displaying accordions.
1. cd into theme and run build `npm run build`
1. visit http://vote-gov.lndo.site/vi
2. confirm that Vietnamese accordion character display with more consistent weights

VOTE-235 update accordion font weight

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/editor.editor.basic_html.yml
config/sync/filter.format.basic_html.yml
docs/backend.md
web/modules/custom/ec_touchpoints_survey/ec_touchpoints_survey.info.yml
web/modules/custom/ec_touchpoints_survey/ec_touchpoints_survey.module
web/modules/custom/ec_touchpoints_survey/src/Plugin/EmbeddedContent/TouchpointsSurvey.php
web/modules/custom/ec_touchpoints_survey/templates/embedded-content/touchpoints-survey.html.twig

https://cm-jira.usa.gov/browse/VOTE-106
Add the ability to embed a Touchpoints survey in a wysiwyg
1. Visit http://vote-gov.lndo.site/node/add/page
2. Add a page title then click on the new "Embedded Content" icon in the wysiwyg toolbar
3. Select "Touchpoints Survey"
4. Enter these values: 
- file name: `77e87d97.js`
- id `votegov-accessibility-survey`
5. save the page and confirm that you can see the embedded form on the page.

VOTE-106 Add the ability to embed a Touchpoints survey in a wysiwyg

---

web/themes/custom/vote_gov/src/sass/custom-components/footer-identifier.scss

https://cm-jira.usa.gov/browse/VOTE-17
Resolve display bug with touchpoints button on small desktop.
1. cd into the vote_gov directory and run `npm run build`
1. Visit http://vote-gov.lndo.site/
2. Reduce your browser width to small desktop or tablet size and make sure the touchpoints button is centered and full width.

VOTE-17 fix firefox display bug for touchpoints button on small desktop

---

config/sync/editor.editor.basic_html.yml
config/sync/filter.format.basic_html.yml

https://cm-jira.usa.gov/browse/VOTE-306
Update text format settings to allow new markup tags and attributes.
1. Visit http://vote-gov.lndo.site/node/5/edit and select Basic HTML text format for the WYSIWYG and save.
2. Confirm that the page displays correctly http://vote-gov.lndo.site/promoting-access-to-voting

VOTE-306 update basic text format rule to allow additional custom markup

---

web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

[Vote-303](https://cm-jira.usa.gov/browse/VOTE-303)
This PR will update USWDS from dependabot and will close out -> https://github.com/usagov/vote-gov-drupal/pull/361
n/a
n/a
1. cd into `vote_gov` theme in web folder 
2. run `npm install`
3. run `npm run build`
4. visit local and click around and ensure that site is still loading and not visual regression is present 
5. check console for any errors 
6. run `npm run cy:fullTests` and `npm run cy:axe` and ensure tests are passing

VOTE-303: USWDS dependabot updates

---

docs/testing.md

[Vote-267](https://cm-jira.usa.gov/browse/VOTE-267)
This PR will update the testing documentation in the repo with testing commands and a few other updates to the new testing flow
n/a
n/a
1. review doc and ensure it covers relevant steps and no major grammar issues

VOTE-267: Testing documentation  update

---

.github/pull_request_template.md
config/sync/core.entity_form_display.node.state_territory.default.yml

https://cm-jira.usa.gov/browse/VOTE-244
Move NVRF field into the field group
1. visit http://vote-gov.lndo.site/node/add/state_territory and check to make sure the "NVRF Fields" field should display in the NVRF tab.

VOTE-244 nvrf field placement

---

.github/pull_request_template.md
config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/editor.editor.basic_html.yml
config/sync/filter.format.basic_html.yml
docs/testing.md
scripts/pipeline/downsync-backup.sh
testing/package-lock.json
testing/package.json
web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json
web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/src/sass/drupal-system/form.scss
web/themes/custom/vote_gov/src/sass/pages/_index.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-alert.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-form.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss

Dev to test

---

.circleci/config.yml
.github/pull_request_template.md
config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/editor.editor.basic_html.yml
config/sync/filter.format.basic_html.yml
docs/testing.md
scripts/build_static
scripts/pipeline/downsync-backup.sh
scripts/pipeline/exports.sh
testing/package-lock.json
testing/package.json
web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json
web/themes/custom/vote_gov/php-includes/preprocess.inc
web/themes/custom/vote_gov/src/sass/drupal-system/form.scss
web/themes/custom/vote_gov/src/sass/pages/_index.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-alert.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-form.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss
web/themes/custom/vote_gov/templates/field/double-field-item--field-in-person-deadline.html.twig
web/themes/custom/vote_gov/templates/field/double-field-item--field-online-deadline.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--in-person.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig

https://cm-jira.usa.gov/browse/VOTE-360
Sprint 42 release candidate
1. Visit `/node/5/edit` and set the text format to basic HTML
2. Do this for both English and Spanish and confirm the content is displaying on the frontend

Sprint 42: release candidate to STAGE

---

composer.lock

([VOTE-325](https://cm-jira.usa.gov/browse/VOTE-325))
Update Drupal Core to latest version 10.1.4
None
1. run `lando rebuild`
2. then `lando retune` to run composer install.
1. Login as an admin and confirm that the Drupal version is 10.1.4 when viewing the admin status page.
2. Click through site and confirm that site is still functional.

VOTE-325: Update drupal core to 10.1.4

---

testing/package-lock.json
testing/package.json
web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

[Vote-387](https://cm-jira.usa.gov/browse/VOTE-378)
This PR will update dependabot findings
closes out PRs: https://github.com/usagov/vote-gov-drupal/pull/396, https://github.com/usagov/vote-gov-drupal/pull/401, https://github.com/usagov/vote-gov-drupal/pull/400
N/A
N/A
1. pull down branch and start local 
2. run `npm run cy:axe`, `npm run cy:fullTests`, `npm run cy:open` and ensure no errors are flagged

CMS Dependabot update - Sprint 43

---

composer.lock
testing/package-lock.json
testing/package.json
web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

https://cm-jira.usa.gov/browse/VOTE-379
Sprint 43 release candidate

Sprint 43: release candidate to STAGE

---

config/sync/language.entity.nv.yml
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/ypk.po

VOTE-261 Add Navajo string translation updates
https://cm-jira.usa.gov/browse/VOTE-259
https://cm-jira.usa.gov/browse/VOTE-261
Adding missing or updated string translations for Yupik and Navajo translations.
Enable Navajo translation.
1. See steps and screenshots in JIRA ticket.

VOTE-259 Add Yupik string translation updates

---

config/sync/block_content.type.nvrf_a_b_message.yml
config/sync/core.entity_form_display.block_content.nvrf_a_b_message.default.yml
config/sync/core.entity_view_display.block_content.nvrf_a_b_message.default.yml
config/sync/field.field.block_content.nvrf_a_b_message.body.yml
config/sync/language.content_settings.block_content.nvrf_a_b_message.yml
config/sync/user.role.content_manager.yml

https://cm-jira.usa.gov/browse/VOTE-401
Add NVRF A/B Message block type
1. Visit http://vote-gov.lndo.site/block/add/nvrf_a_b_message
2. Create a new AB message

VOTE-401 Add NVRF A/B Message block type

---

testing/package-lock.json
testing/package.json

[Vote-465](https://cm-jira.usa.gov/browse/VOTE-465)
This PR will update Cypress and 2 plugins from dependabot. 
Closes out - https://github.com/usagov/vote-gov-drupal/pull/426, https://github.com/usagov/vote-gov-drupal/pull/425, https://github.com/usagov/vote-gov-drupal/pull/409
n/a
n/a
2. run `lando start`
3. cd into `Testing`
4. run `npm run cy:frontEnd` and `npm run cy:open` and ensure there are no errors with Cypress running 
5. also under `reports` there is an `index.html` that you can open with your local browser to check that the plug-in is working.

Vote-465: Cypress Updated from Dependabot

---

testing/cypress/e2e/backEndTests/content-editor-access.cy.js
testing/cypress/e2e/backEndTests/content-manager-access.cy.js
testing/cypress/e2e/backEndTests/site-admin-access.cy.js

[Vote-506](https://cm-jira.usa.gov/browse/VOTE-506)
This PR will update Cypress backend testing with a new URL for media access tests 
n/a
n/a
2. cd into `testing` -> you may need to run `lando drush pm-uninstall usagov_login` 
3. run `npm run cy:backEnd` and verify that tests are now passing

Vote-506: Update Cypress backend tests with new media URL

---

.lando.yml
composer.lock

[VOTE-444](https://cm-jira.usa.gov/browse/VOTE-444)
Resolve Dependabot Alert - https://github.com/usagov/vote-gov-drupal/security/dependabot/16
1. Locally, run `lando retune`
1. Locally confirm that `lando composer --version` outputs 2.6.5
2. Confirm that everything installs without any issues after running `lando composer install` or watching output from Post-deploy command.
3. Once deployed/merged, confirm that the Dependabot Alert, https://github.com/usagov/vote-gov-drupal/security/dependabot/16, is resolved.

VOTE 444 - Update composer vulnerability

---

composer.json
composer.lock
config/sync/block.block.htmlsitemap.yml
config/sync/core.extension.yml
config/sync/views.view.sitemap.yml
web/modules/custom/ec_placeholder/ec_placeholder.info.yml
web/modules/custom/ec_placeholder/ec_placeholder.module
web/modules/custom/ec_placeholder/src/Plugin/EmbeddedContent/ECPlaceholder.php
web/modules/custom/ec_placeholder/templates/embedded-content/ec-placeholder.html.twig
web/themes/custom/vote_gov/templates/embedded-content/ec-placeholder--sitemap-menu.html.twig
web/themes/custom/vote_gov/templates/embedded-content/ec-placeholder--state-list.html.twig
web/themes/custom/vote_gov/templates/views/views-view--sitemap.html.twig

https://cm-jira.usa.gov/browse/VOTE-482
Updates for improving the manability of the html sitemap
1. go to http://vote-gov.lndo.site/node/66/edit
2. Insert a new line after the Main Navigation heading in the body field.
3. Add new embedded content placeholder
4. Save and view the page
5. Confirm that there is a menu displaying where the placeholder is.

VOTE-482 html sitemap improvements

---

config/sync/core.entity_form_display.block_content.nvrf_a_b_message.default.yml
config/sync/core.entity_form_display.node.nvrf_page.default.yml
config/sync/core.entity_view_display.block_content.nvrf_a_b_message.default.yml
config/sync/core.entity_view_display.node.nvrf_page.default.yml
config/sync/core.entity_view_display.node.nvrf_page.teaser.yml
config/sync/field.field.block_content.nvrf_a_b_message.field_touchpoints_id.yml
config/sync/field.field.node.nvrf_page.field_display_title.yml
config/sync/field.storage.block_content.field_touchpoints_id.yml
config/sync/field.storage.node.field_display_title.yml
config/sync/views.view.nvrf_api.yml
config/sync/views.view.nvrf_api_blocks.yml
config/sync/views.view.nvrf_api_taxonomy.yml
web/modules/custom/vote_nvrf/src/Plugin/Field/FieldFormatter/NVRFDoubleFieldsJsonKeyValueFormatter.php

https://cm-jira.usa.gov/browse/VOTE-324
Modifications to NVRF API and content model

VOTE-324 NVRF API modifications

---

config/sync/language/nv/core.date_format.long_date.yml
config/sync/language/nv/core.date_format.revision_date.yml
web/themes/custom/vote_gov/src/sass/global/typography.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-form.scss
web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss
web/themes/custom/vote_gov/templates/field/double-field-item--field-in-person-deadline.html.twig
web/themes/custom/vote_gov/templates/field/double-field-item--field-online-deadline.html.twig
web/themes/custom/vote_gov/templates/field/time.html.twig
web/themes/custom/vote_gov/templates/navigation/links--language-block.html.twig
web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig
web/themes/custom/vote_gov/templates/partial/register/registration-date-mail.html.twig

https://cm-jira.usa.gov/browse/VOTE-343
Alter day and year font for Navajo translation to not use Navajo font.
1. cd into vote_gov and run `npm run build`
1. Edit Alaska in English and add specific dates for the all deadlines.
2. View the Alaska page and see that the dates are correctly displaying in English
3. Go to the Navajo translation and see that the day and year are not using the Navajo font.

Bug/vote 343/navajo date numerals

---

.circleci/config.yml

N/A
This PR will pause Cypress tests within the pipeline due to Static Site being behind the VDI
n/A
n/a
1. Review `.yml` and ensure that cypress tests are commented out

Pause Cypress test within pipeline

---

scripts/pipeline/scheduled_backup.sh

testing static site backup on test

testing static site backup on test

---

scripts/pipeline/cloud-gov-deploy.sh

[VOTE-262](https://cm-jira.usa.gov/browse/VOTE-262)
Enable rolling deployment for the CMS/Drupal application
1. While the deploy is happening, ensure availability of the Drupal site.

VOTE-262: enable rolling deployment for the CMS application

---

web/modules/custom/vote_utility/translations/ypk.po

[Vote-254](https://cm-jira.usa.gov/browse/VOTE-254)
This Pr will update the "Other ways to vote" string within the Yupik translation on state pages
n/a
n/a
3. visit [page](http://vote-gov.lndo.site/ypk/register/ak) and check that string above the nvrf download matches `Ilaneng ilatelleghqaneng`

Vote-254 - Update to Yupik string for "Other ways to Vote"

---

testing/package-lock.json
testing/package.json

[Vote-443](https://cm-jira.usa.gov/browse/VOTE-443)
This PR will update to testing dir from dependabot 
n/a
n/a
1. cd into `testing` and run the following commands `npm run cy:fullTests` and `npm run cy:open`and verify that tests are running with no errors

Update to testing dir from dependabot

---

web/themes/custom/vote_gov/package-lock.json
web/themes/custom/vote_gov/package.json

[Vote-443](https://cm-jira.usa.gov/browse/VOTE-443)
This Pr will update the uswds compile and hopefully address the issue with `postcss`
1

Update:  Current theme updates from dependabot

---

web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

[Vote-443](https://cm-jira.usa.gov/browse/VOTE-443)
This PR will update to the new votegov theme to uswds and uswds compile
n/a
n/a
1.

Update: To new theme from dependabot

---

config/sync/core.base_field_override.node.voter_guide.promote.yml
config/sync/core.base_field_override.node.voter_guide.status.yml
config/sync/core.entity_form_display.node.voter_guide.default.yml
config/sync/core.entity_view_display.node.voter_guide.default.yml
config/sync/core.entity_view_display.node.voter_guide.full.yml
config/sync/core.entity_view_display.node.voter_guide.teaser.yml
config/sync/field.field.node.voter_guide.body.yml
config/sync/field.field.node.voter_guide.field_subtitle.yml
config/sync/field.storage.node.field_subtitle.yml
config/sync/language.content_settings.node.voter_guide.yml
config/sync/node.type.voter_guide.yml
config/sync/simple_sitemap.bundle_settings.default.node.voter_guide.yml
config/sync/user.role.content_editor.yml
config/sync/user.role.content_manager.yml
config/sync/workflows.workflow.publishing_content.yml

https://cm-jira.usa.gov/browse/VOTE-538
Add new Voter Guide content type and set up the display
1. log into the site and visit http://vote-gov.lndo.site/node/add/voter_guide
2. Create a new Voter Guide and make sure the content is displaying when viewing.

VOTE-538 add Voter Guide content type

---

config/sync/views.view.nvrf_api.yml
config/sync/views.view.nvrf_api_blocks.yml
config/sync/views.view.nvrf_api_taxonomy.yml
web/sites/default/settings.cloudgov.php

[VOTE-542](https://cm-jira.usa.gov/browse/VOTE-542)
Exclude api endpoints from Tome generation. Exclude translation paths as well.
None
1. Once deployed to testing environment, confirm that the static site does not include any of the following paths.
/api/nvrf/fields.json
/api/nvrf/messages.json
/api/nvrf/cards.json
/api/nvrf/states.json
/api/nvrf/pages.json
Prefix the above urls with /{langcode} to try to confirm that the translated api endpoint is not available. (ie. /es/api/nvrf/....)

VOTE-542: Exclude api paths from Tome site generation.

---

web/themes/custom/votegov/gulpfile.js
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

https://cm-jira.usa.gov/browse/VOTE-583
Remove browsersync from votegov theme
1. cd into votegov theme and run `npm i`
1. run `npm run dev` and make sure there are no errors
2. run `npm run build` and make sure there are no errors

VOTE-583 remove browsersync from votegov theme

---

config/sync/user.role.content_manager.yml
config/sync/views.view.nvrf_state_reports.yml
web/modules/custom/vote_nvrf/src/Plugin/Field/FieldFormatter/NVRFFieldsDefaultFormatter.php

Update permission for Content Manager role to access the taxonomy listing page
https://cm-jira.usa.gov/browse/VOTE-588
Add a NVRF state report listing page for QAing NVRF content
1. log into the CMS and visit http://vote-gov.lndo.site/admin/nvrf-state-report

VOTE-588 Create a NVRF state report admin page

---

config/sync/views.view.nvrf_reports.yml

https://cm-jira.usa.gov/browse/VOTE-588
Created a view page for nvrf fields and their instructions, help text, and error text.
1. Sign in as admin to the CMS.
2. View http://vote-gov.lndo.site/admin/nvrf-fields and confirm nvrf fields and data are visible.
3. Click the edit button for one of the fields, edit data, and confirm the view page shows the updates.
4. Confirm the view page is not visible when signed out.

Feature/vote 588/nvrf field report view

---

config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_form_display.taxonomy_term.nvrf_field.default.yml
config/sync/core.entity_view_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.full.yml
config/sync/core.entity_view_display.node.state_territory.teaser.yml
config/sync/core.entity_view_display.taxonomy_term.nvrf_field.default.yml
config/sync/editor.editor.basic_html.yml
config/sync/field.field.node.state_territory.field_pdf_pages.yml
config/sync/field.field.taxonomy_term.nvrf_field.field_section_description.yml
config/sync/field.storage.node.field_pdf_pages.yml
config/sync/field.storage.taxonomy_term.field_section_description.yml
config/sync/filter.format.basic_html.yml
config/sync/user.role.content_manager.yml
config/sync/views.view.nvrf_api.yml
config/sync/views.view.nvrf_api_blocks.yml
config/sync/views.view.nvrf_api_taxonomy.yml
config/sync/views.view.nvrf_reports.yml
config/sync/views.view.nvrf_state_reports.yml
testing/cypress/e2e/frontEndTests/language-selector.cy.js
testing/cypress/e2e/frontEndTests/state-registration.cy.js
web/modules/custom/vote_nvrf/src/Plugin/Field/FieldFormatter/NVRFFieldsDefaultFormatter.php
web/themes/custom/vote_gov/templates/paragraph/paragraph--registration-tool.html.twig
web/themes/custom/votegov/gulpfile.js
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json
web/themes/custom/votegov/templates/embedded-content/ec-placeholder.html.twig

https://cm-jira.usa.gov/browse/VOTE-591
HOTFIX release to deploy data model updates to unblock NVRF content entry

MId-sprint 48: HOTFIX release

---

scripts/pipeline/deb-mysql-client-install.sh

Testing backup failures potential fix

testing updates to resolve backup failures

---

.circleci/config.yml

testing updates to resolve backup failures v2

---

.circleci/config.yml

Testing further backup script changes

testing updates to resolve backup failures v3

---

scripts/pipeline/scheduled_backup.sh

[VOTE-234](https://cm-jira.usa.gov/browse/VOTE-234)
Added the static site files to the backup archive.
1. Allow scheduled pipeline backup job to run.
2. Download resultant backup archive.
3. Verify static archive inside the backup archive.

VOTE-234: added the static site files to be added to the backup archive

---

.circleci/config.yml
scripts/pipeline/deb-mysql-client-install.sh

[VOTE-650](https://cm-jira.usa.gov/browse/VOTE-650)
Updated dependency installations to not fail.
1. Allow scheduled-backup workflow to run.
2. Download resultant archive.
3. Verify contents.

VOTE-650: fixed scheduled backup failures

---

config/sync/views.view.nvrf_state_reports.yml

https://cm-jira.usa.gov/browse/VOTE-690
Create a new report page for when logged into the system at `/admin/nvrf-state-report/types`
1. visit http://vote-gov.lndo.site/admin/nvrf-state-report/types and test filtering

VOTE-690 add new nvrf state report page

---

.circleci/config.yml
scripts/pipeline/cloud-gov-deploy.sh

VOTE-712 testing

---

testing/package-lock.json
testing/package.json
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

[Vote-780](https://cm-jira.usa.gov/browse/VOTE-780)
This Pr will update cypress and USWDS from dependabot PRs
This will close out: https://github.com/usagov/vote-gov-drupal/pull/491, https://github.com/usagov/vote-gov-drupal/pull/526, https://github.com/usagov/vote-gov-drupal/pull/510 and https://github.com/usagov/vote-gov-drupal/pull/474
n/a
n/a
1. pull down locally 
2. cd into testing and run `npm i` and make sure no errors can also run `npm run cy:open` and check that there are no issues loading cypress
3. cd in `web/themes/custom/votegov` and run `npm i` and `npm run build` and ensure there are no issues and run `lando reutne` and make sure site loads

Vote - 780:  Dependabot Updates

---

config/sync/core.entity_form_display.paragraph.image_text_cta.default.yml
config/sync/core.entity_view_display.paragraph.image_text_cta.default.yml
config/sync/field.field.node.landing.field_paragraph_components.yml
config/sync/field.field.paragraph.image_text_cta.field_body.yml
config/sync/field.field.paragraph.image_text_cta.field_heading.yml
config/sync/field.field.paragraph.image_text_cta.field_image_alignment.yml
config/sync/field.field.paragraph.image_text_cta.field_link.yml
config/sync/field.field.paragraph.image_text_cta.field_media.yml
config/sync/field.storage.paragraph.field_image_alignment.yml
config/sync/field.storage.paragraph.field_link.yml
config/sync/field.storage.paragraph.field_media.yml
config/sync/paragraphs.paragraphs_type.image_text_cta.yml

https://cm-jira.usa.gov/browse/VOTE-742
Add new image + text CTA paragraph type to landing page content type
1. visit http://vote-gov.lndo.site/node/add/landing and add a new Image + Text CTA paragraph to the page
2. Check the data model sheet to check that all field are accounted for

VOTE-742 add image + text CTA paragraph type

---

scripts/pipeline/cloud-gov-post-deploy-upkeep.sh

VOTE-541 testing

---

scripts/pipeline/scheduled_backup.sh

VOTE-727 testing

---

config/sync/core.entity_form_display.paragraph.feature_cards.default.yml
config/sync/core.entity_view_display.paragraph.feature_cards.default.yml
config/sync/field.field.node.landing.field_paragraph_components.yml
config/sync/field.field.paragraph.feature_cards.field_cards.yml
config/sync/field.field.paragraph.feature_cards.field_heading.yml
config/sync/field.storage.paragraph.field_cards.yml
config/sync/paragraphs.paragraphs_type.feature_cards.yml

[Vote-741](https://cm-jira.usa.gov/browse/VOTE-741)
This Pr will set up the config for the Feature Card section on the home page.
1. pull down branch and run `lando retune`
1. Log into system and edit the home page and add text and link for the feature cards section.  after you are done should see similar as screen shot before and link to a voter guide.

Vote-741: Card Information Config Set Up

---

scripts/pipeline/cloud-gov-post-deploy-upkeep.sh
scripts/pipeline/cloud-gov-post-deploy.sh
scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh

VOTE 846 testing

---

scripts/pipeline/cloud-gov-post-deploy-upkeep.sh
scripts/pipeline/cloud-gov-post-deploy.sh
scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh

[VOTE-846](https://cm-jira.usa.gov/browse/VOTE-846)
Correct an issue that arose in VOTE-712 to properly handle SSH access to prod in post deploy steps.
1. Allow deploy to run.
2. Verify SSH access is allowed before each post deploy step.
3. Confirm each post deploy step succeeds.
4. Verify SSH access is finally disallowed after the pipeline finishes.

VOTE-846: update post deploy steps to handle prod ssh access

---

web/modules/custom/vote_utility/translations/hmn.po

[VOTE-810](https://cm-jira.usa.gov/browse/VOTE-810)
Update the month translations for Hmong.
N/A
Locally, run `lando retune` to import string translations from PO file.
1. Visit http://vote-gov.lndo.site/admin/config/regional/translate
2. Do a search using the following: Translation: Hmong, Search In: Only translated strings
3. Confirm that the search results include translated months in the list of translated strings for Hmong.

VOTE-810: Update month translations for Hmong.

---

.lando.yml
composer.json
composer.lock

…s well as local via lando. Update composer/installers while we are at it.
[VOTE-817](https://cm-jira.usa.gov/browse/VOTE-817)
Update composer to latest version, 2.7.1, to address [Dependabot Vulnerability Alert](https://github.com/usagov/vote-gov-drupal/security/dependabot/25).
Update composer/installers to latest as well.
Update lando config to use Composer 2.7.1.
N/A
1. Locally, run `lando rebuild`.
2. then run `lando retune`
1. Locally, run `lando composer --version`, and confirm that the version shows 2.7.1.
3. Once merged, confirm that the Dependabot Vulnerability Alert is resolved.

VOTE-817: Update composer to version 2.7.1

---

web/themes/custom/votegov/src/sass/_variables.scss
web/themes/custom/votegov/src/sass/base/link.scss
web/themes/custom/votegov/src/sass/components/footer-primary.scss
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/components/page-subtitle.scss
web/themes/custom/votegov/src/sass/components/page-title.scss
web/themes/custom/votegov/src/sass/mixins/mixins.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-button.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-search.scss
web/themes/custom/votegov/templates/component/button.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig

Create a new button component template

Add new global mixins

---

config/sync/field.field.node.landing.field_paragraph_components.yml
config/sync/field.field.paragraph.basics_block.field_heading.yml

https://cm-jira.usa.gov/browse/VOTE-885
Enable and configure the landing page basic block
1. Create a new landing page http://vote-gov.lndo.site/node/add/landing
2. Add accordion group -> Basics Block
3. Confirm the heading is optional

VOTE-885 Enable and configure landing page basic block

---

composer.lock
web/themes/custom/votegov/src/sass/uswds-overrides/_index.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-sidenav.scss

[VOTE-848](https://cm-jira.usa.gov/browse/VOTE-848)
Update the styling of the sidenav to include an active state and make it sticky.
1. cd in votegov theme and run `npm run build`
1. visit http://vote-gov.lndo.site/preparing-vote-18-or-younger and confirm the active state style of the link in the sidenav.
2. Scroll on the page and confirm the navigation stays sticky until you reach the footer.

VOTE-848 update styling for sidenav

---

config/sync/pathauto.pattern.state_territory.yml
config/sync/pathauto.pattern.state_territory_es.yml

https://cm-jira.usa.gov/browse/VOTE-866
Update url alias for state content type
1. visit http://vote-gov.lndo.site/admin/config/search/path/update_bulk
2. Select "Content" and "Update the URL alias for paths having an old URL alias" and update
3. visit http://vote-gov.lndo.site/register/ak and make sure you are get redirected to http://vote-gov.lndo.site/register/alaska
4. generate a local static site: run `lando static`
5. visit http://html.vote-gov.lndo.site/register/ak and make sure you get redirected to http://html.vote-gov.lndo.site/register/alaska

VOTE-866 update url aliases for state content type

---

web/themes/custom/votegov/src/js/search-bar.js
web/themes/custom/votegov/templates/block/block-content--search.html.twig
web/themes/custom/votegov/votegov.libraries.yml

[VOTE-870](https://cm-jira.usa.gov/browse/VOTE-870)
Adds event listener to clear search input on blur
2. npm run build inside theme directory
3. type a value into search input then click outside of it, input should be cleared and placeholder text is visible

VOTE-870: clear search on blur functionality

---

web/themes/custom/votegov/src/sass/base/typography.scss
web/themes/custom/votegov/src/sass/components/_index.scss
web/themes/custom/votegov/src/sass/components/content-section.scss
web/themes/custom/votegov/src/sass/components/field.scss
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/components/page-title.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-button.scss
web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

VOTE-955 update registration form selector component
https://cm-jira.usa.gov/browse/VOTE-936
https://cm-jira.usa.gov/browse/VOTE-955
Styling refinements to state page
Styling refinements to the form selector component
1. cd into the votegov theme and run `npm run build`
1. visit http://vote-gov.lndo.site/register/arizona and review the spacing on to masthead and page content
2. review the spacing for the button on mobile for the form selector component

VOTE-936 state styling refinements

---

web/sites/default/settings.cloudgov.php

VOTE-906 testing

---

web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig

https://cm-jira.usa.gov/browse/VOTE-909
Add parent link inside header menu dropdown
1. log in and visit http://vote-gov.lndo.site/
2. toggle the dropdown for "Guide to Voting" and confirm there is a clickable link to "Guide to Voting" inside the dropdown.

VOTE-909 add submenu parent link in dropdown

---

testing/cypress/e2e/frontEndTests/government-banner.cy.js
testing/cypress/e2e/frontEndTests/language-selector.cy.js
testing/cypress/e2e/frontEndTests/menu.cy.js
testing/cypress/e2e/frontEndTests/search-bar.cy.js
testing/cypress/e2e/frontEndTests/state-registration.cy.js
testing/cypress/fixtures/language-selection.json
web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig
web/themes/custom/votegov/templates/navigation/links--language-block.html.twig
web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig

[Vote-969](https://cm-jira.usa.gov/browse/VOTE-969)
Updating Cypress test to include frontend test now that we have working components. 
n/a
n/a
1. Pull down branch
3. cd into votegov dir and run `npm run build`
4. cd into `testing` and run `cy:fullTests` and ensure tests are passing

Vote-969: Cypress Updates Post 55 Sprint

---

web/themes/custom/votegov/fonts/navajo-font/stylesheet.css
web/themes/custom/votegov/src/sass/base/typography.scss
web/themes/custom/votegov/templates/layout/page.html.twig

[VOTE-980](https://cm-jira.usa.gov/browse/VOTE-980)
Enables Navajo font and updates Navajo stylesheet selector for overrides
3. Add navajo translation to some content and confirm that it is converted to Navajo font

VOTE-980: Enable Navajo Font

---

web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig
web/themes/custom/votegov/votegov.libraries.yml

[Vote-991](https://cm-jira.usa.gov/browse/VOTE-991)
Updating the download NVRF button on state pages to open in a new tab and download the document.
n/a
n/a
1. Pull down the branch and run `land retune`
2. Vist a state page and check that the `Download NVRF` button is opening in a new tab and showing the correct translation of the form

Vote-991: Update NVRF download function

---

web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[VOTE-992](https://cm-jira.usa.gov/browse/VOTE-992)
Removes unnecessary comma from translation files and state page template.
2. Visit a state page to confirm comma is removed.
3. Other translations should still translate the same.
1. Insert steps to test and confirm the result meets the "definition of done".

VOTE-992: Remove a comma from state page template

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-contact-identifier.scss

[Vote-1030](https://cm-jira.usa.gov/browse/VOTE-1032)
Adjusted the bottom spacing to be a percentage and not a fixed amount.
n/a
n/a
1. Pull down the branch and `run lando retune`
2. Cd into `votegov` directory and run `npm run build`
3. Visit home page and scroll to the USA.gov section of the footer identifier and then reduce the screen size and ensure that the red line keeps the same position

Vote-1030: Update to usa.gov section

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-sign-up.scss

[Vote-1032](https://cm-jira.usa.gov/browse/VOTE-1032)
Removing height and adding width to help with wrapping of text within the email signup button on at the tablet breakpoint 
n/a
n/a
1. Pull down the branch and cd into the `votegov` directory 
2. Run `npm run build`
3. Inspect and reduce the screen size to 780px and verify that text is no longer getting cut off

Vote-1032: Fix to sign up button wrapping

---

testing/package-lock.json
testing/package.json
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

[Vote-1045](https://cm-jira.usa.gov/browse/VOTE-1045)
Updates from Dependabot 
Closes out:
- https://github.com/usagov/vote-gov-drupal/pull/617
- https://github.com/usagov/vote-gov-drupal/pull/637
- https://github.com/usagov/vote-gov-drupal/pull/638
- https://github.com/usagov/vote-gov-drupal/pull/647
n/a
n/a
1. cd into `testing` and run `npm i` ensure there are no build issues
2. start local and run `npm run cy:fullTests` and ensure tests are passing 
3. cd into the `votegov` theme and run `npm i` and ensure there are no build issues 
4. run `npm run build` and `npm run gulp` and check no errors in build or run

Vote-1045:  Dependabot updates

---

testing/cypress/e2e/frontEndTests/email-signup.cy.js
testing/cypress/e2e/frontEndTests/footer-contact.cy.js
testing/cypress/e2e/frontEndTests/government-banner.cy.js
testing/cypress/e2e/frontEndTests/language-selector.cy.js
testing/cypress/e2e/frontEndTests/menu.cy.js
testing/cypress/e2e/frontEndTests/search-bar.cy.js
testing/cypress/e2e/frontEndTests/state-pages.cy.js
testing/cypress/e2e/frontEndTests/state-registration.cy.js
testing/cypress/fixtures/homepage-accordion.cy.js
web/themes/custom/votegov/fonts/navajo-font/stylesheet.css
web/themes/custom/votegov/templates/block/block--votegov-languageswitcher.html.twig
web/themes/custom/votegov/templates/block/block-content--email-signup.html.twig
web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig
web/themes/custom/votegov/templates/block/block-content--search.html.twig
web/themes/custom/votegov/templates/component/footer--secondary-section.html.twig
web/themes/custom/votegov/templates/component/page-title.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig

[Vote-1056](https://cm-jira.usa.gov/browse/VOTE-1056)
Updating data-test ids to all be camel case to provided consistency 
n/a
n/a
1. Pull down branch and run `lando retune` 
2. Cd into testing and run `npm run cy:fullTests` and verify that tests are passing 
3. Do a search for `data-test` and ensure that all test ids that are in a Cypress file or a twig template within the `votegov` theme are camel case

Vote-1056: Data Test ID Updates

---

web/themes/custom/votegov/src/sass/components/footer-primary.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-footer.scss

[VOTE-952](https://cm-jira.usa.gov/browse/VOTE-952)
Adds column gap on primary footer section and adds more breakpoints
1. npm run build
2. Check visually that the primary section of the footer works at all breakpoints without columns becoming too squished

VOTE-952: Refine primary footer

---

web/themes/custom/votegov/src/js/registration-tool.js

[Vote-1055](https://cm-jira.usa.gov/browse/VOTE-1055)
Updating if statement for filter function to add a check that the filtered options matches the full string that the user inputs. This fix will address the bug when a user would input a state that has multiple words (South Carolina, North Dakota, New Mexico) 
***Solution***
Adding another or as another conditional check, and using the match method and regex to check that the users input matches the first letter of the string based on the filter input and making it case insensitive. 
This is done with the `^` character, this will target the first letter of the `txtValue` object along with the rest of the string and match it with the `filter` object, by adding the `i` it makes it case insensitive to ensure no mater how the user inputs …

Vote-1055: State registration bug fix

---

config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.full.yml
config/sync/core.entity_view_display.node.state_territory.teaser.yml
config/sync/field.field.node.state_territory.field_updated_date.yml
config/sync/field.storage.node.field_updated_date.yml
config/sync/language.entity.am.yml
config/sync/language.entity.hmn.yml
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[Vote-945](https://cm-jira.usa.gov/browse/VOTE-945)
Updating last updated to be a filed value within content page and set conditional check that if the date is not set then it wont render the field
n/a
n/a
1. Pull down branch and run `lando retune`
2. Login into site and visit a state page and scroll to the bottom and check that `Last Updated: <date>` does not appear on page
3. Edit page and add a date to the Updated Date field and check to see that date is now on the page 
4. Select various language options and ensure that the last updated date text is getting translated as expected

Vote-945: Adding Last Updated Field

---

config/local/config_split.patch.language.entity.so.yml
config/production/config_split.patch.language.entity.so.yml
config/sync/language.entity.so.yml
config/sync/language.entity.tl.yml
config/sync/language.entity.vi.yml
config/sync/language.entity.ypk.yml
config/sync/language.negotiation.yml
config/sync/language/so/core.date_format.long_date.yml
config/sync/language/so/core.date_format.revision_date.yml
config/sync/language/so/language.entity.so.yml
config/sync/language/so/metatag.metatag_defaults.front.yml
config/sync/language/so/metatag.metatag_defaults.global.yml
config/sync/language/so/metatag.metatag_defaults.node__state_territory.yml
web/modules/custom/vote_utility/translations/so.po

[VOTE-864](https://cm-jira.usa.gov/browse/VOTE-894)
Add PO and Config files to enable and provide string translations for Somali.
n/a
1. Locally, run `lando retune -y` to import config files and string translations from PO file.
1. Visit http://vote-gov.lndo.site/admin/config/regional/language and confirm that Somali language is listed.
2. Visit http://vote-gov.lndo.site/admin/config/regional/translate
3. Do a search using the following: Translation: Somali, Search In: Only translated strings
4. Confirm that the search returns a list of translated strings for Somali.
5. Visit http://vote-gov.lndo.site/admin/config/regional/language and confirm the enable/disabled setting for Somali language according to the following:
- Disabled, Local Environment
- Enabled, Non-Production Environment
- …

VOTE-864: Add config and po files for Somali

---

web/themes/custom/vote_gov/templates/block/block--system-menu-block--footer.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig

[Vote-1009](https://cm-jira.usa.gov/browse/VOTE-1009)
Updating touchpoints survey to have `vote.gov` in sentence case
1. pull down branch and run `lando retune` and cd into `votegov` theme and run `npm run build`
1. visit local and verify that touch points button reads `How can we improve vote.gov` with `vote.gov` being sentence case

Vote-1009: Update to vote.gov to be sentence case in footer

---

web/themes/custom/votegov/src/sass/components/_index.scss
web/themes/custom/votegov/src/sass/components/accordion-group.scss
web/themes/custom/votegov/src/sass/components/registration-tool.scss
web/themes/custom/votegov/templates/field/double-field-item--field-accordions.html.twig
web/themes/custom/votegov/templates/field/field--field-accordions.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--accordion-group.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig

https://cm-jira.usa.gov/browse/VOTE-1118
Update legacy homepage components in new theme
1. cd into votegov theme and run `npm run build`
1. log into your local and visit http://vote-gov.lndo.site/votegov-homepage
2. Confirm that the components on the page are styled

VOTE-1118 update legacy homepage component in new theme

---

web/themes/custom/votegov/img/svg/close-white.svg
web/themes/custom/votegov/src/sass/uswds-overrides/usa-alert.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss
web/themes/custom/votegov/templates/block/block--votegov-languageswitcher.html.twig

[Vote-1083](https://cm-jira.usa.gov/browse/VOTE-1083)
Refinements to language selector for mobile view to match design. 
<details>
<summary>Before and After of Language Menu</summary>
<br>
</details>
Also an update to the alert banner at mobile as well to reduce the amount of space on the left and right side.  That can be found at [this commit](https://github.com/usagov/vote-gov-drupal/commit/4b136f117227d7847bac2d14bd3329d74a5eba07)
<details>
<summary>Before and After of Alert menu</summary>
<br>
</details>
1. cd into `votegov` theme and run `npm run build`
1. reduce screen size to mobile view (anything under 640px) and verify that the design is set up like the [deisgn](https://www.figma.com/file/E70piAGXmi4UzrHs0A90cm/Vote.gov-Redesign-2024-(4.5-Archive)?node-id=1567:2507&mode=dev) …

Vote-1083: Mobile Language Selector Menu Refinements

---

.gitattributes
composer.lock

[VOTE-1067](https://cm-jira.usa.gov/browse/VOTE-1067)
Update Drupal Core along with contrib modules.
1. Locally, run `lando retune` to install updates.
1. Review the ticket comments for testing instructions.

VOTE-1067: Update Drupal core and contrib modules.

---

config/sync/core.base_field_override.menu_link_content.menu_link_content.changed.yml
config/sync/core.base_field_override.menu_link_content.menu_link_content.description.yml
config/sync/core.base_field_override.menu_link_content.menu_link_content.link_override.yml
config/sync/core.base_field_override.menu_link_content.menu_link_content.metatag.yml
config/sync/core.base_field_override.menu_link_content.menu_link_content.title.yml
config/sync/language.content_settings.menu_link_content.menu_link_content.yml
web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig

https://cm-jira.usa.gov/browse/VOTE-1147
Enable translation on menu items
1. log in and visit http://vote-gov.lndo.site/es/admin/structure/menu/manage/main
2. Click on the first menu item Operations dropdown and confirm that "Translate" is an option
3. Select the Translate link and add a Spanish translation
4. Change the title and save
5. visit http://vote-gov.lndo.site/es/node/77 and confirm that your title displays
6. visit http://vote-gov.lndo.site/register and confirm that it still shows the original

VOTE-1147 Enable translations on menu items

---

config/sync/core.entity_form_display.node.voter_guide.default.yml
config/sync/core.entity_view_display.node.voter_guide.default.yml
config/sync/core.entity_view_display.node.voter_guide.full.yml
config/sync/core.entity_view_display.node.voter_guide.teaser.yml
config/sync/field.field.node.voter_guide.field_metatags.yml

[Vote-1161](https://cm-jira.usa.gov/browse/VOTE-1161)
Adding meta tag fields for voter guide
1. log into site and create a new voter guide page or visit a current page and check that the meta tag option is available

Vote-1161: Adding meta tag fields to voter guide

---

config/sync/core.entity_form_display.node.landing.default.yml
config/sync/core.entity_form_display.node.nvrf_page.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_form_display.node.voter_guide.default.yml
config/sync/node.type.landing.yml
config/sync/node.type.page.yml

https://cm-jira.usa.gov/browse/VOTE-1340
See ticket description
1. Visit each node type add form to make sure the fields listed in the ticket are removed

VOTE-1340 remove extra options from node forms

---

web/modules/custom/vote_utility/translations/am.po

[VOTE-1086](https://cm-jira.usa.gov/browse/VOTE-1086)
Update config files to include requested translation updates. 
none
1. Locally, run `lando retune` to import updated config and po changes.
2. Login as an admin, and confirm that the changes have been updated by visiting /admin/config/regional/translate.
3. Perform a filtered search for "Online registration deadline:", using Amharic as the filter.
4. Confirm the translated text is 'ድረገጽ ላይ ምዝገባ የመጨረሻ ቀን፦'

VOTE-1086: Update translation for 'Online registration deadline'

---

testing/cypress.config.js
testing/cypress/e2e/backEndTests/footer-menu-editor.cy.js
testing/cypress/e2e/frontEndTests/menu.cy.js
testing/cypress/fixtures/axe-pages.json
testing/package-lock.json
testing/package.json

[Vote-1184](https://cm-jira.usa.gov/browse/VOTE-1184)
[Vote-1151](https://cm-jira.usa.gov/browse/VOTE-1151)
Updates to Cypress and Axe-core -> Closes out https://github.com/usagov/vote-gov-drupal/pull/686 and https://github.com/usagov/vote-gov-drupal/pull/676
Also updating Menu test to add real event steps, fixing footer menu to delete link that is added during test and adding pages to axe tests
1. cd into `testing` and run `npm i` and `lando drush pm-uninstall usagov_login` (to allow backend tests to run)
1. run `npm run cy:fullTests` and verify no errors 
2. run `npm run cy:axe` and verify there are no run errors (there are text errors but they have been ticketed out just need to check that the update does not effect the test)

Vote-1151/1184: Dependabot and Cypress Test Updates

---

web/themes/custom/votegov/src/sass/base/containers.scss
web/themes/custom/votegov/src/sass/base/media.scss
web/themes/custom/votegov/src/sass/base/typography.scss
web/themes/custom/votegov/src/sass/components/_index.scss
web/themes/custom/votegov/src/sass/components/basic.scss
web/themes/custom/votegov/src/sass/components/basics-block.scss
web/themes/custom/votegov/src/sass/components/columns.scss
web/themes/custom/votegov/src/sass/components/date.scss
web/themes/custom/votegov/src/sass/components/feature-cards.scss
web/themes/custom/votegov/src/sass/components/field.scss
web/themes/custom/votegov/src/sass/components/footer-primary.scss
web/themes/custom/votegov/src/sass/components/heading.scss
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/components/registration-tool.scss
web/themes/custom/votegov/src/sass/mixins/mixins.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-footer.scss
web/themes/custom/votegov/templates/component/contact-identifier.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig
web/themes/custom/votegov/templates/navigation/menu--footer.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig
web/themes/custom/votegov/templates/node/node.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--basic.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--basics-block.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--feature-cards.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--image-text-cta.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--quicklinks.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
web/themes/custom/votegov/templates/taxonomy/taxonomy-term--basics-modules.html.twig

This work was completed in peer programming sessions between Ray, Samira, Christian and Mandy.

Optimize votegov theme

---

config/local/config_split.patch.user.role.content_translator.yml
config/local/config_split.patch.user.role.site_builder.yml
config/production/config_split.patch.user.role.content_translator.yml
config/production/config_split.patch.user.role.site_builder.yml
config/sync/system.action.user_add_role_action.content_translator.yml
config/sync/system.action.user_add_role_action.site_builder.yml
config/sync/system.action.user_remove_role_action.content_translator.yml
config/sync/system.action.user_remove_role_action.site_builder.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml
config/sync/user.role.content_editor.yml
config/sync/user.role.content_translator.yml
config/sync/user.role.site_admin.yml
config/sync/user.role.site_builder.yml

VOTE-1339 add new Site Builder role
https://cm-jira.usa.gov/browse/VOTE-1117
https://cm-jira.usa.gov/browse/VOTE-1339
Create new roles:
- Content Translator
- Site Builder
**Test Content Translator**
1. Create a new user with role Content Translator.
2. Log in as this user
3. Visit http://vote-gov.lndo.site/admin/content confirm that it only displays "translate" links
4. Visit http://vote-gov.lndo.site/node/82/translations and add a translation for Spanish
5. Edit the page title and save
6. Confirm that the translation is not published
**Test Site Builder**
1. Create a new user with role Site Builder.
2. Log in as this user
3. Confirm that you have access to all content and site building activities
4. Visit http://vote-gov.lndo.site/es/admin/people and confirm you …

VOTE-1117 Add new Content Translator role

---

docs/workflow.md
testing/cypress/e2e/frontEndTests/footer-contact.cy.js
web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/hmn.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/votegov/templates/component/footer--secondary-section.html.twig
web/themes/custom/votegov/votegov.theme

https://cm-jira.usa.gov/browse/VOTE-1119
Insert a link to the Jira ticket (e.g VOTE-XXX).
Replace hardcoded "Vote.gov" strings to be lowercase ("vote.gov"). Any files in the old theme folder (vote_gov) and any generated files are not in scope. Any content coming from the CMS is not included.
1. Visit the about us page and confirm all vote.gov strings (except those that are the first word in a sentence) in the social media sections of the footer.
2. Repeat for each language
3. Spot the rest of the pages and repo for any strings missed (I only found them in the social media section of the footer, but I could have missed).

VOTE-1119 Make hardcoded 'Vote.gov' strings lowercase

---

web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[VOTE-1157](https://cm-jira.usa.gov/browse/VOTE-1157)
Updates text under "Voter registration deadlines" to say:  
"Voter registration deadlines for the November 05, 2024 election. [Find state and local election dates.](https://www.eac.gov/voters/register-and-vote-in-your-state). 
2. Visit a state page and confirm new copy is there
3. Test the new link works
*note that we do not have translations yet

VOTE-1157: Update state CT template content

---

web/themes/custom/votegov/src/sass/components/basics-block.scss
web/themes/custom/votegov/templates/paragraph/paragraph--basics-block.html.twig
web/themes/custom/votegov/templates/taxonomy/taxonomy-term--basics-modules.html.twig

https://cm-jira.usa.gov/browse/VOTE-1182
Sprint 59 additions to release candidate

Sprint 59: additional fixes

---

scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh

VOTE-886 testing

---

.circleci/config.yml
scripts/pipeline/downsync-backup.sh
scripts/pipeline/downsync-restore.sh
scripts/pipeline/scheduled_backup.sh

[VOTE-886](https://cm-jira.usa.gov/browse/VOTE-886)
Add media files to downsync triggerable pipeline. Delete files from restore env that were not present in backup env to ensure parity.
1. Allow deploy to complete.
2. List backup and restore media storage bucket contents.
3. Trigger downsync pipeline.
4. Verify new files from the backup env are present on the restore env.
5. Verify old files in the restore env but not in the backup env are deleted.

VOTE-886: Add media files to downsync

---

.circleci/config.yml

[Vote-1341](https://cm-jira.usa.gov/browse/VOTE-1341)
Updating cypress tests to run pushes to stage. 
n/a
Check that cypress script is now only running on stage

Vote-1341: Add cyrpess back to run on stage

---

web/themes/custom/votegov/src/sass/components/quick-links.scss
web/themes/custom/votegov/src/sass/mixins/mixins.scss

[Vote-1130](https://cm-jira.usa.gov/browse/VOTE-1130)
Addressing some regressions that came up after getting merged into dev 
- Updated the mix in to have the hover, visited and active state be a consistent color
- Designer asked that lists not have a bullet style so this was removed as well  
1.  run `lando retune` and cd into `votegov` theme and run `npm run build`
1. visit home page and check that links in life events no longer have list style and hover, visited and active now all have the same affect with color

Vote-1130: Life Events Refinements 2.0

---

web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/hmn.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/themes/custom/votegov/templates/block/block-content--email-signup.html.twig
web/themes/custom/votegov/templates/component/eacgov-partner.html.twig
web/themes/custom/votegov/templates/component/registration-date/registration-date--by-mail.html.twig
web/themes/custom/votegov/templates/component/registration-date/registration-date--in-person.html.twig
web/themes/custom/votegov/templates/component/registration-date/registration-date--online.html.twig
web/themes/custom/votegov/templates/component/usa-identifier.html.twig
web/themes/custom/votegov/templates/navigation/breadcrumb.html.twig
web/themes/custom/votegov/templates/navigation/menu-local-tasks.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig

remediate template translations
https://cm-jira.usa.gov/browse/VOTE-1965
Remediate string translations in po files and templates
1. Check the contact identifier in the footer in differente translations to make sure it's fully translated.

VOTE-1965 remediate string translations

---

testing/cypress/e2e/backEndTests/basic-page.cy.js
testing/cypress/e2e/backEndTests/user-content-access.cy.js

[Vote-2013](https://cm-jira.usa.gov/browse/VOTE-2013)
Minor updates to cypress backend script to address updates made to the backend 
1. cd into `testing` and run `lando drush pm-uninstall usagov_login` and then run `npm run cy:backEnd` and verify that tests are passing

Vote-2013: Post Sprint 59 Cypress Updates 

---

.circleci/config.yml
docs/devops.md
testing/cypress/e2e/externalLinks/external-links-validator.cy.js
testing/pipeline.config.js

[Vote-2039](https://cm-jira.usa.gov/browse/VOTE-2039)
Adding link validation to be run on beta every monday and thursday. 
n/a
1. check last run with this set up [here](https://app.circleci.com/pipelines/github/usagov/vote-gov-drupal/81841/workflows/4691d6ba-ca8a-40c7-ac5f-9c1904aca07a/jobs/87218) and check that tests pass 
2. check that job will now run on a cron while on the stage branch (which will have the most updated work)

Vote-2039: Link Validation Beta

---

web/themes/custom/votegov/src/sass/components/field.scss
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/components/page-masthead.scss
web/themes/custom/votegov/src/sass/components/page-title.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-button.scss
web/themes/custom/votegov/templates/layout/page.html.twig

[VOTE-1936](https://cm-jira.usa.gov/browse/VOTE-1936)
Updates basic page with latest PX design changes
3. Compare a basic page (About) to latest PX designs https://www.figma.com/design/u82ICmmHNBKpE1Tw4nsO0K/Vote.gov-Redesign-2024-(Master)?node-id=8989-24648&m=dev
4. Compare with and without sidebar and media

VOTE-1936: PX design updates - Basic Page

---

web/themes/custom/votegov/templates/navigation/menu--footer.html.twig

[Vote-2059](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-2059#)
adding back 2 data-test attributes that were removed to fix footer test
n/a
1. cd into `testing` and run `npm run cy:backEnd` and verify that tests are passing

Vote-2059: Adding back data-test attributes to footer

---

web/themes/custom/votegov/src/sass/components/sidebar.scss

no ticket / quick fix
Gives sidebar a minimum width
1. npm run build

Quick fix to sidebar

---

testing/package-lock.json
testing/package.json
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

[Vote-2024](https://cm-jira.usa.gov/browse/VOTE-2024)
Updating Cypress to 13.11.0 - [Link to changelog](https://docs.cypress.io/guides/references/changelog#13-10-0): closes out https://github.com/usagov/vote-gov-drupal/pull/724
Updating USWDS to 3.8.1 - [Link to changelong](https://github.com/uswds/uswds/releases) closes out https://github.com/usagov/vote-gov-drupal/pull/738
- note: there were a few updates to components that we use but seem to be minor and after review did not cause any issues or regressions 
1. cd into `testing` and run `npm install`
2. cd into `votegov` theme and run `npm install`
1. while in `testing` npm the follow scripts `npm run cy:frontEnd`, `npm run cy:backEnd` and `npm run cy:open` - this will open the runner and can run single testing to ensure all are passing …

Vote-2024: Cypress and USWDS Updates

---

.circleci/config.yml

[Vote-2072](https://cm-jira.usa.gov/browse/VOTE-2072)
Updating the config for circle to run cypress with no fails
n/a
1. check this [run with updated code](https://app.circleci.com/pipelines/github/usagov/vote-gov-drupal/84030/workflows/b91d1f74-6f7e-45b5-9ace-7a1ceff8a272/jobs/89659) and check that the tests are running with out the cloudfoundry dependencies step. (please note that i have removed the axe step until the fixes are done so that way we can have a baseline for passing

Vote-2072: Pipeline update for cypress run

---

config/sync/core.entity_view_display.node.voter_guide.full.yml

https://cm-jira.usa.gov/browse/VOTE-2055
Remove image from voter guide full display.
1. login and visit http://vote-gov.lndo.site/voting-college-student
2. Add an image and save
3. view the page and confirm that the image only displays in the hero area.

VOTE-2055 remove image from voter guide field display

---

config/sync/block.block.votegov_footernavigation.yml
config/sync/block.block.votegov_htmlsitemap.yml
config/sync/block.block.votegov_mainnavigation.yml
config/sync/block.block.votegov_mainnavigation_2.yml

[VOTE-2123](https://cm-jira.usa.gov/browse/VOTE-2123)
See commit message
1. visit http://vote-gov.lndo.site/es/mapa-del-sitio
2. confirm that only translated pages show in main menu, in sitemap and in footer (you can create a spanish translation of a page to test)

VOTE-2123 Configure site menus to restrict untranslated pages

---

web/themes/custom/votegov/php-includes/preprocess.inc

https://cm-jira.usa.gov/browse/VOTE-2118
Fix login page error
1. visit http://vote-gov.lndo.site/user/login confirm there is no error and the page loads

VOTE-2118 wrap node query in preprocess in conditional

---

web/themes/custom/votegov/templates/block/block--votegov-languageswitcher.html.twig
web/themes/custom/votegov/templates/block/block-content--basic.html.twig
web/themes/custom/votegov/templates/block/block-content--email-signup.html.twig
web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
web/themes/custom/votegov/templates/block/block-content--inline-alert.html.twig
web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig
web/themes/custom/votegov/templates/block/block-content--search.html.twig
web/themes/custom/votegov/templates/block/block-content--sitewide-alert.html.twig
web/themes/custom/votegov/templates/media/media--document.html.twig
web/themes/custom/votegov/templates/media/media--icon.html.twig
web/themes/custom/votegov/templates/media/media--image.html.twig
web/themes/custom/votegov/templates/media/media--remote-video.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--by-mail.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--in-person.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--online.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig
web/themes/custom/votegov/templates/node/node--voter-guide--teaser.html.twig
web/themes/custom/votegov/templates/node/node.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--accordion-group.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--basic.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--basics-block.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--feature-cards.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--image-text-cta.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--quicklinks.html.twig
web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
web/themes/custom/votegov/templates/taxonomy/taxonomy-term--basics-modules.html.twig

https://cm-jira.usa.gov/browse/VOTE-1179
Update templates to improve cachability
1. Visit one of each page type and confirm there are no display issues or twig errors:
http://vote-gov.lndo.site/
http://vote-gov.lndo.site/legacy
http://vote-gov.lndo.site/register
http://vote-gov.lndo.site/register/alabama
http://vote-gov.lndo.site/about-us
http://vote-gov.lndo.site/voting-college-student

VOTE-1179 update templates to improve cachability

---

.lando.yml
composer.lock

https://cm-jira.usa.gov/browse/VOTE-902
Resolves security vulnerability with composer/composer
1. remove `vendor` directory
3. run `lando rebuild`
1. visit the site and make sure it loads,
2. run `lando composer audit` to make sure there is no security vulnerabilities

VOTE-902 update composer/composer to 2.7.7

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-form.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-header.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-search.scss
web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig

[VOTE-2188](https://cm-jira.usa.gov/browse/VOTE-2188)
Optimize the main menu styles for scalability and ease of maintenance.
1. visit http://vote-gov.lndo.site/ and test main menu on desktop and mobile

VOTE-2188 Main menu style refinements

---

web/themes/custom/votegov/src/sass/base/typography.scss

[Vote-2108](https://cm-jira.usa.gov/browse/VOTE-2108)
Update to copy styles across the site for consistency.  Updating all headers to be `merriweather` and all body copy to be `roboto`
1. run `lando retune` cd into the `votegov` theme and run `npm run build`
1. visit a voter guide page and inspect headers and body copy and verify that the correct styles are being applied.

Vote-2108: Copy style updates

---

web/themes/custom/votegov/templates/views/views-view--voter-guides--embed-1.html.twig

[VOTE-2176](https://cm-jira.usa.gov/browse/VOTE-2176)
Update heading string for voter guide listing section on voter guides pages
1. visit http://vote-gov.lndo.site/voting-college-student and confirm the heading was updated according to the ticket

VOTE-2176 Update voter guide listing heading on voter guide pages

---

testing/package-lock.json
testing/package.json

[Vote-2158](https://cm-jira.usa.gov/browse/VOTE-2158)
Updates to Cypress from Depdabot. 
Closed out the following prs: 
- https://github.com/usagov/vote-gov-drupal/pull/781
- https://github.com/usagov/vote-gov-drupal/pull/771
- https://github.com/usagov/vote-gov-drupal/pull/768
1. cd into `testing` and run `npm i`
1. while in testing run the following commands `npm run cy:frontEnd`, `npm run cy:backEnd` and can run `npm run cy:open` and check that the runner is working - expected behavior is that no tests should fail or issues with running

Vote-2158: Cypress Updates

---

web/themes/custom/votegov/src/sass/_uswds-settings.scss
web/themes/custom/votegov/src/sass/_variables.scss
web/themes/custom/votegov/src/sass/base/typography.scss
web/themes/custom/votegov/src/sass/components/eacgov-partner.scss
web/themes/custom/votegov/src/sass/components/heading.scss
web/themes/custom/votegov/src/sass/components/hero.scss
web/themes/custom/votegov/src/sass/components/quick-links.scss
web/themes/custom/votegov/src/sass/uswds-overrides/_index.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-card.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-identifier.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-site-alert.scss

[VOTE-2111](https://cm-jira.usa.gov/browse/VOTE-2111)
[VOTE-2120](https://cm-jira.usa.gov/browse/VOTE-2120)
[VOTE-2109](https://cm-jira.usa.gov/browse/VOTE-2109)
[VOTE-2119](https://cm-jira.usa.gov/browse/VOTE-2119)
This PR includes high contrast updates for homepage that includes header, banner, hero, quicklinks, feature cards, identifier, email signup, partnership/socials, partner links.
3. visit landing page and toggle high contrast mode
4. compare to figma design https://www.figma.com/design/u82ICmmHNBKpE1Tw4nsO0K/Vote.gov-Redesign-2024-(Master)?node-id=9682-34033&m=dev

VOTE-2006: PX High Contrast Homepage

---

config/local/config_split.patch.language.entity.am.yml
config/sync/language.entity.am.yml

[VOTE-2204](https://cm-jira.usa.gov/browse/VOTE-2204)
Enabling the Amharic language option via the local configuration. Amharic now appears as an option on the language selection menu:
1. Run `lando retune` in the root directory
1. Visit [http://vote-gov.lndo.site/](http://vote-gov.lndo.site/)
2. Click the red "Select your state or territory to begin" button
3. Select a state from the list on the right side of the screen
4. On the state page, click the "Select language" button in the upper right corner. Ensure that Amharic appears as one of the options
5. Select the Amharic option, and check that the current page has been successfully translated
Example:

Enable Amharic language option

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss

[VOTE-2170](https://cm-jira.usa.gov/browse/VOTE-2170)
Fixed the alignment of gov't banner for mobile
1. load up the local site.
2. go into mobile-screen mode through Inspect-Element.
3. Scroll to the very top.
4. Verify that the vertical spacing of the text inside the banner is evenly distributed.

VOTE-2170: Fixed the alignment of gov't banner for mobile

---

web/themes/custom/votegov/templates/component/eacgov-partner.html.twig

[VOTE-2203](https://cm-jira.usa.gov/browse/VOTE-2224)
Removed “Follow vote.gov on X” from footer.
1. load up the local site
2. scroll to the footer
3. Verify that the "Follow vote.gov on X" link is NOT present.

VOTE-2224: Removed Twitter(X) link from footer

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-sign-up.scss

[VOTE-2190](https://cm-jira.usa.gov/browse/VOTE-2190)
Fixed styling for email signup button on Safari (mobile + desktop).
1. Load up the local site on Safari on iPhone
2. Turn to landscape mode and scroll down
3. Verify that the email signup button is in line with the input text field
4. Do the same for Safari on Desktop.
- [] QA/Test steps were successfully completed, if applicable.
- [] Applicable logs are free of errors.

VOTE-2190: Fixed styling for email signup button on Safari

---

testing/pipeline.config.js

Updating pipeline config to point to ssg-stage and not beta 
n/a
1. verify that pipeline.config.js is now points to ss-stage for the base url

Hotfix: adding ssg over beta for pipeline runs

---

.circleci/config.yml

[Vote-2256](https://cm-jira.usa.gov/browse/VOTE-2256)
Adding Cypress Axe testing back to pipeline run for Stage 
n/a
1. Check that cypress axe tests are no longer commented out

Vote-2256: Adding Axe back to stage testing

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-button.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-identifier.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss

[VOTE-2166](https://cm-jira.usa.gov/browse/VOTE-2166)
Fixes styling issues for RTL languages for:
- footer
- buttons
- breadcrumb
- mobile nav menu
2. npm run build in theme directory
3. Navigate to http://vote-gov.lndo.site/ar/register/alaska
4. Confirm these issues are resolved:
- mobile menu: [VOTE-2169](https://cm-jira.usa.gov/browse/VOTE-2169)
- breadcrumb: [VOTE-2168](https://cm-jira.usa.gov/browse/VOTE-2168)
- buttons *the sign up button on mobile screen sizes and the NVRF download button: [VOTE-2167](https://cm-jira.usa.gov/browse/VOTE-2167)
- footer: [VOTE-2166](https://cm-jira.usa.gov/browse/VOTE-2166)

VOTE-2166: RTL styles

---

config/production/config_split.patch.language.entity.am.yml

https://cm-jira.usa.gov/browse/VOTE-2280
Enable Amharic on production.
1. update your settings.local.php to use "production" split
1. visit http://vote-gov.lndo.site/
2. confirm that you can see Amharic in the language selector dropdown

VOTE-2280 remove production override of am configuration

---

config/sync/field.field.node.state_territory.field_media.yml
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/components/page-masthead.scss
web/themes/custom/votegov/src/sass/mixins/mixins.scss
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

https://cm-jira.usa.gov/browse/VOTE-2291
Fix the image proportions on state and basic page primary image display.
1. run `npm run build` in votegov theme directory
1. log into the site and visit http://vote-gov.lndo.site/about-us
2. Upload an image and test the display of the image at desktop, tablet and mobile in LTR and RTL.
3. visit http://vote-gov.lndo.site/register/alabama
4. Upload an image and test the display of the image at desktop, tablet and mobile in LTR and RTL.

VOTE-2291 fix primary image proportions on state and basic page

---

web/themes/custom/votegov/src/sass/components/a11y-toolbar.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-identifier.scss
web/themes/custom/votegov/templates/component/usa-identifier.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig

[VOTE-2269](https://cm-jira.usa.gov/browse/VOTE-2269)
Implements a temporary solution to solve the issue of overlapping accessibility buttons on mobile.
3. Visit any page on mobile size screen
4. Confirm new styles follows this prototype: 
https://www.figma.com/proto/u82ICmmHNBKpE1Tw4nsO0K/Vote.gov-Redesign-2024-(Master)?page-id=10329%3A4177&node-id=11287-7308&viewport=-83%2C-9142%2C0.52&t=p93ZuIcXwkMKo5gx-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=11287%3A7308&show-proto-sidebar=1
Before:
Now:

VOTE-2269: Add space for mobile accessibility controls

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss

[VOTE-2297](https://cm-jira.usa.gov/browse/VOTE-2297)
Fixes spacing issue with banner accordion button
3. before and after:

VOTE-2297: RTL banner style adjustment

---

web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
web/themes/custom/votegov/templates/layout/html.html.twig

[Vote-1143](https://cm-jira.usa.gov/browse/VOTE-1143) and [Vote-2252]([VOTE-2252](https://cm-jira.usa.gov/browse/VOTE-2252))
Updates to mark up to address Lighthouse Performance issues
- Removes lazy load 
- adds a preconnect to hit google tag manger 
1. Open devtools and run lighthouse and check that the errors `Preconnect to required origins` and `Largest Contentful Paint image was lazily loaded` are no longer being flagged.  Please note there are others but they have been ticketed out and are being addressed

Lighthouse Performance Updates

---

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
web/themes/custom/votegov/templates/node/node--teaser.html.twig
web/themes/custom/votegov/templates/node/node--voter-guide--teaser.html.twig

https://cm-jira.usa.gov/browse/VOTE-2271
Replace <article> element for detail page nodes
1. visit http://vote-gov.lndo.site/ and confirm the the article tag is not wrapping the paragraphs content
2. visit http://vote-gov.lndo.site/guide-to-voting/college-student and confirm that the article tag ia not wrapping the voter guide content

VOTE-2271 landmark updates for node templates

---

web/modules/custom/vote_utility/translations/es.po
web/themes/custom/votegov/templates/component/usagov-partner.html.twig

[VOTE-2373](https://cm-jira.usa.gov/browse/VOTE-2373)
Updates english string to:
Visit our partner site to find more information about voting in the United States. 
Updates spanish string to:
Visite el sitio web de nuestro colaborador para encontrar más información sobre las elecciones en Estados Unidos.
2. Confirm English string on footer
3. Switch to Spanish and confirm translation

VOTE-2373: Update partner string in footer - EN/ES

---

config/sync/user.role.content_translator.yml
config/sync/views.view.global_blocks.yml
config/sync/views.view.site_alerts.yml
web/modules/custom/vote_utility/inc/form_alter.inc
web/modules/custom/vote_utility/translations/es.po
web/themes/custom/votegov/src/sass/mixins/mixins.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss
web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss
web/themes/custom/votegov/templates/component/usagov-partner.html.twig

https://cm-jira.usa.gov/browse/VOTE-2385

Sprint 63 release candidate additions

---

web/modules/custom/vote_utility/translations/es.po
web/themes/custom/votegov/templates/component/eacgov-partner.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig
web/themes/custom/votegov/templates/navigation/menu--footer.html.twig
web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[Vote-2372](https://cm-jira.usa.gov/browse/VOTE-2372)
Updating strings for Spanish translations and adjusting a few english stings as well to match what was within the spreadsheet
[Link to spread sheet](https://docs.google.com/spreadsheets/d/14sotXLgJDF3hMxTncKjO-2lKSXIS51QM/edit?gid=886971717#gid=886971717) all rows that are highlighted green have been updated, red is not needed and orange is a task for content that will be ticketed out. 
1. run `lando retune` and cd into `votegov` theme and run `npm run build`
1. verify updates are made to match spreadsheet and spot check locally under the Spanish translation to ensure updates are made

Vote-2372: String Translations -> Spanish

---

web/modules/custom/vote_utility/translations/es.po

https://cm-jira.usa.gov/browse/VOTE-2369
1. Update the es.po to include the strings linked in the Jira ticket
2. Fix hardcoded Spanish translation for the North Dakota page (no registration)
1. Visit http://vote-gov.lndo.site/es/registrar/alaska and confirm the translation strings are properly applying, and that the link works.
2. Visit http://vote-gov.lndo.site/es/registrar/north-dakota and confirm the translation has "North Dakota" instead of "Virginia"

VOTE-2369 State page spanish translation updates

---

testing/cypress/e2e/backEndTests/basic-page.cy.js
testing/cypress/e2e/backEndTests/content-editor-access.cy.js
testing/cypress/e2e/backEndTests/content-manager-access.cy.js
testing/cypress/e2e/backEndTests/footer-menu-editor.cy.js
testing/cypress/e2e/backEndTests/site-admin-access.cy.js
testing/package-lock.json
testing/package.json

[VOTE-2195](https://cm-jira.usa.gov/browse/VOTE-2195)
Updating Cypress to next version will close out this PR ->https://github.com/usagov/vote-gov-drupal/pull/825
Also updating tests to move role based testing into that roles test and address an update in the footer menu. 
1. cd into `testing` and run `npm i`
1. run `npm run cy:frontEnd` and `npm run cy:backEnd` and verify that tests are passing can also run `npm run cy:open` and verify that runner is working as expected

Vote-2195: Cypress version and test updates

---

web/themes/custom/votegov/templates/component/feature-cards.html.twig

https://cm-jira.usa.gov/browse/VOTE-2429
Adds external link class to the hardcoded feature card for Military and Overseas. 
*had to wrap the body text in a paragraph card to solve a spacing issue. this was easier than overriding uswds styling since this is a temporary fix
3. visit homepage and find the feature cards
4. confirm the Military and Overseas uses an external link icon at the end of the body text

VOTE-2429: Add external link class to Military and Overseas card

---

web/themes/custom/votegov/templates/media/image.html.twig

[VOTE-2424](https://cm-jira.usa.gov/browse/VOTE-2424)
Removes lazy loading from hero image to solve lighthouse issue
2. visit home page and inspect hero image
3. confirm lazy loading is no longer applied to hero image
4. run lighthouse test and confirm issue is satisfied

VOTE-2424: removes lazy loading from hero image

---

web/modules/custom/vote_utility/translations/es.po

[Vote-2477](https://cm-jira.usa.gov/browse/VOTE-2477)
Adding Spanish translation for `Know your voting rights` header above feature cards
1. scroll to the voter cards on the home page while on Spanish and verify that translation is present, also verify on voter guides

Vote-2477: Adding Translation for Feature Card header

---

web/modules/custom/vote_utility/translations/es.po

https://cm-jira.usa.gov/browse/VOTE-2433
Add a Spanish translation for the Secondary navigation aria-label
1. Switch to Spanish on the homepage
2. Run WAVE accessibility tools and/or NVDA
3. Scroll down to the footer and confirm the aria label for the footer menu is in Spanish

VOTE-2433 Add Spanish translation for secondary nav aria label

---

web/robots.txt

[VOTE-2485](https://cm-jira.usa.gov/browse/VOTE-2485)
Updates robots.txt file for search.gov testing
1. Insert steps to test and confirm the result meets the "definition of done".

HOTFIX VOTE-2485: Update robots.txt file

---

web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/votegov/templates/node/node--state-territory--by-mail.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--in-person.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--online.html.twig

https://cm-jira.usa.gov/browse/VOTE-2444
Update the main state page header in English and Spanish.
1. View http://vote-gov.lndo.site/register/colorado
2. Confirm the main header is updated to the following:
3. Switch to Spanish, and confirm the main header is updated to the following:
Note: You will see the other language .po files have the english translation but the string in that language is not update. This will be updated as other translations are updated on the site as a whole.

VOTE-2444 start or update registration copy change

---

config/local/config_split.patch.language.entity.so.yml
config/production/config_split.patch.language.entity.so.yml

[VOTE-2324](https://cm-jira.usa.gov/browse/VOTE-2324)
Enable Somali translation on production.
1. Update the following setting in web/sites/settings.local.php file to include or reflect
`$config['config_split.config_split.production']['status'] = TRUE;`
2. Run `lando retune` or `lando drush cim` to import the production configurations.
1. Login as an administrator
2. Goto /admin/config/regional/language and confirm that Somali is not marked as disabled.
3. Goto the content admin page and identify any page that has been translated in Somali.
4. View the translated page and confirm that the language selector button in the top right corner of the page includes Somali as an option.
5. Logout and repeat Step 4.

VOTE-2324: Enable Somali for production.

---

config/local/config_split.patch.language.entity.so.yml
config/sync/language/am/easy_breadcrumb.settings.yml
config/sync/language/ar/easy_breadcrumb.settings.yml
config/sync/language/bn/easy_breadcrumb.settings.yml
config/sync/language/es/block.block.claro_primary_local_tasks.yml
config/sync/language/es/block.block.claro_secondary_local_tasks.yml
config/sync/language/es/easy_breadcrumb.settings.yml
config/sync/language/fr/easy_breadcrumb.settings.yml
config/sync/language/hi/easy_breadcrumb.settings.yml
config/sync/language/ht/easy_breadcrumb.settings.yml
config/sync/language/km/easy_breadcrumb.settings.yml
config/sync/language/ko/easy_breadcrumb.settings.yml
config/sync/language/nv/easy_breadcrumb.settings.yml
config/sync/language/pt/easy_breadcrumb.settings.yml
config/sync/language/ru/easy_breadcrumb.settings.yml
config/sync/language/so/easy_breadcrumb.settings.yml
config/sync/language/tl/easy_breadcrumb.settings.yml
config/sync/language/vi/easy_breadcrumb.settings.yml
config/sync/language/ypk/easy_breadcrumb.settings.yml
config/sync/language/zh-hans/easy_breadcrumb.settings.yml
config/sync/language/zh/easy_breadcrumb.settings.yml
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po

https://cm-jira.usa.gov/browse/VOTE-2490
Home translations sync
1. visit http://vote-gov.lndo.site/es/registrar and confirm the homepage breadcrumb is translated

VOTE-2490 add config translations for home label

---

web/modules/custom/vote_utility/translations/es.po
web/themes/custom/votegov/templates/component/feature-cards.html.twig

https://cm-jira.usa.gov/browse/VOTE-2505
Update the FVAP voter card hardcoded content
1. View the voter card group on the homepage in English an confirm they match the screenshots in the ticket
2. Switch to spanish and confirm the spanish content
3. Repeat on the voter guide page

VOTE-2505 Add (FVAP) back into voter cards

---

web/themes/custom/votegov/templates/layout/maintenance-page.html.twig

https://cm-jira.usa.gov/browse/VOTE-2241
Configure a minimal maintenance page
1. visit http://vote-gov.lndo.site/admin/config/development/maintenance and put site in maintenance mode. Log out and admire the maintenance page.

VOTE-2241 configure a minimal maintenance page template

---

testing/cypress/fixtures/axe-pages.json
web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po
web/themes/custom/votegov/templates/node/node--state-territory--by-mail.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--in-person.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--online.html.twig

https://cm-jira.usa.gov/browse/VOTE-2512
1. Revert VOTE-2444 (incorrectly applied the copy change)
2. Apply the new copy "Start or update your registration" to the link text in English and Spanish
1. Visit the Colorado state page
2. Confirm the first heading text has been reverted (see ticket for copy)
3. Confirm the link text has the applied copy change (see ticket for copy)
4. Switch to Spanish and repeat steps 2 and 3
5. Confirm all other languages translate (copy to be updated in future tickets)

Hotfix--VOTE-2512 state page hardcoded content

---

web/themes/custom/votegov/templates/node/node--state-territory--by-mail.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--in-person.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig
web/themes/custom/votegov/templates/node/node--state-territory--online.html.twig

1. visit http://vote-gov.lndo.site/register/arkansas view page source and search for `https://schema.org` make sure there are no results

HOTFIX: Disable FAQ JSON schema on state pages

---

scripts/upkeep

[VOTE-2511](https://cm-jira.usa.gov/browse/VOTE-2511)
Remove robots.txt from being included in the upkeep script.
1. Allow deploy to happen.
2. Check that post deploy upkeep and further scheduled upkeeps are able to run.

VOTE-2511: remove robots.txt from the upkeep copy

---

config/sync/field.field.node.voter_guide.field_media.yml

https://cm-jira.usa.gov/browse/VOTE-2513
Disable translation on voter guide image field
1. visit http://vote-gov.lndo.site/es/node/82/edit and confirm there is no image field in the edit form
2. visit http://vote-gov.lndo.site/node/82/edit update the image and save
3. visit http://vote-gov.lndo.site/guide-to-voting/college-student and confirm the new image displays
4. visit http://vote-gov.lndo.site/es/guide-to-voting/college-student and confirm the new image displays

VOTE-2513 Disable translation on voter guide image field

---

config/sync/views.view.nvrf_api.yml
config/sync/views.view.nvrf_api_blocks.yml
config/sync/views.view.nvrf_api_taxonomy.yml

https://cm-jira.usa.gov/browse/VOTE-2239
Update access for api Views so they are generated by Tome.
1. log out of the site and visit the api pages. Make sure that you can access all 4 of them.

VOTE-2239 Update access to api paths

---

scripts/pipeline/cloud-gov-post-deploy-upkeep.sh

[VOTE-2497](https://cm-jira.usa.gov/browse/VOTE-2497)
Add the environment variable to post deploy upkeep that's used for scheduled upkeeps.
1. Allow deploy and post deploy steps to run in the pipeline.
2. Check that the static site's assets have the correct URI.

VOTE-2497: add environment variable to command running post deploy upkeep

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss

[VOTE-2518](https://cm-jira.usa.gov/browse/VOTE-2518)
Excluded navajo font from language selection.
1. Load up the local site
2. Open up the language selector dropdown
3. Click on Dine (Navajo)
4. Verify that the strings look normal (shown below) and no special characters
- [] QA/Test steps were successfully completed, if applicable.
- [] Applicable logs are free of errors.

VOTE-2518: Excluded navajo font from language selection

---

composer.lock

[VOTE-2419](https://cm-jira.usa.gov/browse/VOTE-2419)
Update contributed modules. You can review the ticket comments for the list of updated modules.
1. Locally, run `lando retune` to install updates.
1. Confirm that site is still operational. The updates to modules are primarily for Drupal 11 support so there isn't much to test.

VOTE-2419: Update drupal modules.

---

testing/cypress/e2e/backEndTests/basic-page.cy.js
testing/cypress/e2e/backEndTests/content-editor-access.cy.js
testing/cypress/e2e/backEndTests/user-content-access.cy.js

Hotfix
Update to cypress backend tests after updates were made
1. cd into `testing` and run `lando retune`
1. while in `testing` run `npm run cy:backEnd` and verify that backend tests are passing

Hotfix cypress

---

web/themes/custom/votegov/templates/node/node--state-territory--online.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[VOTE-2591](https://cm-jira.usa.gov/browse/VOTE-2591)
Edited state-page texts:
"Start or update your registration online"
"Voter registration deadlines are for the Tuesday, November 5, 2024 election."
1. Load up the local site
2. Go to any registeration page (i.e. `http://localhost:65492/register/alabama`)
3. Verify that these two sentences exist:
"Start or update your registration online" (the word 'online' is present)
"Voter registration deadlines are for the Tuesday, November 5, 2024 election." (the word 'are' is present)
- [] QA/Test steps were successfully …

VOTE-2591: Edited state-page texts

---

config/local/config_split.patch.core.extension.yml

[Vote-1124](https://cm-jira.usa.gov/browse/VOTE-1124)
Installed a module for responsive image to help address lighthouse errors 
1. run lando retune 
1. load up local and open the console and run a mobile check light house.  Should expect to not see the error `properly size images`

Vote-1124: Add responsive image module to address lighthouse errors

---

config/non_production/views.view.samlauth_map.yml
config/non_production/views.view.watchdog.yml
config/production/views.view.samlauth_map.yml

[VOTE-2498](https://cm-jira.usa.gov/browse/VOTE-2498)
Update config exports to capture missing config settings.
1. Locally run `lando retune`
1. Login as an administrator
2. Update your settings.local.php file to reflect each of the following and one at a time then proceed with steps 3-4 for each setting change:
`$config['config_split.config_split.local']['status'] = TRUE;`
`$config['config_split.config_split.non_production']['status'] = TRUE;`
`$config['config_split.config_split.production']['status'] = TRUE;`
3. Run `lando drush cim` to import configs
4. Visit /admin/config/development/configuration and confirm there are no configurations that are different.

VOTE-2498: Add missing view pagination heading size config entries.

---

config/sync/core.entity_view_display.media.icon.default.yml

https://cm-jira.usa.gov/browse/VOTE-2762
Set an image style for the default display of the icon media type
1. visit http://vote-gov.lndo.site/ and make sure the icon display as expected
2. visit http://vote-gov.lndo.site/admin/reports/status and make sure the warning about the icon media type is gone

VOTE-2762 update media display of icon type

---

config/sync/core.entity_view_display.node.page.full.yml
web/themes/custom/votegov/src/sass/components/page-content.scss
web/themes/custom/votegov/src/sass/mixins/mixins.scss
web/themes/custom/votegov/templates/layout/page.html.twig
web/themes/custom/votegov/templates/node/node--state-territory.html.twig
web/themes/custom/votegov/templates/node/node.html.twig

[VOTE-2598](https://cm-jira.usa.gov/browse/VOTE-2598)
Implements in the new hero component to the template for state and basic pages.
1. navigate to a state page
2. if there is no image on the page edit page and upload an image
3. confirm hero shows correct page title, breadcrumbs, and image
4. navigate to a basic page and repeat steps

VOTE-2598: Implement hero component to state/basic template

---

scripts/upkeep
web/modules/custom/ec_placeholder/src/Plugin/EmbeddedContent/ECPlaceholder.php
web/modules/custom/ec_touchpoints_survey/src/Plugin/EmbeddedContent/TouchpointsSurvey.php
web/modules/custom/ec_uswds/src/Plugin/EmbeddedContent/ECUsaAlert.php

https://cm-jira.usa.gov/browse/VOTE-2766
Copy nvrf data files to s3.
1. files in `data` directory are copied to s3

VOTE-2766 update upkeep script to copy nvrf data files

---

scripts/upkeep
web/modules/custom/ec_placeholder/src/Plugin/EmbeddedContent/ECPlaceholder.php
web/modules/custom/ec_touchpoints_survey/src/Plugin/EmbeddedContent/TouchpointsSurvey.php
web/modules/custom/ec_uswds/src/Plugin/EmbeddedContent/ECUsaAlert.php

VOTE-2766 update upkeep script to copy nvrf data files (#954)

---

scripts/upkeep

[VOTE-2534](https://cm-jira.usa.gov/browse/VOTE-2534) - Previous sprint ticket
Revert changes to sync files from static site before running tome for additional testing.
n/a
n/a

VOTE-2534: Revert upkeep changes to sync files from static site.

---

.circleci/config.yml

[Vote-2747](https://cm-jira.usa.gov/browse/VOTE-2747)
Updating PHP and Cypress version within the circleci config file. 
- PHP was updated to 8.3 
- Cypress was updated to run with the latest version [documentation on latest version docker image](https://hub.docker.com/layers/cypress/included/latest/images/sha256-780e892b19c94cf807e81aa27cd20b6a7cdae6c030ef15ac8c98f80c5349f6ef?context=explore)
- **Benefits on using latest** -> Will always run the most updated version of cypess and will allow us to not become behind. 
- **Cons on using latest** -> Will be a chance that local and pipeline version will be our of sync... however this could help flag any issues a new version might cause us in the future
n/a
1. review file changes and verify that PHP and Cypress has been updated
2. Test run …

Vote-2747: update cypress and php in circleci

---

web/themes/custom/votegov/templates/component/feature-cards.html.twig

[VOTE-2588](https://cm-jira.usa.gov/browse/VOTE-2588)
Gives feature card component a unique id 
2. inspect page
3. find feature card heading
4. confirm id is know-your-voting-rights

VOTE-2588: add id to feature card component heading

---

web/modules/custom/vote_utility/translations/fr.po

[Vote-2655](https://cm-jira.usa.gov/browse/VOTE-2655)
Updating hard coded strings for French  
1. run `lando retune` in import new translations 
1. Review spreadsheet in ticket and verify all updates are made and spot check site as well.

Vote-2655: French Updated Strings

---

config/sync/field.field.node.state_territory.field_pdf_pages.yml

https://cm-jira.usa.gov/browse/VOTE-2796
Make the "NVRF PDF pages" field translatable so it can be unique across languages.
1. Login as admin
2. Visit http://vote-gov.lndo.site/es/node/56/edit?destination=/admin/content and confirm the NVRF PDF pages field is there

VOTE-2797 Make the field NVRF PDF pages translatable

---

scripts/pipeline/deb-basic-deps.sh

testing vote-2844

---

composer.lock

[VOTE-2839](https://cm-jira.usa.gov/browse/VOTE-2839) - Drupal core updates
[VOTE-2820](https://cm-jira.usa.gov/browse/VOTE-2820) - Snyk Error
Resolve snyk error regarding twig/twig by updating drupal core and its dependencies.
1. locally run 'lando retune'
1. Locally run `lando composer audit` and confirm no messages regarding twig appears.
2. Login to site as an admin and goto status page and confirm drupal core is 10.3.5.

VOTE-2820/VOTE-2839: Update drupal core and dependencies.

---

scripts/pipeline/deb-basic-deps.sh
scripts/pipeline/deb-cf-install.sh

[VOTE-2844](https://cm-jira.usa.gov/browse/VOTE-2844)
Change from apt repository to binary install for CF CLI.
1. Ensure the "Install cloudfoundry dependencies" step of the deploy workflow runs successfully.

VOTE-2844: Change CF CLI from apt repository to binary install

---

testing/cypress/e2e/accessibility/axe.cy.js

[Vote-2827](https://cm-jira.usa.gov/browse/VOTE-2827)
Migrate axe tests to utilize page objects 
1. n/a
1. cd into `testing` and run `npm run cy:axe`

Vote-2827: Migrate axe test to utlitize page objects

---

web/modules/custom/vote_utility/translations/ht.po
web/themes/custom/votegov/templates/component/feature-cards.html.twig

[VOTE-2664](https://cm-jira.usa.gov/browse/VOTE-2664)
Updates the hard coded strings for HT
2. compare updated strings to ticket and google doc

VOTE-2664: update hard coded strings for Haitian Creole

---

web/modules/custom/vote_utility/translations/fr.po

[Vote-2823](https://cm-jira.usa.gov/browse/VOTE-2823)
Updating the temporary voter card guide strings for French translations
1. visit home page and select the french translation options and verify that the 2 voter guide cards have been translated

Vote-2823: Temp Voter Card French Translations

---

web/modules/custom/vote_utility/translations/am.po
web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/bn.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/hi.po
web/modules/custom/vote_utility/translations/ht.po
web/modules/custom/vote_utility/translations/ja.po
web/modules/custom/vote_utility/translations/km.po
web/modules/custom/vote_utility/translations/ko.po
web/modules/custom/vote_utility/translations/nv.po
web/modules/custom/vote_utility/translations/pt.po
web/modules/custom/vote_utility/translations/ru.po
web/modules/custom/vote_utility/translations/so.po
web/modules/custom/vote_utility/translations/tl.po
web/modules/custom/vote_utility/translations/vi.po
web/modules/custom/vote_utility/translations/ypk.po
web/modules/custom/vote_utility/translations/zh-hans.po
web/modules/custom/vote_utility/translations/zh.po

[Vote-2840](https://cm-jira.usa.gov/browse/VOTE-2840)
Updating English string to add `online` to address translation bug
1. review file changes and confirm that `online` had been added to the end of the string 
2. visit a state page and verify that translation are happening for this string

Vote-2840: English String Update

---

web/modules/custom/vote_utility/translations/fr.po

https://cm-jira.usa.gov/browse/VOTE-2823
Adding string translation for `Know your voting rights`
1. Verify translation is added

Vote-2823: Know your voting rights French update

---

web/modules/custom/vote_utility/translations/ar.po
web/modules/custom/vote_utility/translations/es.po
web/modules/custom/vote_utility/translations/fr.po
web/modules/custom/vote_utility/translations/ht.po

https://cm-jira.usa.gov/browse/VOTE-2908
Remove string translations "Primary tabs" and "Secondary tabs"
1. Grab the latest DB backup and import
2. `lando retune`
1. visit http://vote-gov.lndo.site/admin/config/development/configuration
3. Confirm there are no unsynced config

VOTE-2908 remove unused string translations

---

docs/devops.md

[VOTE-2535](https://cm-jira.usa.gov/browse/VOTE-2535)
Update documentation for how to pause the upkeep workflow.
1. Test the steps included in the devops.md file under the `upkeep-workflow` section

VOTE-2535: include documentation for how to manually pause the upkeep workflow

---

web/modules/custom/vote_utility/translations/pt.po

[VOTE-2634](https://cm-jira.usa.gov/browse/VOTE-2634)
Adds the hardcoded strings for Portuguese. 
1. Compare string changes to the google doc
*note that the doc is highlighted in red for the ones that can't be done here AND we are not adding the military/overseas strings since we don't have the translation

VOTE-2661: Hard coded strings Portuguese

---

web/themes/custom/votegov/templates/node/node--state-territory.html.twig

https://cm-jira.usa.gov/browse/VOTE-2882
Adjust the fallback variables to prevent errors for missing arrays when there is no default state display content.

VOTE-2882 refine fallbacks for the state display content

---

web/modules/custom/vote_utility/translations/zh-hans.po

[VOTE-2634](https://cm-jira.usa.gov/browse/VOTE-2634)
Adds the hardcoded strings for Chinese Simplified. 
1. Compare string changes to the google doc
*note that the doc is highlighted in red for the ones that can't be done here AND we are not adding the military/overseas strings since we don't have the translation

VOTE-2634: Hard coded string content Chinese Simplified

---

config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.full.yml
config/sync/core.entity_view_display.node.state_territory.teaser.yml
config/sync/field.field.node.state_territory.field_nvrf_details.yml
config/sync/field.storage.node.field_nvrf_details.yml
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

[Vote-2978](https://cm-jira.usa.gov/browse/VOTE-2978)
Adding config for an override field for NVRF details. 
Also adding some minor code clean up based on review 
1. visit a state page such as `Alabama` and edit page, go to the State Display Content tab and scroll to the `NVRF Details Override` and add content to this field. 
2. Can also make a new state display content block to check that the content is override the base content to this field. 
NOTE: you may need to update your block number within the state file to match what is on your local.

Vote-2978: Config for Override NVRF field

---

web/modules/custom/vote_utility/translations/zh-hans.po

[Vote-2979](https://cm-jira.usa.gov/browse/VOTE-2979)
Updates to strings from translator feedback
1. review ticket and ensure that updates are made... will not be on the site due to the translation not being active yet.

Vote-2979: Chinese Simplified String Updates

---

web/modules/custom/vote_utility/translations/pt.po

[Vote-3025](https://cm-jira.usa.gov/browse/VOTE-3025)
Updating pt strings.
1. verify the follow strings have been updated -> `On this page | Nesta página` and`Know your voting rights | Conheça seus direitos de voto`

Vote-3025: Update to PT strings

---

web/modules/custom/vote_utility/translations/hi.po

[Vote-3021](https://cm-jira.usa.gov/browse/VOTE-3021)
Updates to HI strings.
1. verify the following strings are updated - `Visit our partner site to find more information about voting in the United States. | संयुक्त राज्य अमेरिका में मतदान के बारे में अधिक जानकारी प्राप्त करने के लिए हमारी साझेदार साइट पर जाएँ।`, `On this page | इस पेज पर`, `Vote.gov is in partnership withU.S. ELECTION ASSISTANCE COMMISSION | Vote.gov अमेरिकी चुनाव सहायता आयोग के साथ साझेदारी में है`, `Know your voting rights | अपने मतदान अधिकारों को जानें`

Vote-3021: Update to HI strings

---

web/themes/custom/votegov/templates/layout/html.html.twig

https://cm-jira.usa.gov/browse/VOTE-3038
Enable Crazy Egg script for all pages on vote.gov
1. While logged out, visit the homepage
2. Open Chrome dev tools (or another browser equivalent) and go to the network tab
3. Confirm that 9651.js is loading as a resource.

VOTE-3038 Enable crazy egg

---

config/sync/core.entity_form_display.block_content.state_display_content.default.yml
config/sync/core.entity_form_display.node.state_territory.default.yml
config/sync/core.entity_view_display.block_content.state_display_content.default.yml
config/sync/core.entity_view_display.node.state_territory.default.yml
config/sync/core.entity_view_display.node.state_territory.full.yml
config/sync/core.entity_view_display.node.state_territory.teaser.yml
config/sync/field.field.block_content.state_display_content.field_no_mail_registration.yml
config/sync/field.field.block_content.state_display_content.field_no_online_registration.yml
config/sync/field.field.node.state_territory.field_nvrf_details.yml
config/sync/field.field.node.state_territory.field_registration_not_needed.yml
config/sync/field.storage.block_content.field_no_mail_registration.yml
config/sync/field.storage.block_content.field_no_online_registration.yml
config/sync/field.storage.node.field_nvrf_details.yml
web/modules/custom/vote_fields/config/schema/vote_fields.schema.yml
web/modules/custom/vote_fields/src/Plugin/Field/FieldFormatter/StateContentDefaultFormatter.php
web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/StateContentWidget.php

https://cm-jira.usa.gov/browse/VOTE-3052
Transferring data model changes from state-enhancement branch to dev
1. This work has already been reviewed and tested on state-enhancement branch. I think we would want to check to make sure there are no errors when entering in content for state display content block or state override fields
2. Check the display of the state page to make sure there are not changes.

VOTE-3052 Sync state page configuration with state-enhancement

---

web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig

https://cm-jira.usa.gov/browse/VOTE-3036
Adjust markup for in page nav in the voter guide page to match up with styling adjustments made for the state page.
2. cd into theme, npm run build
1. Visit a voter guide page and confirm the spacing and styling matches with the live site.
2. Test multiple device dimensions and browsers for responsiveness.

VOTE-3036 fix voter guide in-page-nav

---

web/themes/custom/votegov/src/sass/components/call-out-box.scss
web/themes/custom/votegov/src/sass/components/date.scss
web/themes/custom/votegov/src/sass/components/info-card.scss
web/themes/custom/votegov/templates/node/node--state-territory.html.twig

https://cm-jira.usa.gov/browse/VOTE-3024
Adjust the election date field styling to match the design.
2. cd into theme, npm run build
1. In the state display content block, set the election date and election data text fields.
2. On a state page, confirm the election date content matches the design. 
3. Test multiple screen sizes for responsiveness and spacing.

VOTE- 3024 fix election date styling

---

web/themes/custom/votegov/templates/component/usa-identifier.html.twig

https://cm-jira.usa.gov/browse/VOTE-3034
Remove empty href link from footer
1. confirm that the GSA logo does not link anywhere

VOTE-3034 clean out empty footer link

---

composer.json
composer.lock

[VOTE-3003](https://cm-jira.usa.gov/browse/VOTE-3003)
Update Drupal core and contributed modules. You can review the ticket comments for the list of updated modules.
1. Locally, run `lando retune` to install updates.
1. Confirm that the site is still operational.
(Based on changes for modules, there isn't anything to test for.)

Feature/VOTE-3003: Drupal core and module updates

---

config/non_production/usagov_login.settings.yml
web/sites/default/settings.cloudgov.php

[VOTE-2981](https://cm-jira.usa.gov/browse/VOTE-2981)
Update single sign on to new GSA Auth.
none
1. Goto /user/login and confirm that you can login successfully.

VOTE-2981: Update pre-prod environments with new saml auth signin urls.

---

scripts/pipeline/downsync-preprod.sh

VOTE-3033 testing

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss

https://cm-jira.usa.gov/browse/VOTE-3092
Adjusted styling for the in page nav component so it works for right-to-left languages.
1. cd into theme, npm run build
1. On the state page, switch the language to Arabic.
2. Confirm the in page navigation margin and padding is correct for multiple screen sizes.
3. Switch back to English and confirm the same.

VOTE-3092 Replace left styles with inline start

---

testing/cypress/e2e/externalLinks/external-links-validator.cy.js

[Vote-2998](https://cm-jira.usa.gov/browse/VOTE-2998)
Adding a url that keeps failing due to time out issues... url is working but need to add it to the list of url to check manually
1. n/a
1. verify that the url in [this run](https://app.circleci.com/pipelines/github/usagov/vote-gov-drupal/99756/workflows/0855b28d-2d5e-42cf-8114-07dd40c2d25c/jobs/107781) has been added to the excluded links array

Vote-2998: Adding url to excluded links

---

config/sync/field.field.paragraph.hero.field_background_color.yml

[Vote-3986](https://cm-jira.usa.gov/browse/VOTE-3086)
Updating label for hero section... a new field name was not created just updating the label for the CMS user to view.
1. Edit the home page and edit the hero section and verify that the new label for hero background color is now `Hero Style`

Vote-3986: Update to hero label

---

manifest.yml

VOTE-3126 testing

---

web/modules/custom/vote_utility/translations/ko.po

https://cm-jira.usa.gov/browse/VOTE-2652
Update hardcoded strings for Korean state page.
2. If necessary - lando import-translations
1. View a state page in Korean and confirm the hardcoded strings have been updated.

VOTE-2652 Update state page strings Korean

---

web/themes/custom/votegov/templates/block/block-content--partnership.html.twig
web/themes/custom/votegov/templates/layout/page--node--vote-nvrf.html.twig

VOTE-3108
Fix regression in NVRF page template
1. visit http://vote-gov.lndo.site/register/alabama/mail-in-form-filler and confirm the page loads
2. visit http://vote-gov.lndo.site/es/registrar/alabama/llenador-de-formulario-por-correo-postal and confirm the page loads

VOTE-3108 resolve regression in nvrf template

---

config/sync/views.view.nvrf_state_reports.yml

https://cm-jira.usa.gov/browse/VOTE-3059
Add state mail-in PDF link to nvrf report page and export.
1. log in and visit http://vote-gov.lndo.site/admin/nvrf-state-report and see there is a new column for state mail-in pdf link
2. visit http://vote-gov.lndo.site/admin/nvrf-state-report/export and check the csv to make sure the state mail-in pdf link data is last column

VOTE-3059 add new field to nvrf report listing and export

---

web/themes/custom/votegov/templates/block/block-content--contact-identifier.html.twig

[Vote-2612](https://cm-jira.usa.gov/browse/VOTE-2612)
Updating Touchpoints survey to the module format after accessibility fix  
n/a
1. Check that the touchpoints is opening in a module and that is its keyboard accessible   
2. Check in mobile view for any regressions

Vote-2612: Update Touchpoints to module

---

testing/package-lock.json
testing/package.json
web/themes/custom/votegov/package-lock.json
web/themes/custom/votegov/package.json

[Vote-3162](https://cm-jira.usa.gov/browse/VOTE-3162)
Dependbot updates for Cypress, Axe-Core and USWDS versions
Closes out: https://github.com/usagov/vote-gov-drupal/pull/1100, https://github.com/usagov/vote-gov-drupal/pull/1078, https://github.com/usagov/vote-gov-drupal/pull/1118 and https://github.com/usagov/vote-gov-drupal/pull/1129
cd into both `testing` and `votegov` folders and run `npm i`
1. While in the `testing` folder run `npm run cy:frontEnd`, `npm run cy:backEnd` and `npm run cy:axe` and verify that test are passing and running with no issues
2. While in `votegov` run `npm run build` and visit the site locally and spot check to ensure there are no regressions.  Also check the NVRF for any regressions (note that one of the updates that might impact is to the step indicator)

Vote-3162: Dependabot updates

---

.circleci/config.yml

vote 2963 testing

---

web/themes/custom/votegov/templates/layout/page--node--vote-nvrf.html.twig
web/themes/custom/votegov/templates/layout/page.html.twig

[VOTE-3169](https://cm-jira.usa.gov/browse/VOTE-3169)
Remove Navajo font from site.
1. Locally run `lando drush cr`
1. Goto /nv and confirm that the Navajo font is not loaded. Confirm also that it doesnt load on NVRF app pages.

VOTE-3169: Remove Navajo style classes from page template.

---

config/production/config_split.patch.language.entity.nv.yml

[VOTE-3121](https://cm-jira.usa.gov/browse/VOTE-3121)
Re-enable Navajo translations on production.
1. n/a
1. Confirm that Navajo translations are enabled on production once deployed.

VOTE-3121: Enable Navajo translations on production.

---

composer.lock

[VOTE-3180](https://cm-jira.usa.gov/browse/VOTE-3180)
Update SVG Image module.
1. Locally run `lando retune`
1. Confirm svg images continue to work (svg image uploading and rendering).

VOTE-3180: Update svg_image module

---

web/themes/custom/votegov/votegov.libraries.yml

Removing the hardcoded VERSION in the libraries file. This could cause caching invalidation issues.
1. Should see no change with the loading of the theme

Remove library version to avoid caching issues

---

scripts/upkeep
web/themes/custom/votegov/votegov.libraries.yml

[VOTE-3181](https://cm-jira.usa.gov/browse/VOTE-3181)
Resolve issues with upkeep script not copying files to destination static site.

Sprint 74: Hotfix candidate release to stage

---

testing/README.md
testing/cypress.config.js
testing/pipeline.config.js

[Vote-3219](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-3219#)
Updating testing docs
n/a
1. Review docs and comments and ensure they are clear

Vote-3219: Update to Testing docs

---

docs/backend.md

[VOTE-2459](https://cm-jira.usa.gov/browse/VOTE-2459)
Update documentation with currently installed contributed modules.
n/a
1. Review documentation in code or locally to confirm formatting and descriptions of modules.

VOTE-2459: Document currently installed contributed modules.

---

docs/devops.md
docs/disasterrecovery.md

[VOTE-2869](https://cm-jira.usa.gov/browse/VOTE-2869)
[VOTE-3058](https://cm-jira.usa.gov/browse/VOTE-3058)
Update documentation for devops and disaster recovery, adding downsync process usage.
1. Ensure documentation for devops and disaster recovery are correct.

VOTE-2869-3058: Update documentation for devops and disaster recovery

---

testing/cypress/e2e/externalLinks/external-links-validator.cy.js

https://cm-jira.usa.gov/browse/VOTE-3309
Add CISA link from voter guide to the excluded external links list.
1. cd into testing folder
2. Run npm run cy:proofer
3. Verify there are no test failures

VOTE-3309 Add CISA link to excluded links list

---

config/non_production/samlauth.authentication.yml
config/production/samlauth.authentication.yml

This resolves a bug with SSO login for site builder role.

Enable SSO login for site builder role

---

scripts/pipeline/cloud-gov-deploy.sh

[VOTE-3346](https://cm-jira.usa.gov/browse/VOTE-3346)
Remove rolling deployments.
1. Allow deployment to happen.
2. Verify that the app is replaced in place without needing double app memory
3.

VOTE-3346: remove rolling deployments

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-card.scss

https://cm-jira.usa.gov/browse/VOTE-3185
Reverts https://github.com/usagov/vote-gov-drupal/pull/1159
1. cd into theme, npm run build
1. Visit the Yup'ik homepage. Confirm the content in the voter cards does not wrap.

VOTE-3209 Remove break word for voter card content

---

.lando.yml

[Insert a link to the Jira ticket (e.g VOTE-XXX).](https://cm-jira.usa.gov/browse/VOTE-3354)
Clean lando.yml of unused services and tooling.
1. `lando rebuild`
1. After rebuild confirm the site is up and running without error.

VOTE-3354: clean lando.yml uf unused services

---

.lando.yml
composer.lock
config/sync/linkit.linkit_profile.default.yml
patches/tome/tomePathCountFixes.patch

[VOTE-3074](https://cm-jira.usa.gov/browse/VOTE-3074)
Resolve tome patch issue.
n/a
1. Run `lando composer install` and confirm that tome patch applies without failing.

VOTE-3074- Update tome patch

---

composer.json
composer.lock

[VOTE-3377](https://cm-jira.usa.gov/browse/VOTE-3377)
Update Drupal core along with other modules. Remove unused ckeditor5_embedded_content module install from composer as cleanup.
1. Login and confirm that site is functional.
2. Confirm that you can login using single sign on.
3. Confirm that core and modules are updated by visiting Available Updates admin page.
4. Review DB Logs and verify that no new errors are being logged.

VOTE-3377: Update drupal core and modules. Remove ckeditor5_embedded_content module.

---

.circleci/config.yml

[VOTE-3360](https://cm-jira.usa.gov/browse/VOTE-3360)
Update cypress images to all be the same image.
1. Allow pipeline to run to stage.
2. Verify that the cypress workflow is able to complete successfully.

VOTE-3360: Update the cypress image version to be the same for all tests

---

docs/devops.md

[VOTE-3365](https://cm-jira.usa.gov/browse/VOTE-3365)
Document how to run upkeep manually via the CLI.
1. Follow the devops docs for running upkeep manually and ensure they succeed.

VOTE-3365: Document how to run upkeep manually via the CLI

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss
web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig

https://cm-jira.usa.gov/browse/VOTE-2267
Remove the bold, padding, and arrow from the parent link in the submenu.
1. cd into theme, npm run build
1. View the menu and confirm the styles are removed from the "Guide to voting" link in the submenu
2. Confirm the link functions as expected and there are no other styling regressions.

VOTE-2267 Remove unique styles from the parent link in the submenu

---

web/themes/custom/votegov/README.md
web/themes/custom/votegov/storybook/README.md

https://cm-jira.usa.gov/browse/VOTE-3414
Add storybook documentation to votegov theme. These documentation md files do not modify any behavior of the application.

VOTE-3414: Add basic storybook documentation

---

web/modules/custom/vote_nvrf/src/Plugin/Field/FieldFormatter/NVRFFieldsJsonFormatter.php
web/modules/custom/vote_nvrf/vote_nvrf.module

[VOTE-628](https://cm-jira.usa.gov/browse/VOTE-628)
Update nodes that use field_nvrf_fields to remove nvrf_field terms upon term deletion
n/a
1. Create a new NVRF Field term
2. Edit a State page and from the NVRF tab add the newly created term and save
3. Go back the the new NVRF Field term and delete it
4. Go back the State page that you just updated, and confirm that the term was removed (there shouldn't be two blank term fields shown, only 1 for a new entry)

VOTE-628: Update nodes that use field_nvrf_fields to remove nvrf_field terms upon term deletion

---

docs/backend.md
docs/testing.md

[VOTE-2463](https://cm-jira.usa.gov/browse/VOTE-2463)
[VOTE-2999](https://cm-jira.usa.gov/browse/VOTE-2999)
Documentation for information on GSA Authentication
Documentation for Automated Tests
1. n/a
1. Review documentation for readability and understanding. Identify any errors or missing information in addition to providing suggestions.

VOTE-2463 and VOTE-2999: Add documentation on GSA Auth and Automated Testing

---

config/sync/automated_cron.settings.yml
config/sync/core.extension.yml

[VOTE-3440](https://cm-jira.usa.gov/browse/VOTE-3440)
Enable Automated Cron
1. Simply confirm that the Automated Cron module is enabled.
2. Login and goto /admin/reports/status to confirm Last Cron Run is today.

VOTE-3440: Enable Automated Cron.

---

composer.lock

[VOTE-3471](https://cm-jira.usa.gov/browse/VOTE-3471)
Update Drupal Core and modules.
1. Confirm site works as expected.

VOTE-3471: Update drupal core.

---

composer.json
composer.lock
config/sync/core.entity_view_mode.node.diff.yml
config/sync/core.extension.yml
config/sync/diff.settings.yml

[VOTE-1136](https://cm-jira.usa.gov/browse/VOTE-1136) - Add Diff module
[VOTE-3485](https://cm-jira.usa.gov/browse/VOTE-3485) - Drupal updates
Update drupal core and modules.
Add and enable Diff module.
Run 'lando retune'
1. Review ticket for Drupal updates for any testing instructions.
2. For Diff module, review the revisions tab for a pre-existing content item and select two revisions to compare to see changes.

VOTE-1136: Add config for diff module. VOTE-3485: Update drupal core and modules

---

config/sync/core.entity_form_display.block_content.nvrf_display_content.default.yml
config/sync/core.entity_view_display.block_content.nvrf_display_content.default.yml
config/sync/field.field.block_content.nvrf_display_content.field_nvrf_footer.yml
config/sync/field.storage.block_content.field_nvrf_footer.yml
config/sync/views.view.nvrf_api_blocks.yml
web/modules/custom/vote_fields/src/Plugin/Field/FieldType/NvrfCardItem.php
web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/NvrfCardWidget.php
web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/StateContentWidget.php

https://cm-jira.usa.gov/browse/VOTE-3517
Update nvrf card field validation to prevent blocking save when you have made no changes.
Added nvrf footer field to store data for the footer.
1. visit https://vote-gov.lndo.site/admin/content/block/27 and add data to nvrf card field and nvrf footer and save.
2. visit https://vote-gov.lndo.site/admin/content/block/27 again, make no changes and save. Confirm that you did not receive an error.
3. visit https://vote-gov.lndo.site/nvrf/assets/strings.json and confirm that you you can see your data for the nvrf card and the nvrf footer in the endpoint.

VOTE-3517 Update to nvrf card field validation and add nvrf footer field

---

composer.lock

[VOTE-3514](https://cm-jira.usa.gov/browse/VOTE-3514)
Update Drupal core dependencies and modules.
1. Review ticket comment for included updates and steps to test (if applicable).

VOTE-3514: Update drupal modules and core dependencies.

---

config/sync/editor.editor.basic_html.yml
config/sync/filter.format.basic_html.yml
config/sync/filter.format.simple_html.yml
config/sync/linkit.linkit_profile.default.yml

[VOTE-3499](https://cm-jira.usa.gov/browse/VOTE-3499)
Update linkit module profile configuration and enable the filter for text format filters.
1. Login as admin
2. Goto content admin page and edit a content item such as a landing page or basic page that has content.
3. Edit a paragraph and select any random piece of text and click the link icon
4. Confirm that you get the popup which allows you to search and link to existing content items. (NOTE: NVRF Page content items should be excluded from being able to link to)
5. Save the the changes and confirm that the link works and points to the url alias instead of the node url.
](https://github.com/usagov/vote-gov-drupal/pull/1277)

VOTE-3499: Update linkit module config and apply to text filters.

---

web/themes/custom/votegov/src/sass/uswds-overrides/usa-alert.scss

https://cm-jira.usa.gov/browse/VOTE-3464
Resolves issue with alert info offset
1. cd into votegov theme and run `npm run build`
1. Create a new page https://vote-gov.lndo.site/node/add/page and add an inline alert using the embedded content button
2. Add both an info alert and a warning alert and save
3. Confrim on the display that both alerts align on the left side.
4. Create an arabic translation of the new page and save
5. Confirm on the display that both alerts align on the right side.

VOTE-3464 resolve offset issue with info alert

---

config/sync/workflows.workflow.publishing_content.yml

[VOTE-3502](https://cm-jira.usa.gov/browse/VOTE-3502)
Enable content moderation/workflow for landing page content type.
1. Locally, run `lando retune`
2. Login to site as admin or content editor.
3. Goto admin content page and edit any landing page and confirm that content moderation option displays at the bottom of the page.
4. Additional testing should be done to confirm early discovered issues regarding draft translations changes reverting when another translation is published.

VOTE-3502: Enable content moderation for landing page.

---

composer.lock
config/sync/admin_toolbar.settings.yml
web/modules/custom/vote_nvrf/src/Controller/NvrfPageController.php

https://cm-jira.usa.gov/browse/VOTE-3548
Update Drupal Core and modules
core 10.4.7
admin_toolbar 3.6.0
editoria11y 2.2.9
1. cd into testing directory and run `npm test`
2. Follow release testing documentation
3. visit http://vote-gov.lndo.site/admin/reports/updates and make sure everything is up to date

VOTE-3548 drupal core and module updates
