usagov/vote-gov-drupal

composer.json, composer.lock, patches/README.md, patches/double_field/2091587-text_long-60_2.patch
[https://bixal-projects.atlassian.net/browse/VOTE-845](https://bixal-projects.atlassian.net/browse/VOTE-845)
Create a new patch file for the double_field module to enable label display for text_long fields
1. run `lando composer install`
2. run `lando drush cr` 
1. Create a new accordion group block
2. Make sure the label is displaying above the wysiwyg field
=> VOTE-845 Patch double_field module to fix display of labels for text_long fields

.gitignore, manifest.yml, private/.htaccess, scripts/bootstrap.sh, scripts/cronish.sh, web/sites/default/settings.cloudgov.php
[VOTE-968](https://bixal-projects.atlassian.net/browse/VOTE-968)
Implements `drush cron` job to run every hour in the background of the first application instance.
=> VOTE-968: drush cron buildpack implementation.

.circleci/config.yml
Alpine is running /bin/sh instead of /bin/bash by default.
=> [VOTE-874]: Install Bash

config/editor.editor.full_html.yml, config/field.field.node.page.field_body.yml, config/filter.format.full_html.yml
https://bixal-projects.atlassian.net/browse/VOTE-1105
A site admin can add a basic page with full markup and styles. The basic page will display with all styles added via the WYSIWYG.
run lando composer install
run lando drush cr
1. In the admin panel (logged in as admin), create a basic page type
2. In the content wysiwyg editor, click the source button. Add in the markup for the slick-sheet accordion.
3. Publish the page and view the accordion on the page.
=> VOTE-1105 Basic-page-full-html-wysiwyg

composer.lock
https://bixal-projects.atlassian.net/browse/VOTE-1031
Update the double field module to version 4.1.1
1. run lando composer install
2. run lando drush cr
1. Verify that the double field module version is 4.1.1
2. Within the admin interface, under structure->content types->state/territory page fields, verify that the double field text boxes show the label (this verifies the long text patch is still working)
=> Update the double field module to 4.1.1

web/themes/custom/vote_gov/package-lock.json, web/themes/custom/vote_gov/package.json
Bump uswds to 3.4.1
Bump browser-sync to 2.29.1
Bump uglify-es to 3.3.10
https://bixal-projects.atlassian.net/browse/VOTE-1180
Update vote_gov theme npm dependencies
1. cd into vote_gov theme
2. run `npm i`
1. run `npm run dev`
2. run `npm run build`
3. Make sure neither script is failing
=> VOTE-1180 Update vote_gov theme dependencies

composer.json, composer.lock, config/core.extension.yml, config/remove_http_headers.settings.yml
[VOTE-1054](https://bixal-projects.atlassian.net/browse/VOTE-1054)
Install & Enable Remove HTTP Headers contrib module.
1. Go to /admin/config/system/remove-http-headers and be sure the module is configured correctly.
=> VOTE-1054: Enable Remove HTTP headers contrib module

config/core.entity_form_display.block_content.sitewide_alert.default.yml, config/core.entity_view_display.block_content.sitewide_alert.default.yml, config/field.field.block_content.sitewide_alert.field_publish.yml, config/field.storage.block_content.field_publish.yml, config/views.view.site_alerts.yml, testing/cypress/e2e/externalLinks/english-external-links-validator.cy.js, testing/cypress/e2e/internalLinks/english-internal-links-validator.cy.js
[VOTE-1065](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1065&assignee=609161faf6c0960069bf61b3)
Adds publish checkbox to site alerts and then filters by publish in site alerts view page
1. Pull branch
2. Run lando retune
1. Create content for a site alert block and select the publish checkbox
2. Visit /admin/content/site-alerts and see that the block appears in the list
3. Un-publish the block and see that it no longer appears in the list
=> VOTE-1065: Site alert publish filter

config/core.entity_view_display.block_content.sitewide_alert.default.yml, web/themes/custom/vote_gov/templates/block/block-content--sitewide-alert.html.twig
[VOTE-995](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-995&assignee=609161faf6c0960069bf61b3)
Implements use of both informational and emergency variants from USWDS for alert styling.
1. Pull branch
2. Run lando retune
1. Create content for both an informational alert and an emergency alert
2. Check any site page to see that they are styled according to their variant
=> VOTE-995: adds uswds alert variants

web/modules/custom/vote_utility/inc/block_content_revisions.inc, web/modules/custom/vote_utility/vote_utility.module
[VOTE-975](https://bixal-projects.atlassian.net/browse/VOTE-975)
Add custom code to remove block_content revisions above 10 revisions per block.
1. Create 10 revisions for a block and run a sql command **SELECT count(*) FROM block_content_revision WHERE id={  block_id }** to be sure future saves/revisions do not exceed 10.
2. Also **SELECT * FROM block_content_revision WHERE id={ block_id } ORDER BY revision_created DESC;** lists the latest revisions left in descending order.
=> VOTE-975: Delete block_content revisions greater than 10 revisions

config/language.negotiation.yml, config/views.view.block_content.yml, config/views.view.content.yml, config/views.view.files.yml, config/views.view.global_blocks.yml, config/views.view.media.yml, config/views.view.media_library.yml, config/views.view.moderated_content.yml, config/views.view.redirect.yml, config/views.view.site_alerts.yml, config/views.view.user_admin_people.yml, config/views.view.watchdog.yml
Exposed all translation options to listing pages that apply Update admin listing page titles to be explicit
https://bixal-projects.atlassian.net/browse/VOTE-1115
Update admin listings for translations
1. delete block content: Accordion Group, Basic & Registration tool
2. Uninstall inline_entity_form
3. Uninstall migrate module and related migration modules
1. Visit http://vote-gov.lndo.site/admin/content and make sure the translation filter has all options visible.
2. Visit http://vote-gov.lndo.site/admin/content/media and make sure the translation filter has all options visible.
=> VOTE-1115 update admin listings

web/modules/custom/vote_utility/translations/bn.po, web/modules/custom/vote_utility/translations/es.po, web/modules/custom/vote_utility/translations/hi.po, web/modules/custom/vote_utility/translations/km.po, web/modules/custom/vote_utility/translations/ko.po, web/modules/custom/vote_utility/translations/nv.po, web/modules/custom/vote_utility/translations/tl.po, web/modules/custom/vote_utility/translations/vi.po, web/modules/custom/vote_utility/translations/ypk.po, web/modules/custom/vote_utility/translations/zh-hans.po, web/modules/custom/vote_utility/translations/zh.po, web/themes/custom/vote_gov/templates/paragraph/paragraph--registration-tool.html.twig
[VOTE-1245](https://bixal-projects.atlassian.net/browse/VOTE-1246)
This migrates the translations for the site name text above the logo
1. Check each language's logo text is translated accurately the Jira ticket number (i.e. "VOTE-123 Implement feature X").
- Automated pipeline tests have passed.
- At least one “Reviewer has been specified.
=> VOTE-1245: migrate logo text translations

manifest.yml
https://bixal-projects.atlassian.net/browse/VOTE-1191
We need higher level environments, PROD and STAGE, to exclude composer dev dependencies from installing.
COMPOSER_NO_DEV should equal 1 on PROD and STAGE
COMPOSER_NO_DEV should equal 0 on DEV and TEST
@casey-rapnicki-bixal  please look this over and see if I applied it correctly.
=> VOTE-1191 add new env var for composer install

composer.json, composer.lock
https://bixal-projects.atlassian.net/browse/VOTE-1272
Patch Pathauto module for compatibiity with PHP 8.2
1. Delete logs in local Drupal site http://vote-gov.lndo.site/admin/reports/dblog/confirm
2. Create a new basic page http://vote-gov.lndo.site/node/add/page
3. Check that there are no error messages triggered from pathauto http://vote-gov.lndo.site/admin/reports/dblog
=> VOTE-1272 patch Pathauto module for php 8.2

composer.json, composer.lock, config/core.extension.yml, config/crazyegg.settings.yml
https://bixal-projects.atlassian.net/browse/VOTE-1268
Installed an enabled the Crazyegg Integration module
1. Visit http://vote-gov.lndo.site/admin/config/system/crazyegg , and confirm you can view the admin configuration for the module.
=> VOTE-1268/Install Crazyegg module

web/themes/custom/vote_gov/src/js/nvrf-pdf-download.js, web/themes/custom/vote_gov/templates/block/block-content--registration-form-selector--full.html.twig, web/themes/custom/vote_gov/vote_gov.libraries.yml
[VOTE-1072](https://bixal-projects.atlassian.net/browse/VOTE-1072)
Add JS function to NVRF form download block.
1. cd in vote_gov theme and run `npm run build && lando drush cr`
1. visit http://vote-gov.lndo.site/register/ar
2. test selecting a language and clicking download button
3. PDF link should open in a new tab
=> VOTE-1072 Add js function to NVRF form download block

testing/cypress/e2e/tests/user-content-access.cy.js
[Vote-917](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-917&assignee=611272e0eb7aef00694b8a97)
This PR will add the content editor role in checking content moderation access.  
4. run `npm run cy:createUser` once complete move to the next step 
5. run `npm run cy:open` select `user-content-access.cy.js` test and verify that the test is passing 
6. once the test is complete, return to terminal in the `testing` folder and run `npm run cy:deleteUser`
=> Vote 917 -> content editor content moderation test

.circleci/config.yml
[VOTE-1518](https://bixal-projects.atlassian.net/browse/VOTE-1518)
`build-theme` doesn't need to run on prod. It has it's own workflow.
=> VOTE-1518: Fix pipeline for prod deployment

web/themes/custom/vote_gov/php-includes/preprocess.inc, web/themes/custom/vote_gov/templates/navigation/links--language-block.html.twig
https://bixal-projects.atlassian.net/browse/VOTE-1476
Current language selector on the homepage produces links like this.
English: /votegov-homepage
Spanish: /es/votegov-homepage
We do not want a redirects to correct paths so we need to update them to be
English: /
Spanish: /es
1. visit http://vote-gov.lndo.site/
2. check the links in the language selector to make sure they do not contain "votegov-homepage"
3. make sure the links work
=> VOTE-1476 fix homepage language selector links

web/themes/custom/vote_gov/templates/block/block--vote-gov-page-title.html.twig, web/themes/custom/vote_gov/templates/paragraph/paragraph--registration-tool.html.twig, web/themes/custom/vote_gov/templates/partial/site-logo.html.twig
[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-1479)
The site logo needs to be applied in two templates. I moved the code with the correctly translated site name into a partial to improve consistency and maintainability. This fixes the interior page translation bug.
1. Verify that these two pages have the correctly translated site name in Spanish
http://vote-gov.lndo.site/es
http://vote-gov.lndo.site/es/acerca-de-votegov
2. Repeat for each language
=> VOTE-1497 Move site logo translation code into partial

web/themes/custom/vote_gov/php-includes/preprocess.inc, web/themes/custom/vote_gov/templates/block/block--languageswitcher-2.html.twig, web/themes/custom/vote_gov/templates/block/block--languageswitcher.html.twig, web/themes/custom/vote_gov/templates/block/block-content--search.html.twig
https://bixal-projects.atlassian.net/browse/VOTE-1454
1. Remove language switcher on 404 and 403 pages
2. Update search placeholder for "(in English)" to match string translation
1. Visit http://vote-gov.lndo.site/ypk make sure the "(in English)" text is translated.
2. Visit http://vote-gov.lndo.site/blank and make sure that there is no language switcher.
=> VOTE-1454 revisions from error page UAT

composer.json, composer.lock, config/core.extension.yml, config/crazyegg.settings.yml, config/google_tag.settings.yml, web/themes/custom/vote_gov/templates/layout/html.html.twig
https://bixal-projects.atlassian.net/browse/VOTE-1409
This removes 2 modules from the codebase: Google Tag and crazyegg. After doing testing and research Google Tag module would be harder to maintain than the hardcoded value. Additionally, google tag can implement crazy egg remotely without the need for a module so we are removing crazyegg module from the codebase. Finally we are hardcoding in GTM code for logged out users.
1. VIsit http://vote-gov.lndo.site/ open the inspector and look at the sources tab to confirm googletagmanager.com is there.
=> VOTE-1409 tracking tool updates

config/field.field.block_content.email_signup.field_link.yml
[Vote-1454](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1454&assignee=611272e0eb7aef00694b8a97)
This Pr will update the config file to allow the email subscribe link to be translatable.
1. import new config db 
2. update the email subscribe link on home page to have all translations to be English link and Spanish translations has Spanish link [English Link](https://connect.usa.gov/subscribe) and [Spanish Link](https://conectate.gobiernousa.gov/suscripciones)
1. Very within file that `translatable` is now set to `true`
2. visit the home page and check that the email sign-up button is taking the user to the correct page (the expected result is every translation goes to …
=> VOTE-1454 -> update config to allow email link to be translated 

web/modules/custom/vote_utility/translations/ko.po
[Insert Jira ticket link](https://bixal-projects.atlassian.net/browse/VOTE-1424)
The string 'Virginia' has been replaced with the state name variable.
2. lando import-translations
1. Go to http://vote-gov.lndo.site/ko/register/nd
2. Verify the not needed string is pulling in the state name North Dakota
3. Using Google translate, verify the string 'Virginia' in Korean characters is no longer in the string.
=> VOTE-1424 Incorrect Korean translation of "not needed" text on North Dakota page

web/themes/custom/vote_gov/package-lock.json, web/themes/custom/vote_gov/package.json
[VOTE-1530](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-1530&assignee=609161faf6c0960069bf61b3)
upgrade browser-sync to 2.29.3
1. run command 'npm run dev' inside theme directory
2. Confirm no dependency errors
=> VOTE-1530: upgrade browser-sync to 2.29.3

config/language.entity.hi.yml, config/language.entity.ht.yml, config/language.entity.km.yml, config/language.entity.ko.yml, config/language.entity.nv.yml, config/language.entity.pt.yml, config/language.entity.tl.yml, config/language.entity.vi.yml, config/language.entity.ypk.yml, config/language.negotiation.yml, config/language/pt/core.date_format.revision_date.yml, config/language/pt/metatag.metatag_defaults.front.yml, config/language/pt/metatag.metatag_defaults.global.yml, config/language/pt/metatag.metatag_defaults.node__landing.yml, config/language/pt/metatag.metatag_defaults.node__state_territory.yml, web/modules/custom/vote_utility/translations/pt.po
https://bixal-projects.atlassian.net/browse/VOTE-1489
- Config/code:
- Create new language in Drupal and disable
- String translations
- Date format
- Metatags
1. Visit http://vote-gov.lndo.site/admin/config/regional/language and confirm Portuguese is created and disabled
2. Visit http://vote-gov.lndo.site/admin/config/regional/translate and confirm Portuguese content interface translations exist
3. Visit http://vote-gov.lndo.site/admin/config/regional/date-time/formats/manage/revision_date/translate/pt/edit and confirm the Portuguese date format
=> VOTE-1489 initialize Portuguese translation

config/core.entity_view_display.node.state_territory.full.yml, web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig, web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
https://bixal-projects.atlassian.net/browse/VOTE-1652
Add NVRF download block to all state pages that have the "Accepts NVRF" checkbox checked. Note that the filed data for this is not migrated yet.
1. visit http://vote-gov.lndo.site/register/ak the NVRF download block should not be displaying
2. edit the page and check the box for "Accepts NVRF" and save
3. view the page again http://vote-gov.lndo.site/register/ak and see the download block is displaying
=> VOTE-1652 Add NVRF download block to all state pages that accept it

web/modules/custom/vote_utility/translations/ar.po
https://bixal-projects.atlassian.net/browse/VOTE-1486
Fixes typos in string translation placeholders for Arabic.
1. visit http://vote-gov.lndo.site/ar and make sure the sitename above the logo is replaced with "Vote.gov"
=> VOTE-1486 fix placeholder typos in arabic string translations

config/views.view.inline_alert.yml, web/themes/custom/vote_gov/src/sass/uswds-overrides/_index.scss, web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-alert.scss, web/themes/custom/vote_gov/templates/block/block-content--inline-alert.html.twig, web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig, web/themes/custom/vote_gov/templates/node/node.html.twig
[Insert Jira ticket link
](https://bixal-projects.atlassian.net/browse/VOTE-1592)
Create view to display published inline alert as a list based on language
1. Create one block of type inline alert with an unpublished state (English)
2. Create two blocks of type inline alert with a published state (Navajo and Yup'ik)
1. Navigate to a state page
2. Confirm the Navajo alert is visible only on the Navajo page
3. Confirm the Yup'ik alert is visible only on the Yup'ik page
4. Confirm the English block is not visible on any language page
5. Delete all inline alert blocks and confirm they are no longer displaying.
=> VOTE-1592 Render and style inline alert block type

web/modules/custom/vote_utility/translations/ru.po
https://bixal-projects.atlassian.net/browse/VOTE-1857
1. `lando import-translations`
1. log into the site
2. visit http://vote-gov.lndo.site/ru and make sure the new Russian sitename above the logo is displaying.
=> VOTE-1857 Add new Russian translation for sitename

web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss
https://cm-jira.usa.gov/browse/VOTE-216
Minor adjustment to the vertical padding of the language selector.
1. cd into vote_gov theme and run `npm run build`
1. Visit http://vote-gov.lndo.site/ and confirm the vertical spacing between language links is reduced.
=> VOTE-216 adjust vertical padding for language switcher

.circleci/config.yml
n/a
This Pr will update the pipeline config to remove the link validation step.  This step will be added to a schedule to help not slow down the deploy process 
n/a
n/a
1. check that config file no longer has the step to run the internal links validation step
=> Bug -> remove link validation test from pipeline

web/modules/custom/vote_utility/translations/ar.po, web/modules/custom/vote_utility/translations/bn.po, web/modules/custom/vote_utility/translations/fr.po, web/modules/custom/vote_utility/translations/hi.po, web/modules/custom/vote_utility/translations/ht.po, web/modules/custom/vote_utility/translations/km.po, web/modules/custom/vote_utility/translations/ko.po, web/modules/custom/vote_utility/translations/nv.po, web/modules/custom/vote_utility/translations/pt.po, web/modules/custom/vote_utility/translations/ru.po, web/modules/custom/vote_utility/translations/tl.po, web/modules/custom/vote_utility/translations/vi.po, web/modules/custom/vote_utility/translations/ypk.po, web/modules/custom/vote_utility/translations/zh-hans.po, web/modules/custom/vote_utility/translations/zh.po
[VOTE-87](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-87&quickFilter=23166)
After testing new languages that were migrated over i found that the Wy pdf link was missing the `(in english)` string for the links.  This PR updated string translations.
n/a
n/a
3. run `lando import-translations` or `lando retune` to import the updated strings 
4. visit the Wyoming page and check that for all languages besides English and Spanish has the `(in english)` added to the link
=> VOTE-87 - added (in english) to stings as needed for wy pdf link

web/themes/custom/vote_gov/src/sass/drupal-system/_index.scss, web/themes/custom/vote_gov/src/sass/drupal-system/hidden.module.css, web/themes/custom/vote_gov/templates/layout/html.html.twig, web/themes/custom/vote_gov/vote_gov.info.yml
https://cm-jira.usa.gov/browse/VOTE-222
vote_gov theme is inheriting several css files that are not required for the function of vote.gov. Remove these files while making sure there is no visual or functional regression.
1. Visit vote-gov.lndo.site and view the source code
2. confirm that the core system CSS files are removed from the `<head>`
=> VOTE-222 Exclude unneccesary drupal system theme assets from vote_gov theme

.circleci/config.yml
[Vote-239](https://cm-jira.usa.gov/browse/VOTE-239)
This PR will separate out the cypress front end and axe tests into separate steps and then also added a flag that if the front end tests were to fail it till still run the axe tests.  How ever the build will still fail if one step does not pass.
n/a
n/a
1. review file changes and ensure that setup is correct for breaking out steps 
**Note**
> I have checked this on test and it is working as expected with the first test failing and still running the next step
=> Vote-239 -> Separate out cypress tests

config/sync/core.entity_form_display.node.landing.default.yml, config/sync/core.entity_form_display.node.page.default.yml, config/sync/core.entity_form_display.node.state_territory.default.yml, config/sync/field.field.node.landing.body.yml, config/sync/field.field.node.page.body.yml, config/sync/field.field.node.state_territory.body.yml, config/sync/language/fr/metatag.metatag_defaults.global.yml
https://cm-jira.usa.gov/browse/VOTE-221
Page description fields were introduced in anticipation of teaser content or metadata descriptions. Teasers are not required for launch and the metadata descriptions can already be manipulated on each node. Until further requirement becomes necessary we are disabling.
1. Visit http://vote-gov.lndo.site/node/add and view the add form for each content type
2. Make sure there is no page description field displaying in the add form
=> VOTE-221 Disable page description fields on content types

testing/cypress/e2e/backEndTests/basic-page.cy.js, testing/cypress/e2e/backEndTests/user-content-access.cy.js
[Vote-241](https://cm-jira.usa.gov/browse/VOTE-241)
This PR will update some backend tests post sprint 40 for a field that could have been removed.
n/a
n/a
3. run `lando drush pm-uninstall usagov_login`
4. cd into `testing`
5. run the following commands, `npm run cy:fullTests`, `npm run cy:axe`, `npm run cy:open` and check there are no errors
=> vote-241 -> Updated Backend post sprint 40

config/sync/editor.editor.basic_html.yml, config/sync/editor.editor.full_html.yml, config/sync/filter.format.basic_html.yml, config/sync/filter.format.full_html.yml
Disable unused full text format
https://cm-jira.usa.gov/browse/VOTE-105
Allow h2 id attribute for basic html text format when editing source. Also disable full html text format that is unused.
1. Visit http://vote-gov.lndo.site/node/add/page and add a heading 2 tag with text `TEST` to the wysiwyg
2. Edit the wysiwyg source using the toolbar button and add a id attribute value `test`
3. Save and publish the page
4. View it on the frontend and inspect the heading2 tag and make sure the id attribute is present
5. Visit http://vote-gov.lndo.site/admin/config/content/formats and confirm the Full html text format is missing
=> VOTE-105 alter basic text format to allow id attr on heading 2

testing/package-lock.json, testing/package.json
[Vote-302](https://cm-jira.usa.gov/browse/VOTE-302)
This PR will compete dependabot updates for Cypress and will close out the following PRs
https://github.com/usagov/vote-gov-drupal/pull/376, https://github.com/usagov/vote-gov-drupal/pull/375, https://github.com/usagov/vote-gov-drupal/pull/374, https://github.com/usagov/vote-gov-drupal/pull/369, https://github.com/usagov/vote-gov-drupal/pull/368
n/a
n/a
4. run `npm install`
5. run the following commands and ensure there are no errors or issues -> `npm run cy:fullTests`, `npm run cy:axe` and `npm run cy:open` and make sure the runner loads and tests run
=> VOTE-302: Cypress dependabot updates

web/themes/custom/vote_gov/php-includes/preprocess.inc, web/themes/custom/vote_gov/src/sass/pages/_index.scss, web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-alert.scss, web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-language-selector.scss
[VOTE-293](https://cm-jira.usa.gov/browse/VOTE-293)
Remove the Navajo font from the language dropdown, so that all the language names display correctly.
2. Might have to rebuild the vote theme folder 
1. Sign into the CMS (hidden languages will not show up without signing in)
1. Navigate to http://vote-gov.lndo.site/nv
2. Click the language dropdown and confirm each language uses the default site font (not the Navajo font)
3. Repeat for tablet and mobile screen size
=> Bug/vote 293/nv font lang switcher

web/themes/custom/vote_gov/src/sass/drupal-system/form.scss, web/themes/custom/vote_gov/src/sass/uswds-overrides/_override-usa-form.scss
https://cm-jira.usa.gov/browse/VOTE-337
Font font-weight difference on the CMS.
1. cd into vote_gov theme and run `npm run build`
1. visit `/accessibility` and make sure the form labels weight matches what is on staging.vote.gov
=> VOTE-337 Fix font-weight inconsistencies

web/themes/custom/vote_gov/templates/partial/footer-contact.html.twig
[VOTE-350](https://cm-jira.usa.gov/browse/VOTE-350)
Remove alt text and aria labels from vote.gov logo in the footer so it is treated as decorative
1. Lando retune
1. ANDI testing
1. Confirm tabbing and screen readers ignore the Vote.gov logo in footer
=> VOTE-350: make ballot box in footer decorative

web/themes/custom/vote_gov/img/ballot_box-blue.svg, web/themes/custom/vote_gov/templates/partial/site-logo.html.twig
[VOTE-349](https://cm-jira.usa.gov/browse/VOTE-349)
Issue is fixed by pointing the main logo svg aria-labelledby to the correct matching id
1. ANDI testing
1. Check that the exposed label of the large Vote.gov logo matches the accessible name given to it (Ex. Vote en Espanol should match Vote en Espanol)
=> VOTE-349: fix mismatching visible label and accessible name

web/themes/custom/vote_gov/templates/content/page-title.html.twig
[Vote-411](https://cm-jira.usa.gov/browse/VOTE-411)
This PR will fix the French title on the accessibility page that was rendering an HTML entity instead of `'`.  
before:
after:
n/a
n/a
2. run `lando rebuild -y`
3. visit `http://vote-gov.lndo.site/fr/accessibility` and verify that the title does not include the HTML entity `&#039;`
4. also spot check other pages and translations to ensure that the fix did not break any other strings
=> Vote-411 -> Bug fix on French Accessibility Page

.circleci/config.yml, scripts/upkeep
[VOTE-431](https://cm-jira.usa.gov/browse/VOTE-431)
Combine build-static and cron workflows into one and change schedule.
1. Confirm Terraform with the needed dependencies was applied to this environment.
1. Allow `upkeep-workflow` to run as a scheduled job in CircleCI.
2. Confirm the static site files were generated.
3. Confirm drush cron was run.
=> VOTE-431: update pipeline config and scripts for changing memory usage

config/sync/core.entity_form_display.taxonomy_term.nvrf_field.default.yml, config/sync/core.entity_view_display.taxonomy_term.nvrf_field.default.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_section_description.yml, config/sync/field.storage.taxonomy_term.field_section_description.yml, config/sync/views.view.nvrf_api_taxonomy.yml, config/sync/views.view.nvrf_reports.yml
https://cm-jira.usa.gov/browse/VOTE-605
Add a new NVRF field "Section Description" to the nvrf taxonomy.
1. Login to the CMS
2. Confirm the new field exists here http://vote-gov.lndo.site/admin/structure/taxonomy/manage/nvrf_field/overview/fields
3. Confirm the new field shows up in each field term (they should be empty and optional)
=> VOTE-605 Add new field to nvrf taxonomy

composer.lock
Update aws-sdk-php dependency to 3.288.1
Update aws-crt-php dependency to v.1.2.3
https://cm-jira.usa.gov/browse/VOTE-657
Resolving a security vulnerability found from scans.
Updating s3fs module to 3.4.0
Updateing aws-sdk-php dependency to 3.283.10
1. Test adding new document in the system to make sure it saves to the s3
2. Test disabling css/js aggregation in the system and reenabling to make sure it works
3. Test to make sure Tome generation still works and copies the assets
=> VOTE-657 update s3fs module to 3.4.0

config/sync/core.entity_view_display.node.voter_guide.full.yml
https://cm-jira.usa.gov/browse/VOTE-801
remove duplicate subtitle displaying on voter guide detail page
NOTE: make sure you have the latest DB imported
1. visit http://vote-gov.lndo.site/node/add/voter_guide and create a new voter guide with a subtitle field
2. Confirm that when you view the page the subtitle isn't showing twice.
=> VOTE-801 remove duplicate subtitle displaying on voter guide detail page

config/sync/core.extension.yml, web/modules/custom/ec_uswds/ec_uswds.info.yml, web/modules/custom/ec_uswds/ec_uswds.module, web/modules/custom/ec_uswds/src/Plugin/EmbeddedContent/ECUsaAlert.php, web/modules/custom/ec_uswds/templates/embedded-content/ec-uswds--usaalert.html.twig
https://cm-jira.usa.gov/browse/VOTE-857
Add a new embedded content type for USWDS alert
1. visit https://vote-gov.lndo.site/node/add/page and add a title.
2. In the wysiwyg click on the "Embedded content" button and select `USWDS: Alert` in the dialog
3. Fill out the fields and submit the dialog
4. Set the page to published and save
5. View the page and make sure the component is styled as the uswds alert component
=> VOTE-857 add embedded content type for usa-alert

web/sites/default/settings.cloudgov.php
[VOTE-775](https://cm-jira.usa.gov/browse/VOTE-775)
Remove deprecated setting for install_profile.
n/a
1. Locally run `lando retune`
1. Login as an administrator.
2. Go to admin Status page and confirm that there isn't a warning about "Install profile in settings" listed.
=> VOTE-775: Remove install_profile setting as it is no longer used.

config/sync/block.block.votegov_htmlsitemap.yml, config/sync/views.view.sitemap.yml, web/themes/custom/votegov/src/sass/components/_index.scss, web/themes/custom/votegov/src/sass/components/sitemap.scss, web/themes/custom/votegov/templates/embedded-content/ec-placeholder--sitemap-menu.html.twig, web/themes/custom/votegov/templates/navigation/menu--main--votegov-htmlsitemap.html.twig, web/themes/custom/votegov/templates/views/views-view--sitemap.html.twig
https://cm-jira.usa.gov/browse/VOTE-943
Configure and style the /sitemap page
1. cd into votegov theme directory and run `npm run builld`
1. visit http://vote-gov.lndo.site/sitemap and make sure the sitemap navigation is displaying
=> VOTE-943 configure and style the sitemap

config/sync/editor.editor.basic_html.yml, config/sync/filter.format.basic_html.yml
https://cm-jira.usa.gov/browse/VOTE-961
Allow class on h2s in WYSIWYG when using basic html format
1. visit http://vote-gov.lndo.site/node/3/edit and edit the source of wysiwyg to add a class on an h2 tag of `heading--red-underline`
2. save and view the page and make sure it has a red underline style.
=> VOTE-961 allow class attr on h2 in basic_html format

web/themes/custom/votegov/src/sass/_uswds-settings.scss, web/themes/custom/votegov/src/sass/base/containers.scss
[VOTE-912](https://cm-jira.usa.gov/browse/VOTE-912)
Adjusts grid container padding tablet+ to 5rem
1. Insert steps to test and confirm the result meets the "definition of done".
=> VOTE-912: Adjust Grid Container

scripts/upkeep
HOTFIX
Include robots.txt file in the generation of the static site.
n/a
n/a
1. Confirm that /robots.txt is accessible once the static site generation workflow has completed..
=> HOTFIX: Tome - add robots.txt to script

docs/backend.md
[VOTE-906](https://cm-jira.usa.gov/browse/VOTE-906)
Add documentation about Mysql configuration limitations and the database transaction isolation level setting.
n/a
n/a
1. Review documentation entry and confirm understanding, formatting, and any typos.
=> VOTE-906: Add documentation about mysql configuration limitations.

web/themes/custom/votegov/src/sass/components/_index.scss, web/themes/custom/votegov/src/sass/components/touchpoints.scss, web/themes/custom/votegov/templates/layout/page.html.twig
https://cm-jira.usa.gov/browse/VOTE-1001
This task added a button in the bottom right for a touchpoints survey. On mobile it is at the bottom of the scrollable page. It should trigger a touchpoints form dialog when selected.
1. cd into votegov theme and run `npm run build`
1. Visit http://vote-gov.lndo.site/ and confirm a touchpoint button displays on bottom right on mobile.
2. Click the button and make sure the form dialog displays.
=> VOTE-1001 Add global touchpoints feedback survey

web/themes/custom/votegov/src/sass/uswds-overrides/_index.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-alert.scss
[Vote-1008](https://cm-jira.usa.gov/browse/VOTE-1008)
There seems to be an override style within the uswds package that was causing the extra padding.  I have added a local override to match the same styles as what is expected from the USWDS component page. 
I have also added override to the sitewide alert and class both overrides will live in the same file.
`lando retune`
n/a
1. Pull down the branch and cd into the `votegov` theme 
2. Run `npm run build`
3. Visit `/user/login` and verify that the alert matches the [alert commponent](https://designsystem.digital.gov/components/alert/) on the uswds page
4. Can also visit `/admin/content/block/12?destination=/admin/content/block` and open the source code and adjust the `--warning` flag for `--info` and `--success` to verify that fix is …
=> Vote-1008: Adding override to alert component

web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss, web/themes/custom/votegov/templates/block/block--votegov-languageswitcher.html.twig, web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
[VOTE-1029](https://cm-jira.usa.gov/browse/VOTE-1029)
Add grid column restrictions to give language selector button room on wider widths
1. npm run build
2. go to any page and confirm there is no overlap between banner and language selector
3. test for 0, 2, 3+ languages by adding/removing translations
4. test for all screen sizes
=> VOTE-1029: Fix language selector / banner overlap

web/themes/custom/votegov/templates/block/block-content--email-signup.html.twig
[Vote-1036](https://cm-jira.usa.gov/browse/VOTE-1036)
Adding `target="_blank"` to the form to open sign up page in a new tab
n/a
n/a
2. visit local and scroll to the usa.gov email sign up field... enter an email and hit signup and verify that you are taken to a new page and email that was entered is present as well
=> Vote-1036: Update to email button

web/themes/custom/votegov/src/sass/uswds-overrides/usa-card.scss
[VOTE-1007](https://cm-jira.usa.gov/browse/VOTE-1007)
Insert a brief summary of the changes included in this PR and any additional information or context which may help the reviewer.
1. Insert steps to test and confirm the result meets the "definition of done".
=> VOTE-1007: feature card icon refinement

web/themes/custom/vote_gov/templates/layout/html.html.twig
[VOTE-383](https://cm-jira.usa.gov/browse/VOTE-383)
Resolve security scan issue with iframe embed for Google Tag Manager.
N/A
N/A
1. Locally, run `lando retune`
2. Load the site, inspect the source code, and confirm that the <iframe> tag for googletagmanager includes a 'sandbox' attribute.
=> VOTE-383: Add sandbox attribute to gtm iframe embed snippet.

web/themes/custom/votegov/src/sass/base/media.scss, web/themes/custom/votegov/src/sass/components/_index.scss, web/themes/custom/votegov/src/sass/components/media.scss, web/themes/custom/votegov/src/sass/mixins/mixins.scss, web/themes/custom/votegov/templates/media/media--document.html.twig, web/themes/custom/votegov/templates/media/media--image.html.twig, web/themes/custom/votegov/templates/media/media--remote-video.html.twig, web/themes/custom/votegov/templates/media/media.html.twig
https://cm-jira.usa.gov/browse/VOTE-959
https://cm-jira.usa.gov/browse/VOTE-960
Update styling of document and video rendered display
1. cd into the theme and run `npm run build`
1. Add a new field to NVRF Page for media reference that include documents, images and video and set it to unlimited values.
2. Create a new test NVRF page and add a document, an image and a remote video and save
3. View the page and confirm:
- the image and remote video fills the container and scales with browser width
- the  document link displays with the name of the file, the file size and a file icon
=> VOTE-959 VOTE-960 video and document style refinements

web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-search.scss
[VOTE-941](https://cm-jira.usa.gov/browse/VOTE-941)
- Changes placeholder text so it only shows on input focus (next round of design updates will add "search" text next to button).
- Keeps navigation items hidden when focus is on any search element
- Updates focus background of search element to match hover state
1. npm run build
2. Click in and out of search bar elements including element and buttons and confirm the navigation menu headers hide/show appropriately. 
3. Confirm hover and active states of search bar match
=> VOTE-941: Search bar style refinements

.circleci/config.yml
[VOTE-1054](https://cm-jira.usa.gov/browse/VOTE-1054)
Increase memory limit of upkeep task to allow task to complete
1. Confirm memory limit increase in cloud.gov
1. Allow upkeep tasks to run for some time.
2. Confirm upkeep tasks complete successfully with `cf task ...`
=> VOTE-1054 increased upkeep task memory from 512M to 1024M

web/themes/custom/votegov/src/sass/components/basics-block.scss
[Vote-1028](https://cm-jira.usa.gov/browse/VOTE-1028)
Updating media breakpoint for column layout to be enforced at desktop and not tablet to help address the spacing issue on the register to vote page. 
<details>
<summary>Before and After images</summary>
<br>
Left Image -> after - Right Image -> before 
</details>
1. Run `lando retune` cd into `votegov` directory and run `npm run build`
1. Visit `/register` and adjust the screen size and ensure that the spacing on the content does not get reduced like in the before image
=> Vote-1028: Fixing space issue on register to vote page

web/themes/custom/votegov/src/sass/mixins/mixins.scss
[Vote-1103](https://cm-jira.usa.gov/browse/VOTE-1103)
Adjust `vote-link` mixin by adding `!important` flag on the hover effect color.  
This was done because in `web/themes/custom/votegov/src/sass/components/footer-primary.scss` line 41, the color is also getting set with important so it is overriding the hover effect color. The update can also help down the road if there are any other colors that are set and would override the hover effect. 
1. cd into `votegov` theme and run `npm run build`
1. scroll to the footer and check that on hover the text color is white
=> Vote-1103: Bug fix for footer hover effect 

web/themes/custom/votegov/templates/taxonomy/taxonomy-term--basics-modules.html.twig
https://cm-jira.usa.gov/browse/VOTE-1064
In the basics modules taxonomy, change the heading levels dynamically based on whether the basics block heading is set.
1. Sign into the CMS locally
2. Go to http://vote-gov.lndo.site/register and edit the basics block to have a heading.
3. Confirm the Basics Block heading is h2 and the module subheadings are h3.
4. Remove the Basics Block heading
5. Confirm the module subheadings have changed to h2
6. Repeat steps 2-5 for Spanish. You might have to create the new translation if it doesn't exist yet.
=> VOTE-1064 basics block dynamic headings

web/themes/custom/votegov/src/sass/components/basics-block.scss
[Vote-1137](https://cm-jira.usa.gov/browse/VOTE-1137)
Adjusting the margin on `ul` elements to reduce extra space within basics blocks. 
Before there was the wildcard selector that was getting anything with the the `basics-block--content`, and this was causing the extra space.  By targeting the `ul` elments and making the margins equal on top and bottom will reduce the space.
<details>
<summary>Before and After Images</summary>
<br>
Before:
<br>
<br>
<br>
After:
<br>
</details>
1. cd into `votegov` theme and run `npm run build`
1. log into site and visit the voter guid for `new us citizens` scroll down to the block that is titled `Support for new citizens` and check that the `ul` has 16px margin. 
2. also spot check other voter guide with basics blocks for any visual regressions
=> Vote-1137: Fix spacing for UL on basics block

config/sync/node.type.voter_guide.yml
[Vote-1141](https://cm-jira.usa.gov/browse/VOTE-1141)
Removing the preview function from the voter guide.  This function is not consistent in its use and can cause more issues then help. 
1. log into the site and navigate to a voter guide and open the edit view... scroll to the bottom and verify that the `preview` option is no longer next to the save button
=> Vote-1141: Remove preview funtion for voter guide

config/sync/block.block.votegov_htmlsitemap.yml, config/sync/block.block.votegov_mainnavigation.yml, config/sync/field.field.block_content.sitewide_alert.field_publish.yml, web/themes/custom/votegov/templates/component/translation-alert.html.twig, web/themes/custom/votegov/templates/embedded-content/ec-placeholder--sitemap-menu.html.twig, web/themes/custom/votegov/templates/layout/page.html.twig
https://cm-jira.usa.gov/browse/VOTE-1337
https://cm-jira.usa.gov/browse/VOTE-1159
Add functionality for a site alert on the homepage for translations that are not ready.
2. Publish this node in english and spanish http://vote-gov.lndo.site/node/63/edit with `/legacy` as the url
4. Add and publish spanish translation of the new Homepage http://vote-gov.lndo.site/node/91/translations with `/votegov` as the url
5. Edit http://vote-gov.lndo.site/node/91/edit and select "mark all other translations as outdated" in the translations accordion in the sidebar
3. Visit http://vote-gov.lndo.site/es and confirm the site alert shows with a link to the legacy homepage
4. Click on the link and make sure it goes to http://vote-gov.lndo.site/es/legacy
1. Insert steps to test and …
=> VOTE-1337 add translation alert with sitemap fallback

web/themes/custom/votegov/src/sass/components/basics-block.scss, web/themes/custom/votegov/templates/paragraph/paragraph--basics-block.html.twig
https://cm-jira.usa.gov/browse/VOTE-1137
A scalable solution for allowing any tags added into the basic block description field and avoid unnecessary margin on top.
1. visit http://vote-gov.lndo.site/voting-new-us-citizen
2. make sure the margin on top of the ul is not inheriting the extra space
=> VOTE-1137-basics-block-text

scripts/pipeline/downsync-restore.sh
[VOTE-886](https://cm-jira.usa.gov/browse/VOTE-886)
Flush images after downsync restore.
1. Allow deploy to complete.
2. List backup and restore media storage bucket contents.
3. Trigger downsync pipeline.
4. Verify images are flushed and regenerated on restore env.
=> VOTE-886: Flush image files after downsync restore

config/sync/media.type.remote_video.yml
https://cm-jira.usa.gov/browse/VOTE-2012
Update storage location for oembed thumbnails to be inside the `/media/video` directory
1. log into the site and visit http://vote-gov.lndo.site/media/add/remote_video
2. Add a new remote video, save and confirm that the thumbnail is generated on the listing page http://vote-gov.lndo.site/admin/content/media
=> VOTE-2012 Update storage location for oembed thumbnails

web/themes/custom/votegov/src/js/external-links.js
[Vote-1342](https://cm-jira.usa.gov/browse/VOTE-1342)
Adding a comment in the js file to give guidance of adding the `extlinkjs-ignore` attribute for icons
n/a
1. review comment and check that it provides direction for the use of the attribute
=> Vote-1342: Adding comment for not adding external link icon 

config/sync/easy_breadcrumb.settings.yml, web/themes/custom/votegov/templates/navigation/breadcrumb.html.twig
[Vote-1336](https://cm-jira.usa.gov/browse/VOTE-1336)
Updating breadcrumb menu to match the page title... replaced the `item.text` with `Drupal Title` 
<details>
<summary>Before and After</summary>
<br>
Before: 
<br>
<br>
<br>
After: 
<br>
</details>
1. log in and visit a voter guide page, verify that breadcrumb is not matching the page title 
2. edit the page title and check that breadcrumb is still matching the page title.  can also visit a state page and update the title case for the state title and should also be reflected in the breadcrumb
=> Vote-1336: Breadcrumb to match page title case

web/themes/custom/votegov/templates/layout/html.html.twig
https://cm-jira.usa.gov/browse/VOTE-2020
Add GTM code to votegov theme
1. Visit http://vote-gov.lndo.site/ and confirm in the source code that the script and no script tags are present
=> VOTE-2020 Add GTM code to votegov theme

web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig
[Insert a link to the Jira ticket (e.g VOTE-XXX).](https://cm-jira.usa.gov/browse/VOTE-1107)
-Moves span elements in list inside of their list items so the list is a valid list
-Issue of close button being inside nav element is already resolved
1. confirm all direct elements in primary navigation list are list items
=> VOTE-1107: Move non li items in list

config/sync/filter.format.basic_html.yml
[Insert a link to the Jira ticket (e.g VOTE-XXX).](https://cm-jira.usa.gov/browse/VOTE-2065)
Reconfigures the text editor for basic HTML wysiwig to not allow image alignment option.
2. lando drush cim
3. edit a page
4. add an image inside the wysiwyg
5. hover over image while in wysiwyg and confirm no alignment buttons are available
=> VOTE-2065: configure basic HTML wysiwyg to not allow image alignment

web/themes/custom/votegov/templates/layout/page.html.twig
[VOTE-2040](https://cm-jira.usa.gov/browse/VOTE-2040)
Replaces hard coded alert component for legacy site link with a content block. The block has been created on production where ID is 20. Translations being added on production.
1. Test again with translations and block id that are on production
1. Create site alert block (this should have id 20 but if not update line 60 of page.html.twig to match your environment)
2. Confirm block shows on pages where translation is marked as outdated
3. Add translations for block and confirm it translates
=> VOTE-2040: Legacy site alert block content

config/sync/views.view.voter_guides.yml, web/themes/custom/votegov/templates/component/feature-cards.html.twig, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--feature-cards.html.twig, web/themes/custom/votegov/templates/views/views-view--voter-guides--embed-1.html.twig
[VOTE-2071](https://cm-jira.usa.gov/browse/VOTE-2071)
Add voter guide listing view to voter guide template.
1. visit http://vote-gov.lndo.site/voting-college-student
2. confirm that the voter guide listing is on the page
=> VOTE-2071 Add voter guide listing view to voter guide page template

config/sync/field.field.paragraph.hero.field_background_color.yml, config/sync/field.storage.paragraph.field_background_color.yml, web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig
[VOTE-946](https://cm-jira.usa.gov/browse/VOTE-946)
Add background color options for hero component.
1. visit http://vote-gov.lndo.site/your-vote-safe
2. edit the page and select background color in the hero as "dark"
3. view the page and see that the style of the hero has changed to the alternative version
=> VOTE-946 add background color option to hero for landing pages

config/production/config_split.patch.language.entity.hmn.yml, config/sync/config_split.config_split.local.yml, config/sync/config_split.config_split.non_production.yml, config/sync/config_split.config_split.production.yml
[VOTE-2078](https://cm-jira.usa.gov/browse/VOTE-2078) - User Configuration Updates - Site Builder Role
[VOTE-2017](https://cm-jira.usa.gov/browse/VOTE-2017) - Hmong language removal
Update configurations to include user roles as partials in config splits settings.
Remove Hmong related config as the language is being removed.
None
Testing results should not change from tests done in referenced tickets, above. But if you need to, the testing instructions are available in ticket PRs below.
VOTE-2078 - https://github.com/usagov/vote-gov-drupal/pull/741
VOTE-2017 - https://github.com/usagov/vote-gov-drupal/pull/745
=> Configuration cleanup

web/themes/custom/votegov/src/sass/uswds-overrides/usa-header.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-nav.scss, web/themes/custom/votegov/templates/layout/page.html.twig, web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig
https://cm-jira.usa.gov/browse/VOTE-2125
Make mobile menu close button accessible from keyboard.
1. run `npm run build` in votegov theme directory
1. visit http://vote-gov.lndo.site/
2. resize browser window to trigger mobile menu display
3. using your keyboard tab to trigger the mobile menu and close it using the close button.
=> VOTE-2125 make mobile menu close button accessible by keyboard

web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss
[Vote-2194](https://cm-jira.usa.gov/browse/VOTE-2194)
The breadcrumb style that was added last sprint was not getting applied to the voter guide... i update the class name to be more specific in the targeting 
1. run `lando retune` and cd into the `votegov` theme
1. visit a voterguide and inspect the hero and check that the header is getting a margin top of 80px/5rem applied
=> Vote-2194: Fix to breadcrumb style

config/sync/field.field.media.image.field_media_image.yml
[Vote-2124](https://cm-jira.usa.gov/browse/VOTE-2124)
Updating the alt text to be optional and no longer required 
1. log in as an admin and update the homepage hero by adding an image and verify that the alt text filed is no longer required.
=> Vote-2124: Make image alt text optional

config/sync/field.storage.paragraph.field_background_color.yml, web/themes/custom/votegov/src/sass/_variables.scss, web/themes/custom/votegov/src/sass/components/hero.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-button.scss, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig
[VOTE-2006](https://cm-jira.usa.gov/browse/VOTE-2006)
[VOTE-2110](https://cm-jira.usa.gov/browse/VOTE-2110)
[VOTE-2084](https://cm-jira.usa.gov/browse/VOTE-2084)
[VOTE-2180](https://cm-jira.usa.gov/browse/VOTE-2180)
- Homepage hero changes
- Hero high contrast changes
- Adding new 'homepage' variant to paragraph
- Adding breadcrumbs to hero for 'dark' variant
1. login and visit http://vote-gov.lndo.site/node/91/edit
2. Upload new homepage hero image located in the VOTE-2180 ticket and select the background color "homepage" and save
3. visit http://vote-gov.lndo.site/ and confirm the styling matches the figma design
4. switch to high contrast and confirm it matches figma design
5. Add arabic translation of homepage and test hero …
=> VOTE-2180 hero component styling updates

web/themes/custom/votegov/src/sass/_uswds-settings.scss
https://cm-jira.usa.gov/browse/VOTE-2203
Updated margin to 24px for mobile (per craig's beta design review/audit)
1. load up the local site
2. load up the beta.vote.gov site
3. go into mobile-screen mode through Inspect-Element for both sites.
4. verify the local site's margins are 24px and that they are bigger than those of beta.vote.gov
=> VOTE-2203: Modified mobile margins to 24px

web/themes/custom/votegov/src/sass/base/typography.scss, web/themes/custom/votegov/templates/paragraph/paragraph--basics-block.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
[Vote-2108](https://cm-jira.usa.gov/browse/VOTE-2108)
Follow up PR to remove `type--secondary` from scss and template files 
1. run `lando retune` and cd into `votegov` them and run `npm run build`
1. verify that `type--secondary` is not in the codebase and load site and verify now major visual regressions
=> Vote-2108: Remove `type--secondary` from files

config/sync/language/pt/language.entity.pt.yml
[VOTE-2200](https://cm-jira.usa.gov/browse/VOTE-2200)
Adds missing Portuguese config file to fix language selector dropdown selection.
2. make sure configuration is imported
3. Check that both names for Portuguese appear in language selector dropdown, matching the current Vote.gov site.
=> VOTE-2200: Add Portuguese config file

web/themes/custom/votegov/src/sass/uswds-overrides/usa-header.scss
[VOTE-2199](https://cm-jira.usa.gov/browse/VOTE-2199)
This fixes the issue on safari where the focus state outline box around the logo was not positioned correctly by adding inline-block rule to the wrapping <a> element.
3. Using safari browser 
4. test the focus outline position by selecting the logo in the header
=> VOTE-2199: Fix logo focus outline

web/themes/custom/votegov/src/sass/components/registration-tool.scss, web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
https://cm-jira.usa.gov/browse/VOTE-2191
Horizontally center the regisration tool columns on desktop and above
1. visit http://vote-gov.lndo.site/register make sure the two columns are horizontally center aligned
2. test in arabic and confirm it works in RTL
=> VOTE-2191 align registration tool horizontally on desktop

web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig, web/themes/custom/votegov/templates/media/image.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig
[Vote-2235](https://cm-jira.usa.gov/browse/VOTE-2235)
Addressing 2 fails that were happening in the Cypress Axe tests 
- Image needing alt text:  Now that we are setting alt text on an image as optional this will set up a conditional to check that if alt text is present render the image if not add the attribute of `role="presentation"` to allow the component to pass. [See documentation for more info](https://dequeuniversity.com/rules/axe/4.9/image-alt?application=axeAPI) 
- content needed a wrapper: With the new Voter guide cards it was living outside of main and needed to have a landmark element. [See documentation for more info](https://dequeuniversity.com/rules/axe/4.9/region?application=axeAPI)  
2. cd into `votegov` theme and run `npm run build`
1. log in as a …
=> Vote-2235: Fixes for Axe Tests

web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig
[VOTE-2105](https://cm-jira.usa.gov/browse/VOTE-2105)
When clicking the name of a section on the USWDS in-page nav component, the "current section" indicator does not move to the correct section. This temporary adjustment hides the current section indicator by removing the text color adjustment and left indicator bar, until the bug can be resolved with USWDS (issue [here](https://github.com/uswds/uswds/issues/5953)).
Before (darker color and left indicator show which section is currently on-screen):
After change (no visual indication of current section):
Navigate to `web/themes/custom/votegov`, and run `npm run dev`
In the root directory, run `lando retune`
1. Navigate to a page where the in-page nav appears -- for example, Guide to Voting > Voting as a college student
2. Make sure that …
=> VOTE-2105: Temporary CSS adjustment to in-page nav

web/themes/custom/votegov/php-includes/preprocess.inc, web/themes/custom/votegov/templates/component/usagov-partner.html.twig
[VOTE-2201](https://cm-jira.usa.gov/browse/VOTE-2201)
Hide footer USAGov election links for non-engish & spanish sites IF not translated.
1. Load up the local site.
2. Verify "Learn more about U.S. elections" section is present
3. Go to /es and verify "Learn more about U.S. elections" section is NOT present
5. in `es.po` add id-str-pair for "State and local elections".
6. Run `lando import-translations`
7. Go to /es again and verify "Learn more about U.S. elections" section is now present.
=> VOTE-2201: Hide footer usagov links for non-engish & spanish sites IF not translated

config/sync/field.field.paragraph.hero.field_background_color.yml, config/sync/field.storage.paragraph.field_background_color.yml
https://cm-jira.usa.gov/browse/VOTE-2265
Remove default option from background color field on hero paragraph
1. Visit http://vote-gov.lndo.site/node/79/edit and edit the hero component
2. Confirm that there are only 2 options: dark and homepage
=> VOTE-2265 Remove 'default' option from hero background color field

web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
[VOTE-2225](https://cm-jira.usa.gov/browse/VOTE-2225)
Removed unnecessary aria-describedby attribute on registration page
1. Load up the local site
2. Go to /register
3. Using Inspect-Element verify that there is no aria-describedby attribute in the <section class="vote-registration-tool">
- [] QA/Test steps were successfully completed, if applicable.
- [] Applicable logs are free of errors.
=> VOTE-2225: Removed unnecessary aria-describedby attribute for registration

web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig
[Vote-2228](https://cm-jira.usa.gov/browse/VOTE-2228)
Adding function for `arira-current` on the main nav links.  This set up function for the active page to have the current=page and all others to be set to false. 
See [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) to see more info on this
1. Inspect the main nav and check that when you click on the page that you see `aria-current="page"` while on the active page
=> Vote-2228: Adding aria-current to main menu items

web/themes/custom/votegov/src/sass/mixins/mixins.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-identifier.scss
https://cm-jira.usa.gov/browse/VOTE-2234
1. Change the vote-dark-link mixin to have a yellow hover state for high contrast
2. Correctly apply the mixin to the breadcrumb
1. re-build the theme
1. Visit [the register to vote page](http://vote-gov.lndo.site/register) and confirm the high contrast style is being applied correctly to the breadcrumb
2. Repeat on the [Guide to voting](http://vote-gov.lndo.site/guide-to-voting) page breadcrumb
=> Vote- 2234 high contrast breadcrumb

config/sync/views.view.voter_guides.yml
[VOTE-2249](https://cm-jira.usa.gov/browse/VOTE-2249)
Update voter guide listing on voter guide pages to be in ascending chronological order and excluding the current page.
1. visit http://vote-gov.lndo.site/guide-to-voting/preparing-age-18-and-under
2. Confirm that the guide doesn't show up in the listing of guides below the page content.
3. Confirm that "voting as a college student" is first and "voting after a felony conviction" is last
=> VOTE-2249 update voter guide listing config

web/themes/custom/votegov/src/sass/_uswds-settings.scss
[Vote-2127](https://cm-jira.usa.gov/browse/VOTE-2127)
Removing the default voice over notification coming from USWDS to let the user know they are on an external link.  Since we have added custom strings that will be translated this will no longer be needed. 
1. cd into the `votegov` theme and run a npm run dev and wait for build to complete 
1. Visit home page and turn on voiceover (for mac can use command+f5) and use the tab button to navigate to an external link
2. The expected behavior is you should not hear "external link" at the start of the command but only the custom message we have applied. 
3. To verify that this is targeting the right setting visit `web/themes/custom/votegov/src/sass/_uswds-settings.scss` and update the setting by adding `This is a test` after a rebuild you …
=> Vote-2127: Removed USWDS External Link Notification

web/themes/custom/votegov/templates/layout/page.html.twig
[Vote-2229](https://cm-jira.usa.gov/browse/VOTE-2229)
Adding `aria-label="secondary"` to the footer element to address issues brought up by the USA.gov team
see [W3 Documentation](https://www.w3.org/TR/WCAG20-TECHS/H97.html) for reference.  This update will match the same mark up for the aria-label found in the [main nav](https://github.com/usagov/vote-gov-drupal/blob/8c90441196b07d38c6f1ad23559ffd5d7c59e57c/web/themes/custom/votegov/templates/navigation/menu--main--votegov-mainnavigation.html.twig#L30)
1. inspect the footer and check that `aria-label="Secondary"` is present
=> Vote-2229: Adding aria-label="secondary" to footer nav

web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss
[VOTE-2261](https://cm-jira.usa.gov/browse/VOTE-2261)
Adds high contrast variables for the language selector button and dropdown
3. Visit a page that has 3 translations so the dropdown renders
4. Toggle the language selector and confirm no style regressions
5. Toggle high contrast mode on
6. Toggle the language selector and high contrast confirm styles
=> VOTE-226: Language selector - high contrast

web/modules/custom/vote_utility/translations/es.po, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig
[Vote-2349](https://cm-jira.usa.gov/browse/VOTE-2349)
Adding the Spanish translation for "On this page" for the in-page nav. 
1. log in as an admin locally and visit `http://vote-gov.lndo.site/node/82/translations` and add a spanish translation (just save the page no need to worry about other text). 
2. verify that `On this page` has been translated.
=> Vote-2349: Add "On this page" transltion for spanish

web/themes/custom/votegov/src/sass/components/touchpoints.scss
[Vote-2233](https://cm-jira.usa.gov/browse/VOTE-2333)
Adding high contrast styles to the embedded touch points form on accessibility page.  Also updating the base style to match the site theme as well. 
1. run `lando retune` and then cd into the `votegov` theme and run `npm run build`
1. visit accessibility page and toggle on the high contrast mode and verify that styles are being added.  
2. also check that hover and base styles match others on the site as well.
=> Vote-2233: adding contrast styles to touchpoints form

web/themes/custom/votegov/templates/layout/page--node--landing.html.twig, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig, web/themes/custom/votegov/templates/layout/page.html.twig
[VOTE-2328](https://cm-jira.usa.gov/browse/VOTE-2328)
Insert a link to the Jira ticket (e.g VOTE-XXX).
ANDI screen reader was generating an extra 'X' where the skip nav link element was to flag where it was removed from tab order. To fix, #main-content id has been to the container of the main content in each instance.
2. Using ANDI, turn on tab order
3. Confirm skip navigation works the same as expected
4. Confirm the "X" span isn't being added under the main nav
=> VOTE-2328: Move #main-content id to fix andi tab order

config/sync/field.field.paragraph.double_deck_card.field_body.yml, config/sync/field.field.paragraph.double_deck_card.field_body_secondary.yml, config/sync/field.field.paragraph.double_deck_card.field_heading.yml, config/sync/language.content_settings.paragraph.double_deck_card.yml
https://cm-jira.usa.gov/browse/VOTE-2375
Enable translation on double deck card component
1. visit http://vote-gov.lndo.site/guide-to-voting/after-felony-conviction
2. Edit the page and add a double deck card in english and publish
3. Create a new translation of the page for spanish
4. Edit the double deck card content and publish
5. Confirm that you can save without error and that the spanish content shows on the spanish page and the english content on the english page
=> VOTE-2375 Enable translation on double deck card component

config/sync/core.entity_form_display.paragraph.registration_tool.default.yml, config/sync/core.entity_view_display.paragraph.registration_tool.default.yml, config/sync/field.field.paragraph.registration_tool.field_no_results_message.yml, config/sync/field.storage.paragraph.field_no_results_message.yml, web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
[VOTE-2370](https://cm-jira.usa.gov/browse/VOTE-2370)
Adds a field to the registration tool paragraph type to allow admin translation for the no results message. English and Spanish content/translation will need to be added after merging.
1. Add English content for the field:
"No matching results. Please check spelling."
2. Add English content for the field:
"No hay resultados. Por favor, revise bien la ortografía."
2. Navigate to http://vote-gov.lndo.site/register
3. Edit page
4. Edit State Registration Tool
5. Add string in "No Results Message" field and save
6. Translate field to Spanish
7. Test by typing nonsense into the State Registration Tool :-)
=> VOTE-2370: Add 'No Results Message' field to Registration Tool

config/sync/user.role.content_translator.yml, config/sync/views.view.global_blocks.yml, config/sync/views.view.site_alerts.yml, web/modules/custom/vote_utility/inc/form_alter.inc
https://cm-jira.usa.gov/browse/VOTE-2243
https://cm-jira.usa.gov/browse/VOTE-2247
Remove translator access to edit blocks.
Remove translator access to edit user profile.
1. Login and create a new test user with the role of content translator
2. Logout and login in as the content translator user
3. visit http://vote-gov.lndo.site/admin/content and confirm you only see the "content" tab and no "block" related tabs are available.
4. try to edit your user profile by click on your username in the admin toolbar and clicking on "edit profile" and make sure the fields are disabled.
=> VOTE-2247 Remove translator access to edit block content

web/modules/custom/vote_utility/translations/es.po
[VOTE-2371](https://cm-jira.usa.gov/browse/VOTE-2371)
Added three aria-label translations for the Spanish version of the "Register to vote" page. Two of the translations appear on the page, as seen below:
For one of the translations ("Select your state or territory" --> "Seleccione su estado o territorio") there is no English aria-label that says "Select your state or territory," so it does not appear on the page.
1. Run `lando retune` after pulling to ensure that the translations are updated.
1. Load the home page of the site, and switch to Spanish using the language selector
2. Navigate to the Register to vote page using the button on the home page
3. Using Chrome dev tools or WAVE, ensure that the first two translated aria-labels appear as expected on the vote-registration-tool …
=> VOTE-2371: Add Spanish Aria Labels

web/modules/custom/vote_utility/translations/es.po, web/themes/custom/votegov/templates/component/feature-cards.html.twig
https://cm-jira.usa.gov/browse/VOTE-2411
Fix the typo found in the overseas voter card
1. In the root folder of the repo, **lando retune**
2. cd into web/themes/custom/votegov, **npm run build**
1. Visit the homepage in English, and confirm the overseas voter card has the typo (space between "citizen and "from")
2. Select Spanish from the language dropdown, and confirm the overseas voter card translates
=> VOTE-2411 Fix typo in overseas voter card

.circleci/config.yml
[Vote-2421](https://cm-jira.usa.gov/browse/VOTE-2421)
Adding a delay to the rerun tests if the first one fails... the goal is to help address any issues with a upkeep command and the site not building 
n/a
1. verify that the sleep command is added to the rerun steps
=> Adding a sleep command to wait to rerun any failed test

web/themes/custom/votegov/templates/taxonomy/taxonomy-term--basics-modules.html.twig
[VOTE-2418](https://cm-jira.usa.gov/browse/VOTE-2418)
Fix bug with Basic Modules taxonomy term page. Add default handling of header tag when the term is not loaded from a parenting paragraph.
1. Go to the taxonomy admin page for Basic Modules and view the list of terms.
2. Click on any term to view its page.
3. Confirm that the page loads and no error is displayed.
4. Confirm that the headings are shown as H2's.
5. Goto /guide-to-voting and locate a Basic Modules block (ie. taxonomy/52 which is Voting In Person).
6. Confirm that the heading for (ie Voting In Person) is shown as H3.
=> VOTE-2418: Resolve issue with taxonomy page loading

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-2391
Change the format of the election date to match format of the registration deadlines. 
Single digits are expressed as "5", not "05".
1. Visit http://vote-gov.lndo.site/register/colorado and confirm the election day format is changed to match the rest rest of the dates.
2. Switch to Spanish, and confirm the dates match the Spanish format and translation.
=> VOTE-2319 Change date format for election day to long date

testing/cypress/e2e/frontEndTests/accessability-toolbar.cy.js, testing/cypress/e2e/frontEndTests/state-pages.cy.js, web/themes/custom/votegov/templates/layout/page.html.twig
[Vote-2364](https://cm-jira.usa.gov/browse/VOTE-2364)
Adding test coverage for accessibility tool bar -> verifying the presence of the component, that the expected theme is added when clicked and that the selection is persistent across pages.
1. cd into `testing` and run `npm i`
2. run `npm run cy:open` and select the `accessability-toolbar.cy.js` test and verify that the test is passing 
3. return back to your cli and run `npm run cy:frontEnd` and verify that all tests are passing
=> Vote-2364:  Test coverage for accessibility toolbar

web/themes/custom/votegov/templates/component/usa-identifier.html.twig, web/themes/custom/votegov/templates/component/usagov-partner.html.twig
https://cm-jira.usa.gov/browse/VOTE-2443
Direct hardcoded usa.gov links in the footer to the Spanish site when the translation is set to Spanish.
1. Visit the homepage, and switch to Spanish. Confirm the usa.gov logo and the Visit usa.gov link goes to their Spanish site.
2. Switch to English, confirm the links still direct to the English site.
=> VOTE-2443 Replace spanish usa.gov links in the footer

web/themes/custom/votegov/templates/navigation/links--language-block.html.twig
[VOTE-2381](https://cm-jira.usa.gov/browse/VOTE-2381)
Add correct `lang` attribute to span surrounding name in language switcher. Note that the ticket asks for both lang and xml:lang but we found twig does not support the deprecated xml:lang attribute so it's not being included. This was approved by Ray. source: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
2. inspect langauge name inside of language switcher list
3. confirm correct attribute for "lang" is wrapping the name (compare to ticket and vote.gov)
=> VOTE-2381: Add 'lang' attribute to language names

config/sync/pathauto.settings.yml
https://cm-jira.usa.gov/browse/VOTE-2491
Allow 'of' in auto generated aliases
1. Create a new basic page with the title 'Title of page' and make sure the checkbox for auto generating the alias is checked. Then save.
2. Confirm that the alias reads `/title-of-page`
=> BUGFIX: remove 'of' from alias ignore settings

docs/README.md, scripts/upkeep, testing/pipeline.config.js
[VOTE-970](https://cm-jira.usa.gov/browse/VOTE-970)
Insert a brief summary of the changes included in this PR and any additional information or context which may help the reviewer.
1. Allow upkeep to run after the deploy
2. Verify URI is correct in the static site for the env.
=> VOTE-970: update URIs as preparation for launch

web/themes/custom/votegov/src/sass/components/a11y-toolbar.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss
[VOTE-2520](https://cm-jira.usa.gov/browse/VOTE-2520)
Adjust stacking order of language selector list so that a11y tools are not overlapping when it is open
1. Navigate to any page with more than 2 languages
2. Select language selector to open list
3. Confirm a11y tools do not stack on top of language selector
4. Confirm no regressions with stacking order of other elements
Before
Now
=> VOTE-2520: Increase banner z-index to hide a11y tools

config/sync/core.entity_view_display.media.image.scaled.yml, config/sync/core.entity_view_mode.media.scaled.yml, config/sync/filter.format.basic_html.yml
[VOTE-2341](https://cm-jira.usa.gov/browse/VOTE-2341)
Remove the ability to embed audio, document, icon and video from the wysiwyg. Only image is available.
1. Pull up any wysiwyg editor and confirm only image media type is available to embed
Before
Now
=> VOTE-2380: Only allow 'image' as embedded option in WYSIWYG

scripts/pipeline/downsync-backup.sh, scripts/pipeline/downsync-restore.sh, scripts/pipeline/scheduled_backup.sh
[VOTE-2184](https://cm-jira.usa.gov/browse/VOTE-2184)
Add timestamps between steps of the two downsync and one backup scripts
1. After merged, look at the pipeline runs for scheduled backups and run a downsync.
2. Ensure timestamps are output to the pipeline.
=> VOTE-2184: add timestamps between steps of the downsync and backup scripts

.circleci/config.yml
[VOTE-2530](https://cm-jira.usa.gov/browse/VOTE-2530)
[VOTE-2531](https://cm-jira.usa.gov/browse/VOTE-2531)
Add approvals to all post deploy upkeeps and an approval for the cypress job in stage.
1. Observe pipeline.
2. In dev, a manual approval should be required for the post deploy upkeep job.
3. In stage, a manual approval should be required for the post deploy upkeep job and the cypress job that follows.
=> VOTE-2530-2531: add approvals to some post deploy steps in the pipeline

config/sync/metatag.metatag_defaults.global.yml
[VOTE-2517](https://cm-jira.usa.gov/browse/VOTE-2517)
Fixes file path extension in config for the favicons being fetched by apple/safari
2. visit site in safari
3. confirm favicons are being fetch
4. confirm no errors
=> VOTE-2517: Fix favicon path file extension

web/themes/custom/votegov/src/sass/uswds-overrides/usa-language-selector.scss, web/themes/custom/votegov/templates/navigation/links--language-block.html.twig
[VOTE-2518](https://cm-jira.usa.gov/browse/VOTE-2518)
Excluded navajo font from language selection.
1. Load up the local site
2. Open up the language selector dropdown
3. Click on Dine (Navajo)
4. Verify that the strings look normal (shown below) and no special characters
- [] QA/Test steps were successfully completed, if applicable.
- [] Applicable logs are free of errors.
=> VOTE-2518: Excluded navajo font from language selection

web/sites/default/settings.cloudgov.php
[VOTE-2415](https://cm-jira.usa.gov/browse/VOTE-2415)
Enable state_cache in Drupal for cloud environments.
n/a
1. Login as an administrator, go to /admin/reports/status and confirm that State Cache is enabled.
Note: This is not enabled for local environments as you will need to add `$settings['state_cache'] = TRUE;` to your local settings file.
=> VOTE-2415: Enable state_cache for cloud environments.

web/themes/custom/votegov/src/sass/components/a11y-toolbar.scss
[Vote-2546](https://cm-jira.usa.gov/browse/VOTE-2546)
Addressing issue with the tool bar growing in scale if a user were to toggle the large text option
This was done by:
- setting a explicit height and width for each button 
- setting a max height and width for the icon 
- addressing an issue with the tool bar shift on the screen and making it more fixed on the screen for both desktop and mobile 
<details>
<summary>screen shots</summary>
<br>
A before and after 
</details>
1. cd into the `votegov` theme and run `lando retune`
1. select the large text options in the A11y tool bar and verify that it does not grow in scale.. also can look at the current site for reference of the old behavior.
=> Vote-2546: add styles to help tool bar not grow in size

scripts/upkeep
[VOTE-2534](https://cm-jira.usa.gov/browse/VOTE-2534)
Download static files from current static site before running tome generation during deployment. Prevent tome from having to generate every file that is missing from the static export directory.
1. n/a
1. Once merged, review the completed executed time for post-deploy-upkeep pipeline step and determine if it is less than previous times.
2. Additionally, you do a manual test in the environment by removing the html directory and then run the scripts/upkeep script.
3. Confirm that the files from the static site are downloaded to the html directory before tome is executed.
4. Confirm that the number of files that are generated are less that the total found paths 2000+.
=> VOTE-2534: Update upkeep script to download current static files before running tome

web/modules/custom/vote_utility/translations/es.po, web/themes/custom/votegov/templates/component/feature-cards.html.twig
https://cm-jira.usa.gov/browse/VOTE-2718
Give hardcoded FVAP cards unique links for English. Spanish links remain the same.
1. On the English homepage, confirm the FVAP cards link to the corresponding links in the ticket.
2. On the Spanish homepage, confirm both cards go to the translated material link.
3. Confirm the overseas guide title is "Votar como ciudadano en el extranjero."
=> VOTE-2718 Update FVAP card links in english

web/themes/custom/votegov/templates/component/hero.html.twig, web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--hero.html.twig
[VOTE-2054](https://cm-jira.usa.gov/browse/VOTE-2054)
- migrates hero into it's own component template 
- passes content with variables between paragraph template and hero component
- includes new hero component on voter guide template
2. go to landing page and confirm hero works as expected
3. go to voter guide page and confirm works as expected
=> VOTE-2054: update hero template to handle variations

testing/cypress/e2e/externalLinks/external-links-validator.cy.js, testing/cypress/e2e/internalLinks/internal-links-validator.cy.js, testing/cypress/fixtures/site-pages.json
[Vote-2699](https://cm-jira.usa.gov/browse/VOTE-2699)
This Pr will revert the link validation tests to the pervious set up and add the new content pages to the `site-pages.json` files.
There will been to be a bit more work to see if there is a better way to run this test dynamically... the updated version was taking quite some time to run and was not giving a good test run. 
na
1. cd into `testing` and run `npm run cy:proofer` and verify that test is running and all links are passing as well
=> Vote-2699: Update to link validation tests

web/themes/custom/votegov/src/sass/uswds-overrides/usa-card.scss
[VOTE-2741](https://cm-jira.usa.gov/browse/VOTE-2741)
Splits the card styles that just apply to the feature cards from the rest of the styles that the nvrf also inherits from.
2. visit landing page
3. test feature cards on all screen sizes, confirm no changes
4. visit http://vote-gov.lndo.site/register/washington/mail-in-form-filler
5. navigate to the second page
6. confirm the cards inherit the same styles *the mobile cards should stack and not change visually
=> VOTE-2741: split feature card styles from all card styles

composer.json, composer.lock, config/local/config_split.patch.core.extension.yml, config/local/stage_file_proxy.settings.yml, config/sync/stage_file_proxy.settings.yml
[VOTE-2275](https://cm-jira.usa.gov/browse/VOTE-2275)
Enables and configures stage file proxy module so images are pulled from production site
2. On line 171 of `web/sites/settings.local.php` change `.production` to `.local` so it is like this: `$config['config_split.config_split.local']['status'] = TRUE;`
3. run lando drush cim
4. Navigate to any state page and confirm the missing hero images are now coming through
=> VOTE-2275: Enable and configure stage file proxy

testing/cypress/e2e/frontEndTests/language-selector.cy.js, testing/cypress/fixtures/language-options.json
[Vote-2123](https://cm-jira.usa.gov/browse/VOTE-2723)
Adding test to check the language options and verify that the expected options are active and have not been removed. 
**Goal of test:**  This test will reference the current list of active translations by targeting the `data-lang` attribute and checking the list that is on the site compared to the json file that is saved
n/a
1. log in as an admin and visit `/es/node/91/edit` and unpublished this translation 
2. go to your terminal and cd into `testing` and run `npm run cy:open` and select the `language-selector.cy.js` test and verify that it is failing 
3. go back to the admin page and republish the spanish translation and rerun the test.. it should now be passing
=> Vote-2123: Verify Language options are active

testing/cypress/e2e/frontEndTests/accessability-toolbar.cy.js, testing/cypress/e2e/frontEndTests/email-signup.cy.js, testing/cypress/e2e/frontEndTests/footer-contact.cy.js, testing/cypress/e2e/frontEndTests/government-banner.cy.js, testing/cypress/e2e/frontEndTests/language-selector.cy.js, testing/cypress/e2e/frontEndTests/menu.cy.js, testing/cypress/e2e/frontEndTests/nvrf-download.cy.js, testing/cypress/e2e/frontEndTests/search-bar.cy.js, testing/cypress/e2e/frontEndTests/state-pages.cy.js, testing/cypress/e2e/frontEndTests/state-registration.cy.js, testing/cypress/fixtures/testing-page.json, testing/cypress/support/pageObjects.js
[Vote-2825](https://cm-jira.usa.gov/browse/VOTE-2825)
Updating frontend tests to utilize page objects.  The goal of of this is to help with troubleshooting and being able to maintain tests if an update is needed. This also allows us to reuse testing objects in multiple tests or the same if they are reused. 
n/a
1. pull down locally
2. cd into `testing` and run `npm run cy:frontEnd` and verify that tests are still passing
=> Vote-2825: Migrate Frontend tests to use page objects

web/data/es/navigation.json, web/data/es/strings.json, web/modules/custom/vote_nvrf/package-lock.json, web/modules/custom/vote_nvrf/package.json
HOTFIX release updating NVRF to v0.17.2
=> VOTE-2362 update to NVRF v0.17.2

config/sync/core.entity_form_display.block_content.registration_form_selector.default.yml, config/sync/core.entity_view_display.block_content.registration_form_selector.default.yml, config/sync/field.field.block_content.registration_form_selector.field_digital_form_link_label.yml, config/sync/field.field.block_content.registration_form_selector.field_enable_digital_form_link.yml, config/sync/field.storage.block_content.field_enable_digital_form_link.yml, web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig, web/themes/custom/votegov/templates/component/button.html.twig, web/themes/custom/votegov/templates/component/hero.html.twig
https://cm-jira.usa.gov/browse/VOTE-2822
Added a new checkbox to enable or display the NVRF link from the state page.
I also cleaned up an issue with the button component.
1. visit http://vote-gov.lndo.site/admin/content/block/3?destination=/admin/content/block and check the new box in the digital form group.
2. visit http://vote-gov.lndo.site/register/washington and make sure the text and link are showing
3. visit http://vote-gov.lndo.site/admin/content/block/3?destination=/admin/content/block and uncheck the new box 
4. visit http://vote-gov.lndo.site/register/washington and make sure the text and link are not showing
5. try this in another language
=> VOTE-2822 add checkbox to enable NVRF link

web/themes/custom/votegov/src/sass/base/link.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-form.scss
[Vote-2841](https://cm-jira.usa.gov/browse/VOTE-2841)
Addressing a hover style for links within the NVRF app.  When links were active there was no contrast between the background and text color 
**Solution** Updated the USWDS override file for `usa-form` and used the same styles from other link hover effects 
Before and After:
1. cd into the `votegov` theme and run `npm run build`
1. Start up local and visit a state page and start the digital form 
2. Fill out form and go to the last page for delivery and scroll to the section `A few important notes` and both links `type of identification` and `guide to voting`.  
3. click on the links or use your dom and turn on `:active` state and verity that the correct styles are being applied
=> Vote-2841: Hover style fix - NVRF Links

web/themes/custom/votegov/src/sass/base/link.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-form.scss
[Vote-2909](https://cm-jira.usa.gov/browse/VOTE-2909)
Addressing a bug that was added after the NVRF link hover styles were added.  This will fix the issues with links styled as buttons losing the text color after being visited 
https://github.com/user-attachments/assets/a30eeb0d-54a1-4e9c-82e4-9c4b1da7ef43
1. cd into the `votegov` theme and run `npm run build` and clear cache 
1. Spot check site to ensure no other links have regression added 
2. visit the log in page and verify that the button has been fixed 
3. visit the NVRF form and verify that the original fix is still applied [see this pr for reference](https://github.com/usagov/vote-gov-drupal/pull/989)
=> Vote-2909: Regression fix for link styles

web/modules/custom/vote_nvrf/package-lock.json
Reverts usagov/vote-gov-drupal#992
ticket [Vote-2619](https://cm-jira.usa.gov/browse/VOTE-2916)
=> Vote-2619: Revert "Bump vite from 4.5.3 to 4.5.5 in /web/modules/custom/vote_nvrf"

config/sync/core.entity_form_display.block_content.email_signup.default.yml, config/sync/core.entity_form_display.block_content.government_banner.default.yml, config/sync/core.entity_form_display.block_content.search.default.yml, config/sync/core.entity_form_display.paragraph.registration_tool.default.yml, config/sync/core.entity_view_display.block_content.email_signup.default.yml, config/sync/core.entity_view_display.block_content.government_banner.default.yml, config/sync/core.entity_view_display.block_content.search.default.yml, config/sync/core.entity_view_display.paragraph.registration_tool.default.yml, config/sync/field.field.block_content.email_signup.field_section_identifier.yml, config/sync/field.field.block_content.government_banner.field_section_identifier.yml, config/sync/field.field.block_content.search.field_section_identifier.yml, config/sync/field.field.paragraph.registration_tool.field_section_identifier.yml, config/sync/field.field.paragraph.registration_tool.field_state_list_identifier.yml, config/sync/field.storage.block_content.field_section_identifier.yml, config/sync/field.storage.paragraph.field_section_identifier.yml, config/sync/field.storage.paragraph.field_state_list_identifier.yml
https://cm-jira.usa.gov/browse/VOTE-2585
Add new data fields for string translations
1. check to make sure new fields were added to the data model based on the documentation linked in the ticket.
=> VOTE-2585 add data fields for string translations

config/sync/core.entity_form_display.block_content.registration_form_selector.default.yml, config/sync/core.entity_view_display.block_content.registration_form_selector.default.yml, config/sync/field.field.block_content.registration_form_selector.field_pdf_description.yml, config/sync/field.storage.block_content.field_pdf_description.yml, web/themes/custom/votegov/templates/block/block-content--registration-form-selector.html.twig
[VOTE-2846](https://cm-jira.usa.gov/browse/VOTE-2846)
Replace NVRF PDF link - Description field to be a wysiwyg and not a text field
The first step in this process is to add the new field and later migrate the data on prod before we delete the old description. This PR adds thew new field and updates the template with the new machine name. 
2. Visit a state page with the registration form selector (Alaska is one)
3. Confirm data in the field comes through
4. Confirm field uses a wysiwig editor
=> VOTE-2846: Configure wysiwyg description field

config/sync/views.view.nvrf_api.yml
[VOTE-2902](https://cm-jira.usa.gov/browse/VOTE-2902)
Update NVRF API view to include a dynamic state specific data view.
1. Locally, run `lando retune` to install updates.
1. Goto /nvrf/assets/states/{state_abbreviation}/data.json
2. Replace {state_abbreviation} with a state (ie. nj) and confirm that the correct json data is loaded.
3. Test the same url with translation /{langcode}/nvrf/assets/states/{state_abbreviation}/data.json
4. Repeat step 2
=> VOTE-2902: Add state specific nvrf api data endpoint.

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-2886
Configure the display of the "In Person" registration card
1. Login as admin and create a "State content display" block. Set the general in-person fields for English and Spanish. Use the content in [this document](https://docs.google.com/document/d/1TVAf-R2nLTKh7kmCTe3mBKSqWn8hcGr1TsjirdCXptQ/edit#heading=h.w121gvnnkl64).
2. View the English Alabama page and confirm the "In-person" block displays with the corresponding content.
3. View the Spanish Alabama page and confirm the "In-person" block displays with the corresponding content.
4. Verify the registration date correctly displays for both English and Spanish.
5. Edit the Alabama page. Uncheck the "in-person" registration checkbox.
6. Confirm the "in-person block does not display …
=> VOTE-2886 state enhancement in person

config/sync/core.entity_view_display.block_content.state_display_content.default.yml, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-2883
Create a template for the new State Display content block.
Display the election date field with hardcoded content.
1. Login to admin and create a new State Display Content block. http://vote-gov.lndo.site/admin/content/block
2. Set the Election Date and the Election text for English and Spanish. You don't have to fill out optional fields. 
3. Visit http://vote-gov.lndo.site/register/alabama and confirm the election date display matches the designs.
4. Test English and Spanish and confirm the election date translates. 
5. Go back to the State Display Content block. Unset the election date.
6. View the state page again and confirm all content for the election date no longer displays.
=> VOTE-2883 state page updates elections date

config/sync/core.entity_form_display.block_content.state_display_content.default.yml, config/sync/core.entity_view_display.node.state_territory.full.yml, web/modules/custom/vote_fields/config/schema/vote_fields.schema.yml, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/StateContentWidget.php, web/themes/custom/votegov/templates/component/info-card.html.twig, web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-2885
1. Add ability to hide state display content subfields from the form
2. Configure state mail registration section
1. visit http://vote-gov.lndo.site/block/add/state_display_content and confirm that the 'Link text' subfield is hidden for Registration Intro field.
2. visit http://vote-gov.lndo.site/register/washington and confirm the content for mail and NVRF displays
3. visit http://vote-gov.lndo.site/register/wyoming and confirm the content for mail displays but not NVRF
=> VOTE-2885 configure state mail registration section

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
[Vote-2887](https://cm-jira.usa.gov/browse/VOTE-2887)
Setting up config for the outside of us info card on state pages.
1. Log into site and create a new state page, go to the `State Display` content tab 
2. Scroll to the `Military and overseas registration` and add text - skip the link text that will need to be addressed in the future
3. Visit page and check that it is matching the design in the figma
=> Vote-2887: Config for Outside US Info Card

web/themes/custom/votegov/src/sass/components/page-content.scss
[VOTE-2965](https://cm-jira.usa.gov/browse/VOTE-2965)
Solves the bug causing longer links to not wrap properly on voter guide pages and new state enhancement pages. This issue was identified during https://cm-jira.usa.gov/browse/VOTE-2888 
Before
Now
Now
1. Edit a voter guide page
2. Add https://www.alabamainteractive.org/sos/voter_registration/voterRegistrationWelcome.action to the body somewhere
3. Confirm it wraps on smaller screen sizes
=> VOTE-2965: Fix body text wrap

testing/cypress/e2e/backEndTests/basic-page.cy.js, testing/cypress/e2e/backEndTests/content-editor-access.cy.js, testing/cypress/e2e/backEndTests/content-manager-access.cy.js, testing/cypress/e2e/backEndTests/footer-menu-editor.cy.js, testing/cypress/e2e/backEndTests/site-admin-access.cy.js, testing/cypress/e2e/backEndTests/user-content-access.cy.js, testing/cypress/support/pageObjects.js, web/themes/custom/votegov/templates/navigation/menu-local-task.html.twig
[Vote-2826](https://cm-jira.usa.gov/browse/VOTE-2826)
This Pr will update the Cypress backend test to use page objects and allow it to use the same process as frontend tests 
1. 'lando retune'
1. cd into `testing` and run `npm i`
2. run `npm run cy:backEnd` and verify that tests are still passing
=> Vote-2826: Migrate Cypress Backend Test to Page Objects

web/themes/custom/votegov/src/sass/uswds-overrides/usa-site-alert.scss
[Vote-2990](https://cm-jira.usa.gov/browse/VOTE-2990)
Updating link color for emergency banner.  
<details>
<summary>Before and After</summary>
**Before:**
**After:**
</details>
Solution:
- Adjusted base color to be white, and added hover affect to match the [USWDS Component](https://designsystem.digital.gov/components/site-alert/)
1. cd into the `votegov` theme and run `npm run build`
1. visit `block/add/sitewide_alert?destination=/admin/content/site-alerts` and add a new `Emergency` banner
2. when adding text be sure to create a link in order to have the proper text show up 
3. verify that the link text is white and that there is a hover affect as well when you hover over it
=> Vote-2990: Link Style Update to Emergency Banner

config/sync/core.entity_form_display.block_content.state_display_content.default.yml, config/sync/core.entity_view_display.block_content.state_display_content.default.yml, config/sync/field.field.block_content.state_display_content.field_no_online_registration.yml, config/sync/field.storage.block_content.field_no_online_registration.yml, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
[Vote-2957](https://cm-jira.usa.gov/browse/VOTE-2957)
Adding a new content field to the State display content block to to display content when a state does not offer online registration. 
Please note: I have added the option for a button, after talking with Susan she was not sure if they would like one or not but something we can remove later on. 
1. run `lando retune` and cd into the `votegov` theme and run `npm run build`
1. create a new state display content block `/block/add/state_display_content?destination=/admin/content/block` and verify that there is a field type for no online registration. 
2. add text to this field, please reach out if you need some dummy text and I can provide it for you. 
3. visit a state page and uncheck `online registration` return back to the page and …
=> Vote-2957: No Online Registration

config/sync/core.entity_form_display.block_content.state_display_content.default.yml, config/sync/core.entity_view_display.block_content.state_display_content.default.yml, config/sync/field.field.block_content.state_display_content.field_no_mail_registration.yml, config/sync/field.storage.block_content.field_no_mail_registration.yml, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
[Vote-2958](https://cm-jira.usa.gov/browse/VOTE-2958)
Adding a new field for no mail registration setting this up as well to allow a button if needed but can remove later on if that is the decision made
1. run `lando retune` and cd into the `votegov` theme and run `npm run build`
1. create a new state display content block `/block/add/state_display_content?destination=/admin/content/block` and verify that there is a field type for no mail registration. 
2. add text to this field, please reach out if you need some dummy text and I can provide it for you. 
3. visit a state page and uncheck `mail registration` return back to the page and verify that the text that was inputted for that field is showing.
=> Vote-2958: No mail registration block

web/themes/custom/votegov/src/sass/components/call-out-box.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-2972
Add the confirm registration component to the side bar.
2. cd into theme, npm run build
1. Add confirm registration content to the defaulr state display content block (note: the id might be different on your local)
http://vote-gov.lndo.site/admin/content/block/23?destination=/admin/content/block
2. Visit the Alabama state page, and confirm the block content displays in the side nav.
3. Confirm that the confirm block in the side nav matches the designs.
4. Confirm the side navigation works correctly, and that only the confirm block at the top of the page is linked.
5. Open Chrome dev tools and view in mobile and tablet sizes. Confirm the entire side nav (links and confirm block) do not display).
=> VOTE-2972 additional check reg box

scripts/upkeep, web/modules/custom/vote_nvrf/src/Controller/NvrfPageController.php, web/modules/custom/vote_nvrf/vote_nvrf.routing.yml
[VOTE-2962](https://cm-jira.usa.gov/browse/VOTE-2962)
Create a custom page with an index of state data points for Tome to access and generate static pages for.
- Locally, run lando retune to install updates.
- Goto /state-data-points-index and confirm that an index of state links displays pointing to /{langcode}/nvrf/assets/states/{state_abbreviation}/data.json
- From the console, run `lando drush tome:static`
- Confirm that the static directories are created under the following directory structure
html/{langcode}/nvrf/assets/states/{state_abbreviation}/data.json
=> VOTE-2962: Add state data points index page for Tome generation.

.circleci/config.yml, scripts/pipeline/downsync-preprod.sh, scripts/upkeep
[VOTE-2997](https://cm-jira.usa.gov/browse/VOTE-2997)
[VOTE-3029](https://cm-jira.usa.gov/browse/VOTE-3029)
[VOTE-3033](https://cm-jira.usa.gov/browse/VOTE-3033)
* Update timeout for potentially long running pipeline jobs to not be canceled when there is no output
* Before the upkeep script runs tome, run drush cr
* Add updb and cim to downsync-preprod script
1. Allow deploy to happen
2. Confirm Deploy and Post Deploy steps do not cancel at 10 minutes (this doesn't often happen)
3. Confirm post deploy upkeep is able to complete successfully and generate the static site as intended
4. Run a manually triggered downsync-backup workflow to use the downsync-preprod script and ensure database/site is updated properly without need for further steps in the CMS
=> VOTE-2998-3029-3033: updates to pipeline timeout, upkeep and downsync

config/sync/system.action.user_add_role_action.archived.yml, config/sync/system.action.user_remove_role_action.archived.yml, config/sync/user.role.archived.yml
https://cm-jira.usa.gov/browse/VOTE-3007
Add new Archived role for offboarded CMS users.
1. visit http://vote-gov.lndo.site/admin/people/roles and confirm you see the [ARCHIVED] role
2. visit http://vote-gov.lndo.site/admin/people/permissions/archived and confirm they have no permissions
=> VOTE-3007 Add new ARCHIVED role

config/sync/views.view.state_territory.yml, web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
https://cm-jira.usa.gov/browse/VOTE-3037
Hide state links in registration tool when the pages are unpublished or untranslated.
1. visit http://vote-gov.lndo.site/node/77/translations and add a translation for Japanese and confirm that the state list does not display on the page when you view it
2. visit http://vote-gov.lndo.site/node/8/translations and add a translation for Japanese and then visit http://vote-gov.lndo.site/ja/register and confirm only the link for Alaska displays in the list
=> VOTE-3037 Hide untranslated state links in registration tool

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-3006
This ticket fixes the following bug:
When the optional "link text" field is left empty in any of the registration content blocks, Drupal throws an error.
1. Go to http://vote-gov.lndo.site/admin/content/block/23?destination=/admin/content/block
2. Remove the "link text" from all blocks except "Check your registration".
3. View the Alabama page and confirm the blocks show up without the link buttons.
4. Edit Alabama and uncheck "Online" and "In person" registration types.
5. View the Alabama page and confirm the "no online" and "no in-person" blocks show without a link.
6. Edit Alabama and recheck "Online" and "In person" registration types. Uncheck the "mail" type.
7. View the Alabama page and confirm the "no mail" blocks shows …
=> VOTE-3006 empty link text bug

web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
[Vote-3051](https://cm-jira.usa.gov/browse/VOTE-3051)
Updating the not needed template to use the `@link` place holder like check registration.  
Also adding back the last updated field to template.  
1. `lando retune` and cd into `votegov` theme and run `npm run build`
1. visit `Alabama` and select the not needed registration type.. also be sure to update the `Not needed` content block as well
2. verify that content is displaying correctly
=> Vote-3051: not needed template update

web/modules/custom/vote_utility/translations/ja.po
[Vote-3054](https://cm-jira.usa.gov/browse/VOTE-3054)
Removing hard coded `2022` in the Japanese translation 
n/a
1. review file changes and check that 2022 has been removed form mail in string 
2. review .po file and ensure no other hard coded years are present
=> Vote-3054: Removed hard coded 2022 date from Japanese

config/local/config_split.patch.language.entity.ja.yml, config/production/config_split.patch.language.entity.ja.yml
[VOTE-3015](https://cm-jira.usa.gov/browse/VOTE-3015)
Enable Japanese language on local and production environments.
1. Update the following setting in web/sites/settings.local.php file to include or reflect
`$config['config_split.config_split.production']['status'] = TRUE;`
2. Run `lando retune` or `lando drush cim` to import the production configurations.
1. Login as an administrator
2. Goto /admin/config/regional/language and confirm that Japanese is not marked as disabled.
3. Goto the content admin page and identify any page that has been translated in Japanese.
4. View the translated page and confirm that the language selector button in the top right corner of the page includes Japanese as an option.
5. Logout and repeat Step 4.
=> VOTE-3015: Enable Japanese locally and on production.

config/sync/core.entity_form_display.block_content.state_display_content.default.yml, config/sync/core.entity_view_display.block_content.state_display_content.default.yml, config/sync/field.field.block_content.state_display_content.field_last_updated_label.yml, config/sync/field.field.block_content.state_display_content.field_postmarked_mail_text.yml, config/sync/field.field.block_content.state_display_content.field_received_mail_text.yml, config/sync/field.storage.block_content.field_last_updated_label.yml, config/sync/field.storage.block_content.field_postmarked_mail_text.yml, config/sync/field.storage.block_content.field_received_mail_text.yml
https://cm-jira.usa.gov/browse/VOTE-3125
Add 3 new fields to the state display content block type:
- last updated label
- postmarked deadline text
- received deadline text
1. visit http://vote-gov.lndo.site/admin/content/block/23 and see the new fields
2. Confirm that they can be translated
=> VOTE-3125 add shared fields to state display content block type

config/sync/block_content.type.state_display_content.yml, config/sync/core.entity_form_display.block_content.state_display_content.default.yml, config/sync/core.entity_form_display.node.state_territory.default.yml, config/sync/core.entity_view_display.block_content.state_display_content.default.yml, config/sync/field.field.block_content.state_display_content.field_display_title.yml, config/sync/field.field.block_content.state_display_content.field_election_text.yml, config/sync/field.field.block_content.state_display_content.field_enable_digital_form_link.yml, config/sync/field.field.block_content.state_display_content.field_mail_reg_deadline_label.yml, config/sync/field.field.block_content.state_display_content.field_online_reg_deadline_label.yml, config/sync/field.field.block_content.state_display_content.field_person_reg_deadline_label.yml, config/sync/field.storage.block_content.field_mail_reg_deadline_label.yml, config/sync/field.storage.block_content.field_online_reg_deadline_label.yml, config/sync/field.storage.block_content.field_person_reg_deadline_label.yml, web/modules/custom/vote_fields/config/schema/vote_fields.schema.yml, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/StateContentWidget.php
https://cm-jira.usa.gov/browse/VOTE-2961
Add helptext features to state page enhancement fields and data types. Add missing fields for:
- deadline labels
- toggle display digital form filler tool
1. Visit http://vote-gov.lndo.site/admin/content/block/23 and see the new fields
2. Confirm the content is in collapsible groups now (requested by Susan)
3. Confirm the help text is applied to various fields in the form
4. Translate the block and make sure the new fields are translatable
5. Visit http://vote-gov.lndo.site/node/26/edit
6. Confirm the content in the State Display Content tab is collapsible
7. Confirm the help text is applied to various fields in the form
8. Translate the state and make sure experience is the same
=> VOTE-2961 Add help text for state display content fields

config/sync/core.entity_form_display.node.state_territory.default.yml, config/sync/core.entity_view_display.node.state_territory.default.yml, config/sync/core.entity_view_display.node.state_territory.full.yml, config/sync/core.entity_view_display.node.state_territory.teaser.yml, config/sync/field.field.node.state_territory.field_date_in_person_deadline.yml, config/sync/field.field.node.state_territory.field_date_online_deadline.yml, config/sync/field.storage.node.field_date_in_person_deadline.yml, config/sync/field.storage.node.field_date_online_deadline.yml
https://cm-jira.usa.gov/browse/VOTE-3133
Add new date deadline fields for the state content type
1. visit http://vote-gov.lndo.site/node/7/edit and check the deadline tab
2. You should see the 2 new fields
3. Make sure these fields are not translatable and they should not display anywhere on the state pages yet.
=> VOTE-3133 Add new date deadline fields to state content type

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
This will ensure an empty override is treated as a value when other values are set.
https://cm-jira.usa.gov/browse/VOTE-3094
Overrides should be handled by block, not per field. When one override field in a block is set, all fields use the override values, even it empty.
To accomplish this, I removed the merge function.
1. Visit the Alabama page and confirm all the default state content displays.
2. Edit the Alabama page and set all the override fields. 
3. Confirm the override values display on the page.
4. Edit the Alabama page and delete one field value per registration type (a mix of headings, content, and link text)
5. Confirm that for each override field value deleted, no default content displays.
=> VOTE- 3094 Remove merge from override functions

manifest.yml, scripts/pipeline/cloud-gov-deploy.sh, scripts/pipeline/exports.sh
[VOTE-3126](https://cm-jira.usa.gov/browse/VOTE-3126)
Add SSO assertion encryption certs
1. Verify deploy completes successfully
2. check that `sso_assertion_cert` and `sso_assertion_key` env vars are exposed to the drupal app
=> VOTE-3126: add sso assertion certs

config/local/config_split.patch.user.role.site_builder.yml, config/sync/editor.editor.basic_html.yml, config/sync/filter.format.basic_html.yml
https://cm-jira.usa.gov/browse/VOTE-3081
Remove the underline and text-align buttons from the toolbar.
Remove the no longer allowed custom classes.
1. Login as admin
2. Create a new basic page
3. Confirm the underline and text align buttons are removed from the wysiwg.
=> VOTE-3081 Remove underline, text align, and not allowed tags

web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig
[Vote-3156](https://cm-jira.usa.gov/browse/VOTE-3156)
Address bug with heading for the not-needed template rendering `@state_name` and not the true state name
Screen shot of before and after 
1. run `lando retune` also cd into `votegov` theme and run npm run build
1. visit `North Dakota` and verify that the info card is rendering `North Dakota` and not `@state_name`
=> Vote-3156: Update Heading Placeholder for Not-Needed

web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-3157
A render error appeared after updating the latest db (11-21-2024). Last sprints the dates were reverted to be the general deadlines. 
I added a missing render filter to the general mail deadline variables.
1. lando db-import drupal_2024-11-21.sql
1. Visit http://vote-gov.lndo.site/register/alabama and confirm the general mail deadline renders correctly for both English and Spanish.
2. Edit the Alabama data to use a specific date for the mail dealine.
3. Confirm the specific mail deadline renders correctly.
4. Visit http://vote-gov.lndo.site/register/american-samoa and confirm that the mail deadline does not display.
=> VOTE 3157 Add render filter to the state mail deadline

testing/cypress/e2e/externalLinks/external-links-validator.cy.js, testing/cypress/e2e/internalLinks/internal-links-validator.cy.js
[Vote-3155](https://cm-jira.usa.gov/browse/VOTE-3155)
Updating link validation tests:
- Internal link -> setting up check to ensure that internal links do not have a trailing `/`
- both tests -> setting up to both hit the prod url, this is due to the pipeline running on prod and needed to check the live site for any broken links
n/a
**Please take a look at the file and check the comment at the top in regards to the baseurl**
1. log into the site and update a link on the home page (i suggest a link in the Quicklinks section) and adding a trailing `/`
2. cd into `testing` and run `npm run cy:open` and select the `internal links` test from the cypress runner and verify that the test is failing on the home page due to the trailing `/`
3.
=> Vote-3155: Updating link validation tests

.circleci/config.yml
[Vote-3142](https://cm-jira.usa.gov/browse/VOTE-3142)
Removing the `when:always` flag from the config.yml file.. according to [CircleCi Docs](https://circleci.com/docs/configuration-reference/#the-when-step) there is no need for an always flag since it will run no matter what unless you need to set a time. Such as on fail or something else. 
n/a
1. Review file and ensure there are no `when:always` flags present
=> Vote-3142: Remove when:always flag

config/sync/field.field.node.landing.field_metatags.yml, config/sync/field.field.node.page.field_metatags.yml, config/sync/field.field.node.state_territory.field_metatags.yml, config/sync/field.field.node.voter_guide.field_metatags.yml, web/modules/custom/vote_utility/inc/form_alter.inc
https://cm-jira.usa.gov/browse/VOTE-3075
https://cm-jira.usa.gov/browse/VOTE-3077
Add help text for meta tags and title field based on accessbility guidance.
1. visit http://vote-gov.lndo.site/node/add/page and confirm Title and meta tag help text has been added
2. visit http://vote-gov.lndo.site/node/add/landing and confirm Title and meta tag help text has been added
3. visit http://vote-gov.lndo.site/node/add/state_territory and confirm meta tag help text has been added
4. visit http://vote-gov.lndo.site/node/add/voter_guide and confirm Title and meta tag help text has been added
=> VOTE-3075 & VOTE-3077 meta tag help text and title help text

config/sync/language.content_settings.block_content.basic.yml, config/sync/language.content_settings.block_content.contact_identifier.yml, config/sync/language.content_settings.block_content.email_signup.yml, config/sync/language.content_settings.block_content.government_banner.yml, config/sync/language.content_settings.block_content.inline_alert.yml, config/sync/language.content_settings.block_content.nvrf_a_b_message.yml, config/sync/language.content_settings.block_content.nvrf_card.yml, config/sync/language.content_settings.block_content.partnership.yml, config/sync/language.content_settings.block_content.registration_form_selector.yml, config/sync/language.content_settings.block_content.search.yml, config/sync/language.content_settings.block_content.sitewide_alert.yml, config/sync/language.content_settings.block_content.state_display_content.yml
[Vote-3101](https://cm-jira.usa.gov/browse/VOTE-3101)
Enabled `Hide non translatable fields` for block types. 
1 run `lando retune`
1. Create a test block type for the following blocks and verify that when translated those fields are not available to the edited
- Basic block - classes 
- ab message - message id and touch points id
- Partnership - each logo
- Form selector - form link 
- Site alert - alert type
- State display - date
=> Vote-3101: Hiding non-translatable fields in block types

config/sync/editor.editor.simple_html.yml, config/sync/filter.format.simple_html.yml, web/themes/custom/votegov/templates/component/call-out-box.html.twig, web/themes/custom/votegov/templates/component/info-card.html.twig, web/themes/custom/votegov/templates/node/node--state-territory--not-needed.html.twig, web/themes/custom/votegov/templates/node/node--state-territory.html.twig
https://cm-jira.usa.gov/browse/VOTE-3149
Implement link attributes for google analytics.
1. Add data-state-ext attribute and values to links defined in the templates
2. Enable source code editing in the simple wysiwg editor (to allow the attribute to be added to links)
1. Visit http://vote-gov.lndo.site/admin/content/block/23?destination=/admin/content/block and edit the source code for the NVRF Details field.
2. Add data-state-ext="nvrf-mail-registration" to the anchor tag
3. Edit the source code of the military field.
4. Add data-state-ext="military-registration" to the anchor tag
5. Go to http://vote-gov.lndo.site/register/alabama and confirm all the data attributes are applied to links as defined in the ticket.
6. Go to http://vote-gov.lndo.site/node/62/edit
7. Edit …
=> Feature/vote 3149/state page data analytics

config/production/usagov_login.settings.yml
[VOTE-3153](https://cm-jira.usa.gov/browse/VOTE-3153)
Renames user login button to reflect the use of GSA Auth.
1. Locally change line 189 in sites/settings.local.php to include $config['config_split.config_split.production']['status'] = TRUE;
2. Locally run `drush cim`
1. Goto /user/login and confirm that the login button reads, "Proceed to GSA Auth login"
=> VOTE-3153: Update login button text.

config/production/config_split.patch.language.entity.nv.yml
[VOTE-3120](https://cm-jira.usa.gov/browse/VOTE-3120)
Disable Navajo translation on production.
1. Locally change line 189 in sites/settings.local.php to include `$config['config_split.config_split.production']['status'] = TRUE;`
2. Run `drush cim`
1. Review the site as a user and confirm that Navajo is not available in the language switcher located in the top right hand corner of the site.
2. Login as an administrator and goto /admin/config/regional/language and confirm that Navajo is marked as disabled.
=> VOTE-3120: Disable Navajo translation.

scripts/pipeline/deb-cf-install.sh
[VOTE-3173)](https://cm-jira.usa.gov/browse/VOTE-3173)
The CF CLI package URI changed and cannot be downloaded as previously done. Change the URI to one that can be downloaded.
1. Ensure the pipeline can install CF CLI.
=> VOTE-3173: change download link for CF CLI to adjust for upstream change

testing/cypress/e2e/internalLinks/internal-links-validator.cy.js, testing/cypress/fixtures/language-options.json
[Vote-3159](https://cm-jira.usa.gov/browse/VOTE-3171)
Minor update to tests:
1 - removed Navajo from tests due to it being disabled on the live site... this will need to be added back when it is active again 
2 - fixed excluded url to not check the base url if it is set since it will have a trailing `/` 
n/a
1. cd into `testing` and run `npm run cy:open` and select the `language-selector` test and the `internal links` test and verify that they are still passing.
=> Vote-3159: Minor Cypress test updates

web/themes/custom/votegov/templates/block/block-content--email-signup.html.twig, web/themes/custom/votegov/templates/block/block-content--government-banner.html.twig
https://cm-jira.usa.gov/browse/VOTE-3184
Update % placeholders to use @ for consistency. This will require updating the content in the CMS as a post-deploy step.
1. visit http://vote-gov.lndo.site/ and expand the government banner and see the % placeholders
2. edit the block http://vote-gov.lndo.site/admin/content/block/1 and replace %.gov% with @gov, replace %lock_icon% with @lock_icon and %https% with @https then save the block.
3. revisit http://vote-gov.lndo.site/ and expand the government banner and confirm the placeholders are being replaced correctly.
=> VOTE-3184 replace legacy % placeholders with @

web/themes/custom/votegov/src/sass/uswds-overrides/usa-card.scss
[Vote-3185](https://cm-jira.usa.gov/browse/VOTE-3185)
Addressing bug with Yupik text running past the container 
1. cd into the `votegov` theme and run `npm run build`
1. visit home page and change to Yupik translation and verify that test is no longer running past the card. 
2. spot check other translation to check for any regressions
=> Vote-3185: Yupik Text Fix

config/sync/field.field.block_content.basic.field_classes.yml, config/sync/field.field.block_content.basic.field_heading.yml, config/sync/field.field.block_content.email_signup.field_heading.yml, config/sync/field.field.block_content.inline_alert.field_heading.yml, config/sync/field.field.block_content.nvrf_card.field_button_label.yml, config/sync/field.field.block_content.nvrf_card.field_heading.yml, config/sync/field.field.block_content.partnership.field_heading.yml, config/sync/field.field.block_content.registration_form_selector.field_digital_form_link_label.yml, config/sync/field.field.block_content.registration_form_selector.field_heading.yml, config/sync/field.field.block_content.registration_form_selector.field_submit_button_label.yml, config/sync/field.field.paragraph.accordion_group.field_heading.yml, config/sync/field.field.paragraph.basic.field_classes.yml, config/sync/field.field.paragraph.basic.field_heading.yml, config/sync/field.field.paragraph.basics_block.field_heading.yml, config/sync/field.field.paragraph.double_deck_card.field_heading.yml, config/sync/field.field.paragraph.feature_cards.field_heading.yml, config/sync/field.field.paragraph.hero.field_heading.yml, config/sync/field.field.paragraph.hero.field_link.yml, config/sync/field.field.paragraph.image_text_cta.field_heading.yml, config/sync/field.field.paragraph.image_text_cta.field_link.yml, config/sync/field.field.paragraph.quicklinks.field_heading.yml, config/sync/field.field.paragraph.quicklinks.field_link.yml, config/sync/field.field.paragraph.registration_tool.field_heading.yml, config/sync/field.field.taxonomy_term.basics_modules.field_heading.yml, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/StateContentWidget.php
https://cm-jira.usa.gov/browse/VOTE-3079
https://cm-jira.usa.gov/browse/VOTE-3082
1. Add help text to heading fields from Amy's documentation
2. Add help text to the link text fields from Amy's documentation
1. visit http://vote-gov.lndo.site/admin/content/block/23 and check that help text was added to the heading fields and help text fields in the accordions.
=> VOTE-3079 VOTE-3082 help text improvements

scripts/upkeep
n/a
Remove from the upkeep script the command to copy the votegov theme fonts directory which no longer exists
n/a
1. Should not see any errors in cloud.gov logs indicating that the fonts directory was not found.
=> HOTFIX: Remove copying of theme's fonts directory in upkeep script.

scripts/pipeline/exports.sh
[VOTE-2992](https://cm-jira.usa.gov/browse/VOTE-2992)
Skip install of development packages by composer in every cloud env. Previously only enabled for test and dev.
1. Allow deployment pipeline to run.
2. Check installed modules to ensure no development packages were installed in dev and test.
=> VOTE-2992: set COMPOSER_NO_DEV=1 to skip development package installs in all cloud envs

web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig
[Vote-3138](https://cm-jira.usa.gov/browse/VOTE-3138)
This PR will hide the inpage nav for languages that use non latin characters to address the bug with no linking to headings 
- `lando retune`
1. visit a voter guide and switch between the various translation and ensure that the in page nav is hiding for the intended translations and is present and still working for the translations that use latin characters
=> Vote-3138: Set up inpage nav to not show for non latin translations

web/themes/custom/votegov/templates/layout/page--node--voter-guide.html.twig
[Vote-3138](https://cm-jira.usa.gov/browse/VOTE-3138)
Adding Korean that was left out by mistake to languages that do not need sidenav
1 - `lando retune`
1. visit a voter guide and check that Korean does not have the side nav
=> Vote-3138: Adding KO to sidenav fix

config/sync/block_content.type.nvrf_display_content.yml, config/sync/core.entity_form_display.block_content.nvrf_display_content.default.yml, config/sync/core.entity_view_display.block_content.nvrf_display_content.default.yml, config/sync/field.field.block_content.nvrf_display_content.field_confirm_group.yml, config/sync/field.field.block_content.nvrf_display_content.field_download_button_label.yml, config/sync/field.field.block_content.nvrf_display_content.field_edit_button_label.yml, config/sync/field.field.block_content.nvrf_display_content.field_mail_deadline_label.yml, config/sync/field.field.block_content.nvrf_display_content.field_not_required_label.yml, config/sync/field.field.block_content.nvrf_display_content.field_nvrf_step.yml, config/sync/field.field.block_content.nvrf_display_content.field_print_button_label.yml, config/sync/field.storage.block_content.field_confirm_group.yml, config/sync/field.storage.block_content.field_download_button_label.yml, config/sync/field.storage.block_content.field_edit_button_label.yml, config/sync/field.storage.block_content.field_mail_deadline_label.yml, config/sync/field.storage.block_content.field_not_required_label.yml, config/sync/field.storage.block_content.field_nvrf_step.yml, config/sync/field.storage.block_content.field_print_button_label.yml, config/sync/language.content_settings.block_content.nvrf_display_content.yml, config/sync/views.view.nvrf_api_blocks.yml, web/modules/custom/vote_fields/config/schema/vote_fields.schema.yml, web/modules/custom/vote_fields/src/Plugin/Field/FieldFormatter/ConfirmGroupDefaultFormatter.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldFormatter/NvrfStepDefaultFormatter.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldType/ConfirmGroupItem.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldType/NvrfStepItem.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/ConfirmGroupWidget.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/NvrfStepWidget.php
https://cm-jira.usa.gov/browse/VOTE-920
Create a new block type for managing nvrf strings
1. visit http://vote-gov.lndo.site/block/add/nvrf_display_content and add new block type content instance
2. translate the new block into Spanish and change some values but NOT the id fields
3. visit http://vote-gov.lndo.site/nvrf/assets/strings.json and confirm the english content is exposed
4. visit http://vote-gov.lndo.site/es/nvrf/assets/strings.json and confirm the spanish content is exposed
=> VOTE-920 create a new block type for managing nvrf strings

config/sync/core.entity_form_display.taxonomy_term.nvrf_field.default.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_content_version.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_display_label.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_error_message.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_help_text.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_instructions.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_nvrf_machine_name.yml, config/sync/field.field.taxonomy_term.nvrf_field.field_options.yml, web/modules/custom/vote_utility/inc/form_alter.inc
https://cm-jira.usa.gov/browse/VOTE-3189
Improvements to help text for nvrf fields taxonomy edit form.
1. Visit http://vote-gov.lndo.site/admin/structure/taxonomy/manage/nvrf_field/add
2. Review suggested changes to field labels & help text.
=> VOTE-3189 improve help text for nvrf fields taxonomy edit form

config/sync/user.role.authenticated.yml, config/sync/user.role.content_editor.yml, config/sync/user.role.content_manager.yml
https://cm-jira.usa.gov/browse/VOTE-2450
After auditing the permissions of the roles. I identified that there were some modifications needed. This work is captured here.
There are several changes here and difficult to write test cases for them all. A couple of things to note. Content Managers and Content Editors should no longer have permission to delete nodes, terms or media. Authenticated users only have the ability to view content. Content Editors can use the text format options.
=> VOTE-2450 role adjustments based on permission audit

web/themes/custom/votegov/src/js/touchpoints-click.js
https://cm-jira.usa.gov/browse/VOTE-3305
Problem: Fix a console error triggered by the touch points form mobile menu button
Solution: Closing the mobile menu before opening the modal 
1. cd into theme, npm run build
2. In main directory, lando retune
1. View vote.gov in mobile dimensions.
2. Turn on a screen reader
3. While the console is open, navigate to the touchpoints button within the mobile menu.
4. Click the touch points button and confirm there are no errors in the console.
5. Close the touchpoints modal and confirm there are no errors in the console.
=> VOTE-3305 ARIA hidden modal bug

web/themes/custom/votegov/templates/component/feature-cards.html.twig, web/themes/custom/votegov/templates/node/node--voter-guide--teaser.html.twig
https://cm-jira.usa.gov/browse/VOTE-2926
Replace title attr with aria-labelledby on featured card links. This fixes the issue with the title being read twice by screen readers.
1. visit http://vote-gov.lndo.site/ and use voiceover or screen reader tool to link to it read out each featured card link to make sure it only reads the title once.
=> VOTE-2926: Add aria-labelledby to featured card links

web/modules/custom/vote_fields/config/schema/vote_fields.schema.yml, web/modules/custom/vote_fields/src/Plugin/Field/FieldFormatter/NvrfStepDefaultFormatter.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldType/NvrfStepItem.php, web/modules/custom/vote_fields/src/Plugin/Field/FieldWidget/NvrfStepWidget.php, web/modules/custom/vote_fields/vote_fields.install
https://cm-jira.usa.gov/browse/VOTE-3337
Add new subfields for NVRF API to to prepare for transfer of hardcoded data from the app to the CMS.
1. Make sure the database updates complete in the console log without error
2. visit http://vote-gov.lndo.site/admin/content/block/27 and enter test content into the new fields: "Step indicator aria label", "Edit button aria label" and save the block
3. visit http://vote-gov.lndo.site/admin/reports/dblog to make sure there are no log errors
4. visit http://vote-gov.lndo.site/nvrf/assets/strings.json to make sure the test data is displayed on the endpoint
=> VOTE-3337 Add new subfields to nvrf_step field type

config/non_production/config_split.patch.core.extension.yml, config/non_production/stage_file_proxy.settings.yml
[VOTE-3304](https://cm-jira.usa.gov/browse/VOTE-3304)
Disable Stage File Proxy module on non-production environments.
1. Set your environment for config_split to "non_production" in your settings.local.php
`$config['config_split.config_split.non_production']['status'] = TRUE;`
2. Run `lando rebuild`
1. Confirm that the Stage File Proxy module is disabled after you rebuild or import configs.
=> VOTE-3304: Disable Stage File Proxy on non production environments.

web/themes/custom/votegov/src/sass/components/hero.scss, web/themes/custom/votegov/src/sass/uswds-overrides/usa-breadcrumb.scss, web/themes/custom/votegov/templates/component/hero.html.twig, web/themes/custom/votegov/templates/layout/page.html.twig, web/themes/custom/votegov/templates/navigation/breadcrumb.html.twig, web/themes/custom/votegov/templates/paragraph/paragraph--registration-tool.html.twig
https://cm-jira.usa.gov/browse/VOTE-2928
Move breadcrumbs out of the main landmark for improved screen reader experience.
1. cd into the votegov theme directory and run `npm run build`
1. visit https://vote-gov.lndo.site/guide-to-voting/college-student and confirm with screen reader by skipping to main content the breadcrumb is avoided.
2. Test styles on normal and high-contrast mode.
3. Test styles on desktop and mobile.
4. Test styles on Chrome, Firefox, Safari, Edge.
=> VOTE-2928: Move breadcrumbs out of main landmark for screen readers

composer.json, composer.lock, config/sync/core.entity_form_display.taxonomy_term.nvrf_field.default.yml, config/sync/core.extension.yml
[VOTE-3503](https://cm-jira.usa.gov/browse/VOTE-3503) - Enable and configure uuid_extra module
[VOTE-3532](https://cm-jira.usa.gov/browse/VOTE-3532) - Drupal module updates
Update drupal modules and install, enable, and configure uuid_extra module.
1. Login as admin and view edit form for NVRF Field taxonomy term(s) and confirm that you can view the UUID field displayed.
2. Nothing to test for module updates
=> VOTE-3532/VOTE-3503: Update drupal modules and install, enable, and configure uuid_extra module.

web/sites/default/nonlocal.services.yml, web/sites/default/settings.cloudgov.php
[VOTE-3441](https://cm-jira.usa.gov/browse/VOTE-3441)
Disable select caches during the execution of Tome.
1. To test locally, add the following code to you local settings.php file
`$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/default/nonlocal.services.yml';
if (PHP_SAPI === 'cli' && str_starts_with($_SERVER["argv"][1], 'tome:static')) {
// Disable the page and menu cache on tome runs.
$settings['cache']['bins']['page'] = 'cache.backend.null';
$settings['cache']['bins']['menu'] = 'cache.backend.null';
}`
1. Generate tome and confirm that static site is built correctly without any missing elements.
=> VOTE-3441: Add cache exclusion during tome execution.
